/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var jce = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[8,12],$V1=[1,17],$V2=[1,16],$V3=[15,21,30,43],$V4=[1,36],$V5=[1,40],$V6=[15,27],$V7=[10,15],$V8=[10,15,25],$V9=[1,55],$Va=[1,54],$Vb=[1,56],$Vc=[1,57],$Vd=[10,25,40],$Ve=[2,36],$Vf=[1,74],$Vg=[10,37,38,41,47,50],$Vh=[10,25,37,38,41,47,50];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"jce":3,"deplist":4,"expressions":5,"EOF":6,"dep":7,"INCLUDE":8,"QUOTE":9,"IDENTIFIER":10,"JCE":11,"MODULE":12,"LEFT":13,"structlist":14,"RIGHT":15,"SEMI":16,"interface":17,"def":18,"struct":19,"enum":20,"ENUM":21,"enumitems":22,"enumitem":23,"enumitemDef":24,"COMMA":25,"EQUAL":26,"NUMBER":27,"HEX":28,"UMINUS":29,"STRUCT":30,"itemlist":31,"items":32,"item":33,"REQUIRED":34,"t":35,"propertyName":36,"TYPE":37,"VECTOR":38,"OPEN":39,"CLOSE":40,"MAP":41,"DOUBLE_COLON":42,"INTERFACE":43,"methodlist":44,"LEFT_QUOTE":45,"args":46,"RIGHT_QUOTE":47,"argc":48,"arg":49,"OUT":50,"$accept":0,"$end":1},
terminals_: {2:"error",6:"EOF",8:"INCLUDE",9:"QUOTE",10:"IDENTIFIER",11:"JCE",12:"MODULE",13:"LEFT",15:"RIGHT",16:"SEMI",21:"ENUM",25:"COMMA",26:"EQUAL",27:"NUMBER",28:"HEX",29:"UMINUS",30:"STRUCT",34:"REQUIRED",37:"TYPE",38:"VECTOR",39:"OPEN",40:"CLOSE",41:"MAP",42:"DOUBLE_COLON",43:"INTERFACE",45:"LEFT_QUOTE",47:"RIGHT_QUOTE",50:"OUT"},
productions_: [0,[3,3],[4,0],[4,2],[7,5],[5,6],[5,7],[14,1],[14,2],[18,1],[18,1],[20,6],[22,1],[22,2],[23,1],[23,2],[24,1],[24,3],[24,3],[24,4],[19,3],[31,4],[32,1],[32,2],[33,5],[36,1],[36,4],[36,3],[36,3],[35,1],[35,1],[35,4],[35,6],[35,3],[17,6],[44,6],[46,0],[46,2],[48,2],[48,1],[49,2],[49,3]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

    return {
        deps: $$[$0-2],
        module: $$[$0-1]
    }

break;
case 2:

    this.$ = [];

break;
case 3: case 8:

    this.$ = $$[$0-1].concat($$[$0])

break;
case 4:

    console.log($$[$0-2]);
    this.$ = [$$[$0-2] + $$[$0-1]];

break;
case 5:

        // console.log('MODULE:', $$[$0-4])
        // module.IDENTIFIER = $$[$0-4];

        // this.$ = {
        //     name: $$[$0-4],
        //     structList: $$[$0-2]
        // }
        
        this.$ = t.tsModuleDeclaration(
            t.identifier($$[$0-4]),
            t.tsModuleBlock($$[$0-2])
        );
    
break;
case 6:

    $$[$0-3].push($$[$0-2]);
    this.$ = t.tsModuleDeclaration(
        t.identifier($$[$0-5]),
        t.tsModuleBlock($$[$0-3])
    );

break;
case 7: case 12: case 22:

    this.$ = [$$[$0]];

break;
case 9: case 10: case 14: case 39:

    this.$ = $$[$0];

break;
case 11:

{
    this.$ = t.tsEnumDeclaration(
        t.identifier($$[$0-4]),
        $$[$0-2]
    );
}

break;
case 13:

    this.$ = $$[$0-1].concat($$[$0]);

break;
case 15: case 38:

    this.$ = $$[$0-1];

break;
case 16:

    this.$ = t.tsEnumMember(t.identifier($$[$0]));

break;
case 17:

    {
    const value = Number($$[$0]);
    this.$ = t.tsEnumMember(t.identifier($$[$0-2]), t.numericLiteral(value));
    }

break;
case 18:

    {
    this.$ = t.tsEnumMember(t.identifier($$[$0-2]), t.stringLiteral($$[$0]));
    }

break;
case 19:

    {
    const value = -Number($$[$0]);
    this.$ = t.tsEnumMember(t.identifier($$[$0-3]), t.numericLiteral(value));
    }

break;
case 20:

    this.$ = t.tsInterfaceDeclaration(
        t.identifier($$[$0-1]),
        undefined,
        undefined,
        t.tsInterfaceBody($$[$0])
    );

break;
case 21: case 27: case 28:

    this.$ = $$[$0-2]

break;
case 23:

    // console.log('ERROR', $$[$0-1], $$[$0]);

    this.$ = $$[$0-1].concat($$[$0])

break;
case 24:

    {
        const node = t.tsPropertySignature(
            t.identifier($$[$0-1]),
            t.tsTypeAnnotation($$[$0-2])
        );

        if ($$[$0-3] === 'optional') {
            node.optional = true;
        }

        this.$ = node;
    }

break;
case 25:

    this.$ = $$[$0]

break;
case 26:

    this.$ = $$[$0-3]

break;
case 29:

    // console.log('TYPE:', $$[$0] + '_x');
    if ($$[$0] === 'bool') {
        this.$ = t.tsBooleanKeyword();
    } 
    else if ($$[$0] === 'int') {
        this.$ = t.tsNumberKeyword();
    }
    else {
        this.$ = t.tsStringKeyword();
    }

break;
case 30:

    this.$ = t.tsTypeReference(t.identifier($$[$0]));

break;
case 31:

    this.$ = t.tsTypeReference(
        t.identifier('Array'),
        t.tsTypeParameterInstantiation([
          $$[$0-1]
        ])
      );

break;
case 32:

    // console.log("map:", $$[$0-3]);
    if ($$[$0-3].type === 'TSTypeReference') {
        this.$ = t.tsTypeReference(
                t.identifier('Map'),
                t.tsTypeParameterInstantiation([
                    $$[$0-3],
                    $$[$0-1]
                ])
            );
    } else {
        this.$ = t.tsTypeReference(
            t.identifier('Record'),
            t.tsTypeParameterInstantiation([
                $$[$0-3],
                $$[$0-1]
            ])
        );
    }

break;
case 33:

    // module::struct => namespace.interface
    const left = t.identifier($$[$0-2]);
    const right = t.identifier($$[$0]);
    this.$ = t.tsTypeReference(t.tsQualifiedName(left, right));

break;
case 34:

    // console.log($$[$0-5]);
    // console.log($$[$0-4]);

    this.$ = t.tsInterfaceDeclaration(
        t.identifier($$[$0-4]),
        undefined,
        undefined,
        t.tsInterfaceBody($$[$0-2])
    );

break;
case 35:

    const typeParameters = null;
    const parameters = $$[$0-2][0] || [];
    const typeAnnotation = $$[$0-2][1] ||  t.tsTypeAnnotation(t.tsTypeReference(t.identifier("void")));
    this.$ = [
        t.tsPropertySignature(
            t.identifier($$[$0-4]),
            t.tsTypeAnnotation(
                t.tsFunctionType(
                    typeParameters,
                    parameters,
                    typeAnnotation
                )
            )
        )
    ]

break;
case 37:

    // console.log($$[$0-1], $$[$0]);

break;
case 40:

    console.log($$[$0-1], $$[$0]);

break;
case 41:

    console.log($$[$0-2], $$[$0-1], $$[$0]);

break;
}
},
table: [o($V0,[2,2],{3:1,4:2}),{1:[3]},{5:3,7:4,8:[1,6],12:[1,5]},{6:[1,7]},o($V0,[2,3]),{10:[1,8]},{9:[1,9]},{1:[2,1]},{13:[1,10]},{10:[1,11]},{14:12,18:13,19:14,20:15,21:$V1,30:$V2},{11:[1,18]},{15:[1,19],17:20,18:21,19:14,20:15,21:$V1,30:$V2,43:[1,22]},o($V3,[2,7]),o($V3,[2,9]),o($V3,[2,10]),{10:[1,23]},{10:[1,24]},{9:[1,25]},{16:[1,26]},{15:[1,27]},o($V3,[2,8]),{10:[1,28]},{13:[1,30],31:29},{13:[1,31]},o($V0,[2,4]),{6:[2,5]},{16:[1,32]},{13:[1,33]},o($V3,[2,20]),{27:$V4,32:34,33:35},{10:$V5,22:37,23:38,24:39},{6:[2,6]},{37:[1,42],44:41},{15:[1,43],27:$V4,33:44},o($V6,[2,22]),{34:[1,45]},{10:$V5,15:[1,46],23:47,24:39},o($V7,[2,12]),o($V7,[2,14],{25:[1,48]}),o($V8,[2,16],{26:[1,49]}),{15:[1,50]},{10:[1,51]},{16:[1,52]},o($V6,[2,23]),{10:$V9,35:53,37:$Va,38:$Vb,41:$Vc},{16:[1,58]},o($V7,[2,13]),o($V7,[2,15]),{27:[1,59],28:[1,60],29:[1,61]},{16:[1,62]},{45:[1,63]},o($V3,[2,21]),{10:[1,65],36:64},o($Vd,[2,29]),o($Vd,[2,30],{42:[1,66]}),{39:[1,67]},{39:[1,68]},o($V3,[2,11]),o($V8,[2,17]),o($V8,[2,18]),{27:[1,69]},{15:[2,34]},{10:$V9,35:73,37:$Va,38:$Vb,41:$Vc,46:70,47:$Ve,48:71,49:72,50:$Vf},{16:[1,75]},{16:[2,25],26:[1,76]},{10:[1,77]},{10:$V9,35:78,37:$Va,38:$Vb,41:$Vc},{10:$V9,35:79,37:$Va,38:$Vb,41:$Vc},o($V8,[2,19]),{47:[1,80]},{10:$V9,35:73,37:$Va,38:$Vb,41:$Vc,46:81,47:$Ve,48:71,49:72,50:$Vf},o($Vg,[2,39],{25:[1,82]}),{10:[1,83]},{10:$V9,35:84,37:$Va,38:$Vb,41:$Vc},o($V6,[2,24]),{10:[1,87],27:[1,86],29:[1,85]},o($Vd,[2,33]),{40:[1,88]},{25:[1,89]},{16:[1,90]},{47:[2,37]},o($Vg,[2,38]),o($Vh,[2,40]),{10:[1,91]},{27:[1,92]},{16:[2,27]},{16:[2,28]},o($Vd,[2,31]),{10:$V9,35:93,37:$Va,38:$Vb,41:$Vc},{15:[2,35]},o($Vh,[2,41]),{16:[2,26]},{40:[1,94]},o($Vd,[2,32])],
defaultActions: {7:[2,1],26:[2,5],32:[2,6],62:[2,34],81:[2,37],86:[2,27],87:[2,28],90:[2,35],92:[2,26]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

    const t = require('@babel/types');
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1: /* DO NOTHING */ 
break;
case 2: /* DO NOTHING */ 
break;
case 3: /* DO NOTHING */ 
break;
case 4:return "INCLUDE";
break;
case 5:return "JCE"
break;
case 6:return 6
break;
case 7:return "QUOTE";
break;
case 8: return "MODULE";
break;
case 9: return "STRUCT";
break;
case 10: return "ENUM";
break;
case 11: return "INTERFACE" 
break;
case 12: return "OPEN"; 
break;
case 13: return "CLOSE"; 
break;
case 14: return "LEFT"; 
break;
case 15: return "RIGHT"; 
break;
case 16: return "KEY_OPEN"; 
break;
case 17: return "KEY_CLOSE"; 
break;
case 18: return "LEFT_QUOTE"; 
break;
case 19: return "RIGHT_QUOTE"; 
break;
case 20:return "REQUIRED"
break;
case 21:return "OUT";
break;
case 22:return 37
break;
case 23:return "TYPE"
break;
case 24:return "TYPE"
break;
case 25:return "TYPE"
break;
case 26:return "TYPE"
break;
case 27:return "TYPE"
break;
case 28:return "TYPE"
break;
case 29:return "TYPE"
break;
case 30:return "TYPE"
break;
case 31:return "TYPE"
break;
case 32:return "TYPE"
break;
case 33:return "TYPE"
break;
case 34: return "VECTOR"; 
break;
case 35: return "MAP"; 
break;
case 36: return "IDENTIFIER";
break;
case 37:return "SEMI"
break;
case 38:return "COMMA"
break;
case 39:return "DOUBLE_COLON"
break;
case 40: return "EQUAL"; 
break;
case 41: return "UMINUS"; 
break;
case 42: return "NUMBER"; 
break;
case 43: return "HEX"; 
break;
case 44: return "EOF"; 
break;
}
},
rules: [/^(?:\s+)/,/^(?:\/\/(.*))/,/^(?:[/][*][^*]*[*]+([^*/][^*]*[*]+)*[/])/,/^(?:key\[[^\]]*\];)/,/^(?:#include\b)/,/^(?:\.jce\b)/,/^(?:$)/,/^(?:")/,/^(?:module\b)/,/^(?:struct\b)/,/^(?:enum\b)/,/^(?:interface\b)/,/^(?:<)/,/^(?:>)/,/^(?:\{)/,/^(?:\})/,/^(?:\[)/,/^(?:\])/,/^(?:\()/,/^(?:\))/,/^(?:(require|optional))/,/^(?:out\b)/,/^(?:string\b)/,/^(?:byte\b)/,/^(?:short\b)/,/^(?:bool\b)/,/^(?:int\b)/,/^(?:float\b)/,/^(?:long\b)/,/^(?:double\b)/,/^(?:signed\s+int\b)/,/^(?:unsigned\s+int\b)/,/^(?:unsigned\s+short\b)/,/^(?:unsigned\\s\+byte\b)/,/^(?:vector\b)/,/^(?:map\b)/,/^(?:[a-zA-Z_$][a-zA-Z_$0-9]*)/,/^(?:;)/,/^(?:,)/,/^(?:::)/,/^(?:=)/,/^(?:-)/,/^(?:[0-9]+(\.[0-9]+)?\b)/,/^(?:0[xX][0-9a-fA-F]+)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = jce;
exports.Parser = jce.Parser;
exports.parse = function () { return jce.parse.apply(jce, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}