// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 8.0.9_20200904091838 by TAF Team.
// Generated from `./PushHqData.jce'
// **********************************************************************

/* tslint:disable */
/* eslint-disable */

import * as TafStream from "@taf/taf-stream";
import * as _TAF_MODULE_C_ from "./BasicDataJce";
import * as _TAF_MODULE_E_ from "./CommonJce";
import * as _TAF_MODULE_D_ from "./CommonDataJce";
import * as _TAF_MODULE_B_ from "./FuPanBasicDataJce";
import * as _TAF_MODULE_A_ from "./FuPanCommonJce";
import * as _TAF_MODULE_G_ from "./FupanBlockJce";
import * as _TAF_MODULE_H_ from "./FupanCallAuctionJce";
import * as _TAF_MODULE_F_ from "./FupanHisFactorJce";
import * as _TAF_MODULE_I_ from "./PushHqDataJce";

export namespace FuPan {
    const enum E_BLK_CURR_DATA_TYPE {
        E_BLK_CURR_NO_STOCK = 0,
        E_BLK_CURR_ZT_STOCK = 1,
        E_BLK_CURR_UNZT_STOCK = 2
    }
    function etos(enm:E_BLK_CURR_DATA_TYPE):string;
    function stoe(enm:string):E_BLK_CURR_DATA_TYPE;

    const enum STORM_EYE_IDX_TYPE {
        STORM_EYE_IDX_TYPE_NUM = 0,
        STORM_EYE_IDX_TYPE_LEVEL = 1
    }
    function etos(enm:STORM_EYE_IDX_TYPE):string;
    function stoe(enm:string):STORM_EYE_IDX_TYPE;


    class FStockPoolReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        eStockType: _TAF_MODULE_B_.FuPan.E_STOCK_POOL_TYPE;
        bGetDetail: boolean;
        iBeg: number;
        iWantNum: number;
        iDate: number;
        lRefreshTime: number;

        toObject(): FStockPoolReq.Object;
        readFromObject(json: FStockPoolReq.Object): FStockPoolReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FStockPoolReq;
        static create(is: TafStream.JceInputStream): FStockPoolReq;
    }

    namespace FStockPoolReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            eStockType?: _TAF_MODULE_B_.FuPan.E_STOCK_POOL_TYPE;
            bGetDetail?: boolean;
            iBeg?: number;
            iWantNum?: number;
            iDate?: number;
            lRefreshTime?: number;
        }
    }

    class FStockPoolRsp {
        vecStock: TafStream.List<_TAF_MODULE_B_.FuPan.FZDStockInfo>;
        iSize: number;
        lTime: number;
        iDate: number;

        toObject(): FStockPoolRsp.Object;
        readFromObject(json: FStockPoolRsp.Object): FStockPoolRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FStockPoolRsp;
        static create(is: TafStream.JceInputStream): FStockPoolRsp;
    }

    namespace FStockPoolRsp {
        interface Object {
            vecStock?: Array<_TAF_MODULE_B_.FuPan.FZDStockInfo.Object>;
            iSize?: number;
            lTime?: number;
            iDate?: number;
        }
    }

    class FBatchStockPoolReq {
        vecStockPoolReq: TafStream.List<FuPan.FStockPoolReq>;

        toObject(): FBatchStockPoolReq.Object;
        readFromObject(json: FBatchStockPoolReq.Object): FBatchStockPoolReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBatchStockPoolReq;
        static create(is: TafStream.JceInputStream): FBatchStockPoolReq;
    }

    namespace FBatchStockPoolReq {
        interface Object {
            vecStockPoolReq: Array<FuPan.FStockPoolReq.Object>;
        }
    }

    class FBatchStockPoolRsp {
        vecStockPoolRsp: TafStream.List<FuPan.FStockPoolRsp>;

        toObject(): FBatchStockPoolRsp.Object;
        readFromObject(json: FBatchStockPoolRsp.Object): FBatchStockPoolRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBatchStockPoolRsp;
        static create(is: TafStream.JceInputStream): FBatchStockPoolRsp;
    }

    namespace FBatchStockPoolRsp {
        interface Object {
            vecStockPoolRsp?: Array<FuPan.FStockPoolRsp.Object>;
        }
    }

    class FBoardDetailReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        iMarket: number;
        sCode: string;
        iDate: number;
        eType: _TAF_MODULE_B_.FuPan.E_STOCK_POOL_TYPE;

        toObject(): FBoardDetailReq.Object;
        readFromObject(json: FBoardDetailReq.Object): FBoardDetailReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBoardDetailReq;
        static create(is: TafStream.JceInputStream): FBoardDetailReq;
    }

    namespace FBoardDetailReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            iMarket?: number;
            sCode?: string;
            iDate?: number;
            eType?: _TAF_MODULE_B_.FuPan.E_STOCK_POOL_TYPE;
        }
    }

    class FBoardDetailRsp {
        vecDetail: TafStream.List<_TAF_MODULE_B_.FuPan.FOpenBoardDetail>;

        toObject(): FBoardDetailRsp.Object;
        readFromObject(json: FBoardDetailRsp.Object): FBoardDetailRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBoardDetailRsp;
        static create(is: TafStream.JceInputStream): FBoardDetailRsp;
    }

    namespace FBoardDetailRsp {
        interface Object {
            vecDetail?: Array<_TAF_MODULE_B_.FuPan.FOpenBoardDetail.Object>;
        }
    }

    class FTrendDataType {
        eTrend: _TAF_MODULE_A_.FuPan.E_MARKET_TREND_TYPE;
        eDate: _TAF_MODULE_A_.FuPan.E_TREND_DATE_TYPE;
        iDate: number;
        eFilterType: _TAF_MODULE_B_.FuPan.E_STOCK_FILTER_TYPE;

        toObject(): FTrendDataType.Object;
        readFromObject(json: FTrendDataType.Object): FTrendDataType;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FTrendDataType;
        static create(is: TafStream.JceInputStream): FTrendDataType;
    }

    namespace FTrendDataType {
        interface Object {
            eTrend?: _TAF_MODULE_A_.FuPan.E_MARKET_TREND_TYPE;
            eDate?: _TAF_MODULE_A_.FuPan.E_TREND_DATE_TYPE;
            iDate?: number;
            eFilterType?: _TAF_MODULE_B_.FuPan.E_STOCK_FILTER_TYPE;
        }
    }

    class FMarketTrendReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecType: TafStream.List<FuPan.FTrendDataType>;

        toObject(): FMarketTrendReq.Object;
        readFromObject(json: FMarketTrendReq.Object): FMarketTrendReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FMarketTrendReq;
        static create(is: TafStream.JceInputStream): FMarketTrendReq;
    }

    namespace FMarketTrendReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecType?: Array<FuPan.FTrendDataType.Object>;
        }
    }

    class FMarketTrendRsp {
        stData: _TAF_MODULE_A_.FuPan.FMarketTrendData;

        toObject(): FMarketTrendRsp.Object;
        readFromObject(json: FMarketTrendRsp.Object): FMarketTrendRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FMarketTrendRsp;
        static create(is: TafStream.JceInputStream): FMarketTrendRsp;
    }

    namespace FMarketTrendRsp {
        interface Object {
            stData?: _TAF_MODULE_A_.FuPan.FMarketTrendData.Object;
        }
    }

    class FMarketTrendVecRsp {
        vecData: TafStream.List<_TAF_MODULE_A_.FuPan.FMarketTrendData>;

        toObject(): FMarketTrendVecRsp.Object;
        readFromObject(json: FMarketTrendVecRsp.Object): FMarketTrendVecRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FMarketTrendVecRsp;
        static create(is: TafStream.JceInputStream): FMarketTrendVecRsp;
    }

    namespace FMarketTrendVecRsp {
        interface Object {
            vecData?: Array<_TAF_MODULE_A_.FuPan.FMarketTrendData.Object>;
        }
    }

    class FBlkCurrentReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        iWantNum: number;
        iPos: number;
        eDetail: FuPan.E_BLK_CURR_DATA_TYPE;
        iDate: number;
        lBlkUpdteTime: number;
        iMinZTNum: number;

        toObject(): FBlkCurrentReq.Object;
        readFromObject(json: FBlkCurrentReq.Object): FBlkCurrentReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkCurrentReq;
        static create(is: TafStream.JceInputStream): FBlkCurrentReq;
    }

    namespace FBlkCurrentReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            iWantNum?: number;
            iPos?: number;
            eDetail?: FuPan.E_BLK_CURR_DATA_TYPE;
            iDate?: number;
            lBlkUpdteTime?: number;
            iMinZTNum?: number;
        }
    }

    class FBlkCurrentRsp {
        vecData: TafStream.List<_TAF_MODULE_A_.FuPan.FBlockZTData>;
        iDate: number;
        lBlkUpdteTime: number;

        toObject(): FBlkCurrentRsp.Object;
        readFromObject(json: FBlkCurrentRsp.Object): FBlkCurrentRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkCurrentRsp;
        static create(is: TafStream.JceInputStream): FBlkCurrentRsp;
    }

    namespace FBlkCurrentRsp {
        interface Object {
            vecData?: Array<_TAF_MODULE_A_.FuPan.FBlockZTData.Object>;
            iDate?: number;
            lBlkUpdteTime?: number;
        }
    }

    class FBlkCurZTReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        sCode: string;
        iWantNum: number;
        iPos: number;
        iDate: number;

        toObject(): FBlkCurZTReq.Object;
        readFromObject(json: FBlkCurZTReq.Object): FBlkCurZTReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkCurZTReq;
        static create(is: TafStream.JceInputStream): FBlkCurZTReq;
    }

    namespace FBlkCurZTReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            sCode?: string;
            iWantNum?: number;
            iPos?: number;
            iDate?: number;
        }
    }

    class FBlkCurZTRsp {
        vecStock: TafStream.List<_TAF_MODULE_A_.FuPan.FBlockStockZT>;

        toObject(): FBlkCurZTRsp.Object;
        readFromObject(json: FBlkCurZTRsp.Object): FBlkCurZTRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkCurZTRsp;
        static create(is: TafStream.JceInputStream): FBlkCurZTRsp;
    }

    namespace FBlkCurZTRsp {
        interface Object {
            vecStock?: Array<_TAF_MODULE_A_.FuPan.FBlockStockZT.Object>;
        }
    }

    class FBlkCurUnZTReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        sCode: string;
        iWantNum: number;
        iPos: number;
        iDate: number;

        toObject(): FBlkCurUnZTReq.Object;
        readFromObject(json: FBlkCurUnZTReq.Object): FBlkCurUnZTReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkCurUnZTReq;
        static create(is: TafStream.JceInputStream): FBlkCurUnZTReq;
    }

    namespace FBlkCurUnZTReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            sCode?: string;
            iWantNum?: number;
            iPos?: number;
            iDate?: number;
        }
    }

    class FBlkCurUnZTRsp {
        vecStock: TafStream.List<_TAF_MODULE_A_.FuPan.FBlockStockUnZT>;

        toObject(): FBlkCurUnZTRsp.Object;
        readFromObject(json: FBlkCurUnZTRsp.Object): FBlkCurUnZTRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkCurUnZTRsp;
        static create(is: TafStream.JceInputStream): FBlkCurUnZTRsp;
    }

    namespace FBlkCurUnZTRsp {
        interface Object {
            vecStock?: Array<_TAF_MODULE_A_.FuPan.FBlockStockUnZT.Object>;
        }
    }

    class FStockUnique {
        iMarket: number;
        sCode: string;

        toObject(): FStockUnique.Object;
        readFromObject(json: FStockUnique.Object): FStockUnique;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FStockUnique;
        static create(is: TafStream.JceInputStream): FStockUnique;
    }

    namespace FStockUnique {
        interface Object {
            iMarket?: number;
            sCode?: string;
        }
    }

    class FBlkLastHisReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecStock: TafStream.List<FuPan.FStockUnique>;
        iDayNum: number;
        iDate: number;

        toObject(): FBlkLastHisReq.Object;
        readFromObject(json: FBlkLastHisReq.Object): FBlkLastHisReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkLastHisReq;
        static create(is: TafStream.JceInputStream): FBlkLastHisReq;
    }

    namespace FBlkLastHisReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecStock?: Array<FuPan.FStockUnique.Object>;
            iDayNum?: number;
            iDate?: number;
        }
    }

    class FStockLastHisData {
        iMarket: number;
        sCode: string;
        hisData: TafStream.List<_TAF_MODULE_A_.FuPan.FStockLastHis>;

        toObject(): FStockLastHisData.Object;
        readFromObject(json: FStockLastHisData.Object): FStockLastHisData;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FStockLastHisData;
        static create(is: TafStream.JceInputStream): FStockLastHisData;
    }

    namespace FStockLastHisData {
        interface Object {
            iMarket?: number;
            sCode?: string;
            hisData?: Array<_TAF_MODULE_A_.FuPan.FStockLastHis.Object>;
        }
    }

    class FBlkLastHisRsp {
        vecData: TafStream.List<FuPan.FStockLastHisData>;

        toObject(): FBlkLastHisRsp.Object;
        readFromObject(json: FBlkLastHisRsp.Object): FBlkLastHisRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkLastHisRsp;
        static create(is: TafStream.JceInputStream): FBlkLastHisRsp;
    }

    namespace FBlkLastHisRsp {
        interface Object {
            vecData?: Array<FuPan.FStockLastHisData.Object>;
        }
    }

    class FBlkTimeHisReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        sCode: string;
        iWantNum: number;
        iPos: number;
        iStockNum: number;

        toObject(): FBlkTimeHisReq.Object;
        readFromObject(json: FBlkTimeHisReq.Object): FBlkTimeHisReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkTimeHisReq;
        static create(is: TafStream.JceInputStream): FBlkTimeHisReq;
    }

    namespace FBlkTimeHisReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            sCode?: string;
            iWantNum?: number;
            iPos?: number;
            iStockNum?: number;
        }
    }

    class FBlkTimeHisRsp {
        stData: _TAF_MODULE_A_.FuPan.FBlockTimeTrail;

        toObject(): FBlkTimeHisRsp.Object;
        readFromObject(json: FBlkTimeHisRsp.Object): FBlkTimeHisRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkTimeHisRsp;
        static create(is: TafStream.JceInputStream): FBlkTimeHisRsp;
    }

    namespace FBlkTimeHisRsp {
        interface Object {
            stData?: _TAF_MODULE_A_.FuPan.FBlockTimeTrail.Object;
        }
    }

    class FBlkStockHisReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        sCode: string;
        iWantNum: number;
        iPos: number;

        toObject(): FBlkStockHisReq.Object;
        readFromObject(json: FBlkStockHisReq.Object): FBlkStockHisReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkStockHisReq;
        static create(is: TafStream.JceInputStream): FBlkStockHisReq;
    }

    namespace FBlkStockHisReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            sCode?: string;
            iWantNum?: number;
            iPos?: number;
        }
    }

    class FBlkStockHisRsp {
        stData: _TAF_MODULE_A_.FuPan.FBlockStockTrail;

        toObject(): FBlkStockHisRsp.Object;
        readFromObject(json: FBlkStockHisRsp.Object): FBlkStockHisRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkStockHisRsp;
        static create(is: TafStream.JceInputStream): FBlkStockHisRsp;
    }

    namespace FBlkStockHisRsp {
        interface Object {
            stData?: _TAF_MODULE_A_.FuPan.FBlockStockTrail.Object;
        }
    }

    class FBlkHisTurnReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        iWantNum: number;

        toObject(): FBlkHisTurnReq.Object;
        readFromObject(json: FBlkHisTurnReq.Object): FBlkHisTurnReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkHisTurnReq;
        static create(is: TafStream.JceInputStream): FBlkHisTurnReq;
    }

    namespace FBlkHisTurnReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            iWantNum?: number;
        }
    }

    class FBlkHisTurnRsp {
        vecData: TafStream.List<_TAF_MODULE_A_.FuPan.FBlockZTStatic>;

        toObject(): FBlkHisTurnRsp.Object;
        readFromObject(json: FBlkHisTurnRsp.Object): FBlkHisTurnRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkHisTurnRsp;
        static create(is: TafStream.JceInputStream): FBlkHisTurnRsp;
    }

    namespace FBlkHisTurnRsp {
        interface Object {
            vecData?: Array<_TAF_MODULE_A_.FuPan.FBlockZTStatic.Object>;
        }
    }

    class FLeadBlkReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        iDate: number;
        iBlockType: number;

        toObject(): FLeadBlkReq.Object;
        readFromObject(json: FLeadBlkReq.Object): FLeadBlkReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FLeadBlkReq;
        static create(is: TafStream.JceInputStream): FLeadBlkReq;
    }

    namespace FLeadBlkReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            iDate?: number;
            iBlockType?: number;
        }
    }

    class FLeadBlkRsp {
        vecData: TafStream.List<_TAF_MODULE_I_.IC.SLeadBlkInfo>;

        toObject(): FLeadBlkRsp.Object;
        readFromObject(json: FLeadBlkRsp.Object): FLeadBlkRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FLeadBlkRsp;
        static create(is: TafStream.JceInputStream): FLeadBlkRsp;
    }

    namespace FLeadBlkRsp {
        interface Object {
            vecData?: Array<_TAF_MODULE_I_.IC.SLeadBlkInfo.Object>;
        }
    }

    class FBlkChangesReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        iDate: number;
        eType: _TAF_MODULE_I_.IC.BLOCKCHANGE_TYPE;
        iBlkLeadStockNum: number;
        iWantNum: number;
        iPos: number;
        iBlockType: number;

        toObject(): FBlkChangesReq.Object;
        readFromObject(json: FBlkChangesReq.Object): FBlkChangesReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkChangesReq;
        static create(is: TafStream.JceInputStream): FBlkChangesReq;
    }

    namespace FBlkChangesReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            iDate?: number;
            eType?: _TAF_MODULE_I_.IC.BLOCKCHANGE_TYPE;
            iBlkLeadStockNum?: number;
            iWantNum?: number;
            iPos?: number;
            iBlockType?: number;
        }
    }

    class FBlkChangesRsp {
        vecData: TafStream.List<_TAF_MODULE_I_.IC.SBlockChange>;

        toObject(): FBlkChangesRsp.Object;
        readFromObject(json: FBlkChangesRsp.Object): FBlkChangesRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkChangesRsp;
        static create(is: TafStream.JceInputStream): FBlkChangesRsp;
    }

    namespace FBlkChangesRsp {
        interface Object {
            vecData?: Array<_TAF_MODULE_I_.IC.SBlockChange.Object>;
        }
    }

    class FStockPoolFBoardPeriodReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecStock: TafStream.List<FuPan.FStockUnique>;

        toObject(): FStockPoolFBoardPeriodReq.Object;
        readFromObject(json: FStockPoolFBoardPeriodReq.Object): FStockPoolFBoardPeriodReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FStockPoolFBoardPeriodReq;
        static create(is: TafStream.JceInputStream): FStockPoolFBoardPeriodReq;
    }

    namespace FStockPoolFBoardPeriodReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecStock?: Array<FuPan.FStockUnique.Object>;
        }
    }

    class FStockPoolFBoardPeriodInfo {
        stock: FuPan.FStockUnique;
        stBoard: _TAF_MODULE_B_.FuPan.FBoardPeriod;

        toObject(): FStockPoolFBoardPeriodInfo.Object;
        readFromObject(json: FStockPoolFBoardPeriodInfo.Object): FStockPoolFBoardPeriodInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FStockPoolFBoardPeriodInfo;
        static create(is: TafStream.JceInputStream): FStockPoolFBoardPeriodInfo;
    }

    namespace FStockPoolFBoardPeriodInfo {
        interface Object {
            stock?: FuPan.FStockUnique.Object;
            stBoard?: _TAF_MODULE_B_.FuPan.FBoardPeriod.Object;
        }
    }

    class FStockPoolFBoardPeriodRsp {
        vecStBoardPeriodData: TafStream.List<FuPan.FStockPoolFBoardPeriodInfo>;

        toObject(): FStockPoolFBoardPeriodRsp.Object;
        readFromObject(json: FStockPoolFBoardPeriodRsp.Object): FStockPoolFBoardPeriodRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FStockPoolFBoardPeriodRsp;
        static create(is: TafStream.JceInputStream): FStockPoolFBoardPeriodRsp;
    }

    namespace FStockPoolFBoardPeriodRsp {
        interface Object {
            vecStBoardPeriodData?: Array<FuPan.FStockPoolFBoardPeriodInfo.Object>;
        }
    }

    class FHisFactorReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        eHisFactorType: _TAF_MODULE_F_.FuPan.E_HIS_FACTOR_TYPE;
        nStartDate: number;
        nEndDate: number;
        nDayNum: number;

        toObject(): FHisFactorReq.Object;
        readFromObject(json: FHisFactorReq.Object): FHisFactorReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FHisFactorReq;
        static create(is: TafStream.JceInputStream): FHisFactorReq;
    }

    namespace FHisFactorReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            eHisFactorType?: _TAF_MODULE_F_.FuPan.E_HIS_FACTOR_TYPE;
            nStartDate?: number;
            nEndDate?: number;
            nDayNum?: number;
        }
    }

    class FHisFactorRsp {
        eHisFactorType: _TAF_MODULE_F_.FuPan.E_HIS_FACTOR_TYPE;
        nStartDate: number;
        nEndDate: number;
        nDayNum: number;
        vecHisFactorData: TafStream.List<_TAF_MODULE_F_.FuPan.FHisFactorData>;

        toObject(): FHisFactorRsp.Object;
        readFromObject(json: FHisFactorRsp.Object): FHisFactorRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FHisFactorRsp;
        static create(is: TafStream.JceInputStream): FHisFactorRsp;
    }

    namespace FHisFactorRsp {
        interface Object {
            eHisFactorType?: _TAF_MODULE_F_.FuPan.E_HIS_FACTOR_TYPE;
            nStartDate?: number;
            nEndDate?: number;
            nDayNum?: number;
            vecHisFactorData?: Array<_TAF_MODULE_F_.FuPan.FHisFactorData.Object>;
        }
    }

    class FSubDragonHeadBlkInfo {
        blk: _TAF_MODULE_B_.FuPan.StockInfo;

        toObject(): FSubDragonHeadBlkInfo.Object;
        readFromObject(json: FSubDragonHeadBlkInfo.Object): FSubDragonHeadBlkInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FSubDragonHeadBlkInfo;
        static create(is: TafStream.JceInputStream): FSubDragonHeadBlkInfo;
    }

    namespace FSubDragonHeadBlkInfo {
        interface Object {
            blk?: _TAF_MODULE_B_.FuPan.StockInfo.Object;
        }
    }

    class FBatchSubDragonHeadStockReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecSubject: TafStream.List<FuPan.FSubDragonHeadBlkInfo>;
        lRefreshTime: number;

        toObject(): FBatchSubDragonHeadStockReq.Object;
        readFromObject(json: FBatchSubDragonHeadStockReq.Object): FBatchSubDragonHeadStockReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBatchSubDragonHeadStockReq;
        static create(is: TafStream.JceInputStream): FBatchSubDragonHeadStockReq;
    }

    namespace FBatchSubDragonHeadStockReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecSubject?: Array<FuPan.FSubDragonHeadBlkInfo.Object>;
            lRefreshTime?: number;
        }
    }

    class FSimpleStockInfo {
        iMarket: number;
        sCode: string;

        toObject(): FSimpleStockInfo.Object;
        readFromObject(json: FSimpleStockInfo.Object): FSimpleStockInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FSimpleStockInfo;
        static create(is: TafStream.JceInputStream): FSimpleStockInfo;
    }

    namespace FSimpleStockInfo {
        interface Object {
            iMarket?: number;
            sCode?: string;
        }
    }

    class FSubDragonHeadBlkRspInfo {
        blk: _TAF_MODULE_B_.FuPan.StockInfo;
        vecStk: TafStream.List<FuPan.FSimpleStockInfo>;

        toObject(): FSubDragonHeadBlkRspInfo.Object;
        readFromObject(json: FSubDragonHeadBlkRspInfo.Object): FSubDragonHeadBlkRspInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FSubDragonHeadBlkRspInfo;
        static create(is: TafStream.JceInputStream): FSubDragonHeadBlkRspInfo;
    }

    namespace FSubDragonHeadBlkRspInfo {
        interface Object {
            blk?: _TAF_MODULE_B_.FuPan.StockInfo.Object;
            vecStk?: Array<FuPan.FSimpleStockInfo.Object>;
        }
    }

    class FSubDragonHeadStockRsp {
        vecSubject: TafStream.List<FuPan.FSubDragonHeadBlkRspInfo>;
        lRefreshTime: number;

        toObject(): FSubDragonHeadStockRsp.Object;
        readFromObject(json: FSubDragonHeadStockRsp.Object): FSubDragonHeadStockRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FSubDragonHeadStockRsp;
        static create(is: TafStream.JceInputStream): FSubDragonHeadStockRsp;
    }

    namespace FSubDragonHeadStockRsp {
        interface Object {
            vecSubject?: Array<FuPan.FSubDragonHeadBlkRspInfo.Object>;
            lRefreshTime?: number;
        }
    }

    class FZTTrendStockReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        iCount: number;
        lRefreshTime: number;

        toObject(): FZTTrendStockReq.Object;
        readFromObject(json: FZTTrendStockReq.Object): FZTTrendStockReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZTTrendStockReq;
        static create(is: TafStream.JceInputStream): FZTTrendStockReq;
    }

    namespace FZTTrendStockReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            iCount?: number;
            lRefreshTime?: number;
        }
    }

    class FSimpleZTStockInfo {
        iMarket: number;
        sCode: string;
        iContinueBoard: number;
        stBoard: _TAF_MODULE_B_.FuPan.FBoardPeriod;
        eType: _TAF_MODULE_B_.FuPan.E_STOCK_ZT_TYPE;
        iLastZTime: number;
        vecHotBlk: TafStream.List<_TAF_MODULE_F_.FuPan.FHotBlockInfo>;
        dChgRatio: number;
        bUnOpenNewStock: boolean;

        toObject(): FSimpleZTStockInfo.Object;
        readFromObject(json: FSimpleZTStockInfo.Object): FSimpleZTStockInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FSimpleZTStockInfo;
        static create(is: TafStream.JceInputStream): FSimpleZTStockInfo;
    }

    namespace FSimpleZTStockInfo {
        interface Object {
            iMarket?: number;
            sCode?: string;
            iContinueBoard?: number;
            stBoard?: _TAF_MODULE_B_.FuPan.FBoardPeriod.Object;
            eType?: _TAF_MODULE_B_.FuPan.E_STOCK_ZT_TYPE;
            iLastZTime?: number;
            vecHotBlk?: Array<_TAF_MODULE_F_.FuPan.FHotBlockInfo.Object>;
            dChgRatio?: number;
            bUnOpenNewStock?: boolean;
        }
    }

    class FZTTrendStockRsp {
        vecStock: TafStream.List<FuPan.FSimpleZTStockInfo>;
        lRefreshTime: number;

        toObject(): FZTTrendStockRsp.Object;
        readFromObject(json: FZTTrendStockRsp.Object): FZTTrendStockRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZTTrendStockRsp;
        static create(is: TafStream.JceInputStream): FZTTrendStockRsp;
    }

    namespace FZTTrendStockRsp {
        interface Object {
            vecStock?: Array<FuPan.FSimpleZTStockInfo.Object>;
            lRefreshTime?: number;
        }
    }

    class FZTModelStockReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        iCount: number;
        lRefreshTime: number;

        toObject(): FZTModelStockReq.Object;
        readFromObject(json: FZTModelStockReq.Object): FZTModelStockReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZTModelStockReq;
        static create(is: TafStream.JceInputStream): FZTModelStockReq;
    }

    namespace FZTModelStockReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            iCount?: number;
            lRefreshTime?: number;
        }
    }

    class FZTModelBlkInfo {
        blk: _TAF_MODULE_B_.FuPan.StockInfo;
        vecStock: TafStream.List<FuPan.FSimpleZTStockInfo>;
        iHot: number;

        toObject(): FZTModelBlkInfo.Object;
        readFromObject(json: FZTModelBlkInfo.Object): FZTModelBlkInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZTModelBlkInfo;
        static create(is: TafStream.JceInputStream): FZTModelBlkInfo;
    }

    namespace FZTModelBlkInfo {
        interface Object {
            blk?: _TAF_MODULE_B_.FuPan.StockInfo.Object;
            vecStock?: Array<FuPan.FSimpleZTStockInfo.Object>;
            iHot?: number;
        }
    }

    class FZTModelInfo {
        stkInfo: FuPan.FSimpleZTStockInfo;
        modelInfo: FuPan.FZTModelBlkInfo;

        toObject(): FZTModelInfo.Object;
        readFromObject(json: FZTModelInfo.Object): FZTModelInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZTModelInfo;
        static create(is: TafStream.JceInputStream): FZTModelInfo;
    }

    namespace FZTModelInfo {
        interface Object {
            stkInfo?: FuPan.FSimpleZTStockInfo.Object;
            modelInfo?: FuPan.FZTModelBlkInfo.Object;
        }
    }

    class FZTModelStockRsp {
        vecModelInfo: TafStream.List<FuPan.FZTModelInfo>;
        lRefreshTime: number;

        toObject(): FZTModelStockRsp.Object;
        readFromObject(json: FZTModelStockRsp.Object): FZTModelStockRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZTModelStockRsp;
        static create(is: TafStream.JceInputStream): FZTModelStockRsp;
    }

    namespace FZTModelStockRsp {
        interface Object {
            vecModelInfo?: Array<FuPan.FZTModelInfo.Object>;
            lRefreshTime?: number;
        }
    }

    class FSubNewStockReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        lRefreshTime: number;

        toObject(): FSubNewStockReq.Object;
        readFromObject(json: FSubNewStockReq.Object): FSubNewStockReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FSubNewStockReq;
        static create(is: TafStream.JceInputStream): FSubNewStockReq;
    }

    namespace FSubNewStockReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            lRefreshTime?: number;
        }
    }

    class FSubNewStockInfo {
        stkInfo: _TAF_MODULE_F_.FuPan.FMDaySubNewStockInfo;
        vecBlk: TafStream.List<_TAF_MODULE_B_.FuPan.FBlockSimpleInfo>;

        toObject(): FSubNewStockInfo.Object;
        readFromObject(json: FSubNewStockInfo.Object): FSubNewStockInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FSubNewStockInfo;
        static create(is: TafStream.JceInputStream): FSubNewStockInfo;
    }

    namespace FSubNewStockInfo {
        interface Object {
            stkInfo?: _TAF_MODULE_F_.FuPan.FMDaySubNewStockInfo.Object;
            vecBlk?: Array<_TAF_MODULE_B_.FuPan.FBlockSimpleInfo.Object>;
        }
    }

    class FSubNewStockRsp {
        vecStk: TafStream.List<FuPan.FSubNewStockInfo>;
        lRefreshTime: number;

        toObject(): FSubNewStockRsp.Object;
        readFromObject(json: FSubNewStockRsp.Object): FSubNewStockRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FSubNewStockRsp;
        static create(is: TafStream.JceInputStream): FSubNewStockRsp;
    }

    namespace FSubNewStockRsp {
        interface Object {
            vecStk?: Array<FuPan.FSubNewStockInfo.Object>;
            lRefreshTime?: number;
        }
    }

    class FBlkUnuActReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        lRefreshTime: number;

        toObject(): FBlkUnuActReq.Object;
        readFromObject(json: FBlkUnuActReq.Object): FBlkUnuActReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkUnuActReq;
        static create(is: TafStream.JceInputStream): FBlkUnuActReq;
    }

    namespace FBlkUnuActReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            lRefreshTime?: number;
        }
    }

    class FBlkUnuActDetailInfo {
        blkUnuAct: _TAF_MODULE_F_.FuPan.FBlkUnuActInfo;
        iNDaysUnuActTime: number;

        toObject(): FBlkUnuActDetailInfo.Object;
        readFromObject(json: FBlkUnuActDetailInfo.Object): FBlkUnuActDetailInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkUnuActDetailInfo;
        static create(is: TafStream.JceInputStream): FBlkUnuActDetailInfo;
    }

    namespace FBlkUnuActDetailInfo {
        interface Object {
            blkUnuAct?: _TAF_MODULE_F_.FuPan.FBlkUnuActInfo.Object;
            iNDaysUnuActTime?: number;
        }
    }

    class FBlkUnuActRsp {
        vecBlkUnuActDetail: TafStream.List<FuPan.FBlkUnuActDetailInfo>;
        lRefreshTime: number;

        toObject(): FBlkUnuActRsp.Object;
        readFromObject(json: FBlkUnuActRsp.Object): FBlkUnuActRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkUnuActRsp;
        static create(is: TafStream.JceInputStream): FBlkUnuActRsp;
    }

    namespace FBlkUnuActRsp {
        interface Object {
            vecBlkUnuActDetail?: Array<FuPan.FBlkUnuActDetailInfo.Object>;
            lRefreshTime?: number;
        }
    }

    class FBlkUnuActFlagReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        lRefreshTime: number;

        toObject(): FBlkUnuActFlagReq.Object;
        readFromObject(json: FBlkUnuActFlagReq.Object): FBlkUnuActFlagReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkUnuActFlagReq;
        static create(is: TafStream.JceInputStream): FBlkUnuActFlagReq;
    }

    namespace FBlkUnuActFlagReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            lRefreshTime?: number;
        }
    }

    class FBlkUnuActFlagRsp {
        vecBlkUnuActTag: TafStream.List<_TAF_MODULE_F_.FuPan.FBlkUnuActTagInfo>;
        lRefreshTime: number;

        toObject(): FBlkUnuActFlagRsp.Object;
        readFromObject(json: FBlkUnuActFlagRsp.Object): FBlkUnuActFlagRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkUnuActFlagRsp;
        static create(is: TafStream.JceInputStream): FBlkUnuActFlagRsp;
    }

    namespace FBlkUnuActFlagRsp {
        interface Object {
            vecBlkUnuActTag?: Array<_TAF_MODULE_F_.FuPan.FBlkUnuActTagInfo.Object>;
            lRefreshTime?: number;
        }
    }

    class FHotPointBlkStkReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        lRefreshTime: number;

        toObject(): FHotPointBlkStkReq.Object;
        readFromObject(json: FHotPointBlkStkReq.Object): FHotPointBlkStkReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FHotPointBlkStkReq;
        static create(is: TafStream.JceInputStream): FHotPointBlkStkReq;
    }

    namespace FHotPointBlkStkReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            lRefreshTime?: number;
        }
    }

    class FHotPointBlkStockInfo {
        stkInfo: FuPan.FSimpleZTStockInfo;
        iDragonHeadIdx: number;

        toObject(): FHotPointBlkStockInfo.Object;
        readFromObject(json: FHotPointBlkStockInfo.Object): FHotPointBlkStockInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FHotPointBlkStockInfo;
        static create(is: TafStream.JceInputStream): FHotPointBlkStockInfo;
    }

    namespace FHotPointBlkStockInfo {
        interface Object {
            stkInfo?: FuPan.FSimpleZTStockInfo.Object;
            iDragonHeadIdx?: number;
        }
    }

    class FHotPointBlkRspInfo {
        blk: _TAF_MODULE_B_.FuPan.StockInfo;
        vecStk: TafStream.List<FuPan.FHotPointBlkStockInfo>;
        iHot: number;

        toObject(): FHotPointBlkRspInfo.Object;
        readFromObject(json: FHotPointBlkRspInfo.Object): FHotPointBlkRspInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FHotPointBlkRspInfo;
        static create(is: TafStream.JceInputStream): FHotPointBlkRspInfo;
    }

    namespace FHotPointBlkRspInfo {
        interface Object {
            blk?: _TAF_MODULE_B_.FuPan.StockInfo.Object;
            vecStk?: Array<FuPan.FHotPointBlkStockInfo.Object>;
            iHot?: number;
        }
    }

    class FHotPointBlkStkRsp {
        vecHotPointBlkStk: TafStream.List<FuPan.FHotPointBlkRspInfo>;
        lRefreshTime: number;

        toObject(): FHotPointBlkStkRsp.Object;
        readFromObject(json: FHotPointBlkStkRsp.Object): FHotPointBlkStkRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FHotPointBlkStkRsp;
        static create(is: TafStream.JceInputStream): FHotPointBlkStkRsp;
    }

    namespace FHotPointBlkStkRsp {
        interface Object {
            vecHotPointBlkStk?: Array<FuPan.FHotPointBlkRspInfo.Object>;
            lRefreshTime?: number;
        }
    }

    class FUltraShortTermStkReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        lRefreshTime: number;

        toObject(): FUltraShortTermStkReq.Object;
        readFromObject(json: FUltraShortTermStkReq.Object): FUltraShortTermStkReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FUltraShortTermStkReq;
        static create(is: TafStream.JceInputStream): FUltraShortTermStkReq;
    }

    namespace FUltraShortTermStkReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            lRefreshTime?: number;
        }
    }

    class FUltraShortTermStkRsp {
        stUltraStkPool: _TAF_MODULE_F_.FuPan.FUltraShorttermStkPool;
        lRefreshTime: number;

        toObject(): FUltraShortTermStkRsp.Object;
        readFromObject(json: FUltraShortTermStkRsp.Object): FUltraShortTermStkRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FUltraShortTermStkRsp;
        static create(is: TafStream.JceInputStream): FUltraShortTermStkRsp;
    }

    namespace FUltraShortTermStkRsp {
        interface Object {
            stUltraStkPool?: _TAF_MODULE_F_.FuPan.FUltraShorttermStkPool.Object;
            lRefreshTime?: number;
        }
    }

    class FCatchBullStkReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        lRefreshTime: number;

        toObject(): FCatchBullStkReq.Object;
        readFromObject(json: FCatchBullStkReq.Object): FCatchBullStkReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FCatchBullStkReq;
        static create(is: TafStream.JceInputStream): FCatchBullStkReq;
    }

    namespace FCatchBullStkReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            lRefreshTime?: number;
        }
    }

    class FCatchBullStkRsp {
        vecZtStk: TafStream.List<FuPan.FSimpleZTStockInfo>;
        vecFbStk: TafStream.List<FuPan.FSimpleZTStockInfo>;
        vecSnStk: TafStream.List<FuPan.FSimpleZTStockInfo>;
        lRefreshTime: number;

        toObject(): FCatchBullStkRsp.Object;
        readFromObject(json: FCatchBullStkRsp.Object): FCatchBullStkRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FCatchBullStkRsp;
        static create(is: TafStream.JceInputStream): FCatchBullStkRsp;
    }

    namespace FCatchBullStkRsp {
        interface Object {
            vecZtStk?: Array<FuPan.FSimpleZTStockInfo.Object>;
            vecFbStk?: Array<FuPan.FSimpleZTStockInfo.Object>;
            vecSnStk?: Array<FuPan.FSimpleZTStockInfo.Object>;
            lRefreshTime?: number;
        }
    }

    class FUltraShtLastZtStkReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        lRefreshTime: number;

        toObject(): FUltraShtLastZtStkReq.Object;
        readFromObject(json: FUltraShtLastZtStkReq.Object): FUltraShtLastZtStkReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FUltraShtLastZtStkReq;
        static create(is: TafStream.JceInputStream): FUltraShtLastZtStkReq;
    }

    namespace FUltraShtLastZtStkReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            lRefreshTime?: number;
        }
    }

    class FUltraShtLastZtStkRspInfo {
        stkInfo: FuPan.FSimpleZTStockInfo;
        eOriPool: _TAF_MODULE_F_.FuPan.E_UNITED_STK_POOL_TYPE;
        iLastZTTimeRank: number;

        toObject(): FUltraShtLastZtStkRspInfo.Object;
        readFromObject(json: FUltraShtLastZtStkRspInfo.Object): FUltraShtLastZtStkRspInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FUltraShtLastZtStkRspInfo;
        static create(is: TafStream.JceInputStream): FUltraShtLastZtStkRspInfo;
    }

    namespace FUltraShtLastZtStkRspInfo {
        interface Object {
            stkInfo?: FuPan.FSimpleZTStockInfo.Object;
            eOriPool?: _TAF_MODULE_F_.FuPan.E_UNITED_STK_POOL_TYPE;
            iLastZTTimeRank?: number;
        }
    }

    class FUltraShtLastZtStkRsp {
        vecStk: TafStream.List<FuPan.FUltraShtLastZtStkRspInfo>;
        lRefreshTime: number;

        toObject(): FUltraShtLastZtStkRsp.Object;
        readFromObject(json: FUltraShtLastZtStkRsp.Object): FUltraShtLastZtStkRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FUltraShtLastZtStkRsp;
        static create(is: TafStream.JceInputStream): FUltraShtLastZtStkRsp;
    }

    namespace FUltraShtLastZtStkRsp {
        interface Object {
            vecStk?: Array<FuPan.FUltraShtLastZtStkRspInfo.Object>;
            lRefreshTime?: number;
        }
    }

    class FBlkBasicDataReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecBlk: TafStream.List<_TAF_MODULE_B_.FuPan.StockInfo>;
        eBasicDataType: _TAF_MODULE_G_.FuPan.E_BLK_BASIC_DATA_TYPE;
        iEndDate: number;
        iPreDayNum: number;
        iCmd: number;

        toObject(): FBlkBasicDataReq.Object;
        readFromObject(json: FBlkBasicDataReq.Object): FBlkBasicDataReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkBasicDataReq;
        static create(is: TafStream.JceInputStream): FBlkBasicDataReq;
    }

    namespace FBlkBasicDataReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecBlk?: Array<_TAF_MODULE_B_.FuPan.StockInfo.Object>;
            eBasicDataType?: _TAF_MODULE_G_.FuPan.E_BLK_BASIC_DATA_TYPE;
            iEndDate?: number;
            iPreDayNum?: number;
            iCmd?: number;
        }
    }

    class FDateBlkBasicData {
        iDate: number;
        vecData: TafStream.List<_TAF_MODULE_G_.FuPan.FBlockBasicData>;

        toObject(): FDateBlkBasicData.Object;
        readFromObject(json: FDateBlkBasicData.Object): FDateBlkBasicData;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FDateBlkBasicData;
        static create(is: TafStream.JceInputStream): FDateBlkBasicData;
    }

    namespace FDateBlkBasicData {
        interface Object {
            iDate?: number;
            vecData?: Array<_TAF_MODULE_G_.FuPan.FBlockBasicData.Object>;
        }
    }

    class FBlkBasicDataRsp {
        eBasicDataType: _TAF_MODULE_G_.FuPan.E_BLK_BASIC_DATA_TYPE;
        vecDateData: TafStream.List<FuPan.FDateBlkBasicData>;

        toObject(): FBlkBasicDataRsp.Object;
        readFromObject(json: FBlkBasicDataRsp.Object): FBlkBasicDataRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkBasicDataRsp;
        static create(is: TafStream.JceInputStream): FBlkBasicDataRsp;
    }

    namespace FBlkBasicDataRsp {
        interface Object {
            eBasicDataType?: _TAF_MODULE_G_.FuPan.E_BLK_BASIC_DATA_TYPE;
            vecDateData?: Array<FuPan.FDateBlkBasicData.Object>;
        }
    }

    class FBlkStkDataReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecBlk: TafStream.List<_TAF_MODULE_B_.FuPan.StockInfo>;
        iStkType: number;
        iEndDate: number;
        iPreDayNum: number;

        toObject(): FBlkStkDataReq.Object;
        readFromObject(json: FBlkStkDataReq.Object): FBlkStkDataReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkStkDataReq;
        static create(is: TafStream.JceInputStream): FBlkStkDataReq;
    }

    namespace FBlkStkDataReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecBlk?: Array<_TAF_MODULE_B_.FuPan.StockInfo.Object>;
            iStkType?: number;
            iEndDate?: number;
            iPreDayNum?: number;
        }
    }

    class FDateBlkStkData {
        iDate: number;
        vecBlkStk: TafStream.List<_TAF_MODULE_G_.FuPan.FBlockStkCompData>;

        toObject(): FDateBlkStkData.Object;
        readFromObject(json: FDateBlkStkData.Object): FDateBlkStkData;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FDateBlkStkData;
        static create(is: TafStream.JceInputStream): FDateBlkStkData;
    }

    namespace FDateBlkStkData {
        interface Object {
            iDate?: number;
            vecBlkStk?: Array<_TAF_MODULE_G_.FuPan.FBlockStkCompData.Object>;
        }
    }

    class FBlkStkDataRsp {
        iStkType: number;
        vecDateBlkStk: TafStream.List<FuPan.FDateBlkStkData>;

        toObject(): FBlkStkDataRsp.Object;
        readFromObject(json: FBlkStkDataRsp.Object): FBlkStkDataRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkStkDataRsp;
        static create(is: TafStream.JceInputStream): FBlkStkDataRsp;
    }

    namespace FBlkStkDataRsp {
        interface Object {
            iStkType?: number;
            vecDateBlkStk?: Array<FuPan.FDateBlkStkData.Object>;
        }
    }

    class FBatchStkDataReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecStk: TafStream.List<_TAF_MODULE_B_.FuPan.StockInfo>;
        iDate: number;

        toObject(): FBatchStkDataReq.Object;
        readFromObject(json: FBatchStkDataReq.Object): FBatchStkDataReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBatchStkDataReq;
        static create(is: TafStream.JceInputStream): FBatchStkDataReq;
    }

    namespace FBatchStkDataReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecStk?: Array<_TAF_MODULE_B_.FuPan.StockInfo.Object>;
            iDate?: number;
        }
    }

    class FBatchStkDataRsp {
        iDate: number;
        vecStk: TafStream.List<_TAF_MODULE_G_.FuPan.FBlockStockInfo>;

        toObject(): FBatchStkDataRsp.Object;
        readFromObject(json: FBatchStkDataRsp.Object): FBatchStkDataRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBatchStkDataRsp;
        static create(is: TafStream.JceInputStream): FBatchStkDataRsp;
    }

    namespace FBatchStkDataRsp {
        interface Object {
            iDate?: number;
            vecStk?: Array<_TAF_MODULE_G_.FuPan.FBlockStockInfo.Object>;
        }
    }

    class FBlkExtDataReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        eBlkDataType: _TAF_MODULE_G_.FuPan.E_BLOCK_DATA_TYPE;
        iStartDate: number;
        iEndDate: number;
        iPreDayNum: number;
        iSubCmd: number;

        toObject(): FBlkExtDataReq.Object;
        readFromObject(json: FBlkExtDataReq.Object): FBlkExtDataReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkExtDataReq;
        static create(is: TafStream.JceInputStream): FBlkExtDataReq;
    }

    namespace FBlkExtDataReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            eBlkDataType?: _TAF_MODULE_G_.FuPan.E_BLOCK_DATA_TYPE;
            iStartDate?: number;
            iEndDate?: number;
            iPreDayNum?: number;
            iSubCmd?: number;
        }
    }

    class FBlkExtDataRsp {
        eBlkDataType: _TAF_MODULE_G_.FuPan.E_BLOCK_DATA_TYPE;
        vecExtData: TafStream.List<_TAF_MODULE_G_.FuPan.FBlockExternData>;

        toObject(): FBlkExtDataRsp.Object;
        readFromObject(json: FBlkExtDataRsp.Object): FBlkExtDataRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkExtDataRsp;
        static create(is: TafStream.JceInputStream): FBlkExtDataRsp;
    }

    namespace FBlkExtDataRsp {
        interface Object {
            eBlkDataType?: _TAF_MODULE_G_.FuPan.E_BLOCK_DATA_TYPE;
            vecExtData?: Array<_TAF_MODULE_G_.FuPan.FBlockExternData.Object>;
        }
    }

    class FBlkStormEyeIdxReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        eIdxType: FuPan.STORM_EYE_IDX_TYPE;
        iStartDate: number;
        iEndDate: number;
        vecBlk: TafStream.List<_TAF_MODULE_B_.FuPan.StockInfo>;

        toObject(): FBlkStormEyeIdxReq.Object;
        readFromObject(json: FBlkStormEyeIdxReq.Object): FBlkStormEyeIdxReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkStormEyeIdxReq;
        static create(is: TafStream.JceInputStream): FBlkStormEyeIdxReq;
    }

    namespace FBlkStormEyeIdxReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            eIdxType?: FuPan.STORM_EYE_IDX_TYPE;
            iStartDate?: number;
            iEndDate?: number;
            vecBlk?: Array<_TAF_MODULE_B_.FuPan.StockInfo.Object>;
        }
    }

    class FStromEyeNumIdx {
        iDate: number;
        stStormNum: _TAF_MODULE_G_.FuPan.FBlockStormNum;

        toObject(): FStromEyeNumIdx.Object;
        readFromObject(json: FStromEyeNumIdx.Object): FStromEyeNumIdx;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FStromEyeNumIdx;
        static create(is: TafStream.JceInputStream): FStromEyeNumIdx;
    }

    namespace FStromEyeNumIdx {
        interface Object {
            iDate?: number;
            stStormNum?: _TAF_MODULE_G_.FuPan.FBlockStormNum.Object;
        }
    }

    class FStormEyeLv {
        iDate: number;
        iZTStkNum: number;
        iAccZTStkNum: number;

        toObject(): FStormEyeLv.Object;
        readFromObject(json: FStormEyeLv.Object): FStormEyeLv;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FStormEyeLv;
        static create(is: TafStream.JceInputStream): FStormEyeLv;
    }

    namespace FStormEyeLv {
        interface Object {
            iDate?: number;
            iZTStkNum?: number;
            iAccZTStkNum?: number;
        }
    }

    class FBlkStormEyeLvIdx {
        blk: _TAF_MODULE_B_.FuPan.FBlockSimpleInfo;
        vecLv: TafStream.List<FuPan.FStormEyeLv>;

        toObject(): FBlkStormEyeLvIdx.Object;
        readFromObject(json: FBlkStormEyeLvIdx.Object): FBlkStormEyeLvIdx;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkStormEyeLvIdx;
        static create(is: TafStream.JceInputStream): FBlkStormEyeLvIdx;
    }

    namespace FBlkStormEyeLvIdx {
        interface Object {
            blk?: _TAF_MODULE_B_.FuPan.FBlockSimpleInfo.Object;
            vecLv?: Array<FuPan.FStormEyeLv.Object>;
        }
    }

    class FBlkStormEyeIdxRsp {
        vecStormNum: TafStream.List<FuPan.FStromEyeNumIdx>;
        vecStormLv: TafStream.List<FuPan.FBlkStormEyeLvIdx>;

        toObject(): FBlkStormEyeIdxRsp.Object;
        readFromObject(json: FBlkStormEyeIdxRsp.Object): FBlkStormEyeIdxRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBlkStormEyeIdxRsp;
        static create(is: TafStream.JceInputStream): FBlkStormEyeIdxRsp;
    }

    namespace FBlkStormEyeIdxRsp {
        interface Object {
            vecStormNum?: Array<FuPan.FStromEyeNumIdx.Object>;
            vecStormLv?: Array<FuPan.FBlkStormEyeLvIdx.Object>;
        }
    }

    class FBatchStkCaUnuActReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecStk: TafStream.List<_TAF_MODULE_B_.FuPan.StockInfo>;

        toObject(): FBatchStkCaUnuActReq.Object;
        readFromObject(json: FBatchStkCaUnuActReq.Object): FBatchStkCaUnuActReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBatchStkCaUnuActReq;
        static create(is: TafStream.JceInputStream): FBatchStkCaUnuActReq;
    }

    namespace FBatchStkCaUnuActReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecStk?: Array<_TAF_MODULE_B_.FuPan.StockInfo.Object>;
        }
    }

    class FBatchStkCaUnuActRsp {
        vecStkCaUnuAct: TafStream.List<_TAF_MODULE_H_.FuPan.FStkAllCaUnuAct>;

        toObject(): FBatchStkCaUnuActRsp.Object;
        readFromObject(json: FBatchStkCaUnuActRsp.Object): FBatchStkCaUnuActRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBatchStkCaUnuActRsp;
        static create(is: TafStream.JceInputStream): FBatchStkCaUnuActRsp;
    }

    namespace FBatchStkCaUnuActRsp {
        interface Object {
            vecStkCaUnuAct?: Array<_TAF_MODULE_H_.FuPan.FStkAllCaUnuAct.Object>;
        }
    }

    class FMultiCaUnuActTypeDataReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecType: TafStream.List<_TAF_MODULE_H_.FuPan.E_CALL_AUCTION_DATA_TYPE>;
        iStartDate: number;
        iEndDate: number;
        iPreDayNum: number;

        toObject(): FMultiCaUnuActTypeDataReq.Object;
        readFromObject(json: FMultiCaUnuActTypeDataReq.Object): FMultiCaUnuActTypeDataReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FMultiCaUnuActTypeDataReq;
        static create(is: TafStream.JceInputStream): FMultiCaUnuActTypeDataReq;
    }

    namespace FMultiCaUnuActTypeDataReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecType?: Array<_TAF_MODULE_H_.FuPan.E_CALL_AUCTION_DATA_TYPE>;
            iStartDate?: number;
            iEndDate?: number;
            iPreDayNum?: number;
        }
    }

    class FNumOfCaUnuActTypeStkReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecType: TafStream.List<_TAF_MODULE_H_.FuPan.E_CALL_AUCTION_DATA_TYPE>;
        iStartDate: number;
        iEndDate: number;
        iPreDayNum: number;
        bWantAll: boolean;

        toObject(): FNumOfCaUnuActTypeStkReq.Object;
        readFromObject(json: FNumOfCaUnuActTypeStkReq.Object): FNumOfCaUnuActTypeStkReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FNumOfCaUnuActTypeStkReq;
        static create(is: TafStream.JceInputStream): FNumOfCaUnuActTypeStkReq;
    }

    namespace FNumOfCaUnuActTypeStkReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecType?: Array<_TAF_MODULE_H_.FuPan.E_CALL_AUCTION_DATA_TYPE>;
            iStartDate?: number;
            iEndDate?: number;
            iPreDayNum?: number;
            bWantAll?: boolean;
        }
    }

    class FCaUnuActTypeDataReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        eType: _TAF_MODULE_H_.FuPan.E_CALL_AUCTION_DATA_TYPE;
        iStartDate: number;
        iEndDate: number;
        iPreDayNum: number;
        iSubCmd: number;

        toObject(): FCaUnuActTypeDataReq.Object;
        readFromObject(json: FCaUnuActTypeDataReq.Object): FCaUnuActTypeDataReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FCaUnuActTypeDataReq;
        static create(is: TafStream.JceInputStream): FCaUnuActTypeDataReq;
    }

    namespace FCaUnuActTypeDataReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            eType?: _TAF_MODULE_H_.FuPan.E_CALL_AUCTION_DATA_TYPE;
            iStartDate?: number;
            iEndDate?: number;
            iPreDayNum?: number;
            iSubCmd?: number;
        }
    }

    class FCaUnuActTypeDataRsq {
        eType: _TAF_MODULE_H_.FuPan.E_CALL_AUCTION_DATA_TYPE;
        vecCaUnuAct: TafStream.List<_TAF_MODULE_H_.FuPan.FCaUnuActData>;

        toObject(): FCaUnuActTypeDataRsq.Object;
        readFromObject(json: FCaUnuActTypeDataRsq.Object): FCaUnuActTypeDataRsq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FCaUnuActTypeDataRsq;
        static create(is: TafStream.JceInputStream): FCaUnuActTypeDataRsq;
    }

    namespace FCaUnuActTypeDataRsq {
        interface Object {
            eType?: _TAF_MODULE_H_.FuPan.E_CALL_AUCTION_DATA_TYPE;
            vecCaUnuAct?: Array<_TAF_MODULE_H_.FuPan.FCaUnuActData.Object>;
        }
    }

    class FCaUnuActLevelStkReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        eLevel: _TAF_MODULE_H_.FuPan.E_CA_UNU_ACT_LEVEL;
        iStartDate: number;
        iEndDate: number;
        iPreDayNum: number;

        toObject(): FCaUnuActLevelStkReq.Object;
        readFromObject(json: FCaUnuActLevelStkReq.Object): FCaUnuActLevelStkReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FCaUnuActLevelStkReq;
        static create(is: TafStream.JceInputStream): FCaUnuActLevelStkReq;
    }

    namespace FCaUnuActLevelStkReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            eLevel?: _TAF_MODULE_H_.FuPan.E_CA_UNU_ACT_LEVEL;
            iStartDate?: number;
            iEndDate?: number;
            iPreDayNum?: number;
        }
    }

    class FDateCaUnuActLevelStk {
        iDate: number;
        vecCaUnuActStk: TafStream.List<_TAF_MODULE_H_.FuPan.FStkLastCaUnuAct>;

        toObject(): FDateCaUnuActLevelStk.Object;
        readFromObject(json: FDateCaUnuActLevelStk.Object): FDateCaUnuActLevelStk;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FDateCaUnuActLevelStk;
        static create(is: TafStream.JceInputStream): FDateCaUnuActLevelStk;
    }

    namespace FDateCaUnuActLevelStk {
        interface Object {
            iDate?: number;
            vecCaUnuActStk?: Array<_TAF_MODULE_H_.FuPan.FStkLastCaUnuAct.Object>;
        }
    }

    class FCaUnuActLevelStkRsp {
        eLevel: _TAF_MODULE_H_.FuPan.E_CA_UNU_ACT_LEVEL;
        vecCaLevel: TafStream.List<FuPan.FDateCaUnuActLevelStk>;

        toObject(): FCaUnuActLevelStkRsp.Object;
        readFromObject(json: FCaUnuActLevelStkRsp.Object): FCaUnuActLevelStkRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FCaUnuActLevelStkRsp;
        static create(is: TafStream.JceInputStream): FCaUnuActLevelStkRsp;
    }

    namespace FCaUnuActLevelStkRsp {
        interface Object {
            eLevel?: _TAF_MODULE_H_.FuPan.E_CA_UNU_ACT_LEVEL;
            vecCaLevel?: Array<FuPan.FDateCaUnuActLevelStk.Object>;
        }
    }

    class FAllCallAuctionDataRsp {
        vecAllCaUnuAct: TafStream.List<_TAF_MODULE_H_.FuPan.FCaUnuActTypeData>;

        toObject(): FAllCallAuctionDataRsp.Object;
        readFromObject(json: FAllCallAuctionDataRsp.Object): FAllCallAuctionDataRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FAllCallAuctionDataRsp;
        static create(is: TafStream.JceInputStream): FAllCallAuctionDataRsp;
    }

    namespace FAllCallAuctionDataRsp {
        interface Object {
            vecAllCaUnuAct?: Array<_TAF_MODULE_H_.FuPan.FCaUnuActTypeData.Object>;
        }
    }

    class FNumOfCallAuctionStkRsp {
        mapNumOfStk: TafStream.HeroMap<_TAF_MODULE_H_.FuPan.E_CALL_AUCTION_DATA_TYPE, number>;
        iNumOfAllStk: number;

        toObject(): FNumOfCallAuctionStkRsp.Object;
        readFromObject(json: FNumOfCallAuctionStkRsp.Object): FNumOfCallAuctionStkRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FNumOfCallAuctionStkRsp;
        static create(is: TafStream.JceInputStream): FNumOfCallAuctionStkRsp;
    }

    namespace FNumOfCallAuctionStkRsp {
        interface Object {
            mapNumOfStk?: Record<string, number>;
            iNumOfAllStk?: number;
        }
    }

    class FZDPanKouInfoReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecStk: TafStream.List<_TAF_MODULE_B_.FuPan.StockInfo>;

        toObject(): FZDPanKouInfoReq.Object;
        readFromObject(json: FZDPanKouInfoReq.Object): FZDPanKouInfoReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZDPanKouInfoReq;
        static create(is: TafStream.JceInputStream): FZDPanKouInfoReq;
    }

    namespace FZDPanKouInfoReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecStk?: Array<_TAF_MODULE_B_.FuPan.StockInfo.Object>;
        }
    }

    class FZDPanKouInfo {
        iMarket: number;
        strCode: string;
        strStockZTReason: string;
        dCurFDAmount: number;
        dFDRatio: number;
        dHighFDAmout: number;
        dZTTradeAmout: number;

        toObject(): FZDPanKouInfo.Object;
        readFromObject(json: FZDPanKouInfo.Object): FZDPanKouInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZDPanKouInfo;
        static create(is: TafStream.JceInputStream): FZDPanKouInfo;
    }

    namespace FZDPanKouInfo {
        interface Object {
            iMarket?: number;
            strCode?: string;
            strStockZTReason?: string;
            dCurFDAmount?: number;
            dFDRatio?: number;
            dHighFDAmout?: number;
            dZTTradeAmout?: number;
        }
    }

    class FZDPanKouInfoRsq {
        vecFZDPanKouInfo: TafStream.List<FuPan.FZDPanKouInfo>;

        toObject(): FZDPanKouInfoRsq.Object;
        readFromObject(json: FZDPanKouInfoRsq.Object): FZDPanKouInfoRsq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZDPanKouInfoRsq;
        static create(is: TafStream.JceInputStream): FZDPanKouInfoRsq;
    }

    namespace FZDPanKouInfoRsq {
        interface Object {
            vecFZDPanKouInfo?: Array<FuPan.FZDPanKouInfo.Object>;
        }
    }

    class FBatchUnitedStockPoolReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecType: TafStream.List<_TAF_MODULE_F_.FuPan.E_UNITED_STK_POOL_TYPE>;
        lRefreshTime: number;
        iDate: number;

        toObject(): FBatchUnitedStockPoolReq.Object;
        readFromObject(json: FBatchUnitedStockPoolReq.Object): FBatchUnitedStockPoolReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBatchUnitedStockPoolReq;
        static create(is: TafStream.JceInputStream): FBatchUnitedStockPoolReq;
    }

    namespace FBatchUnitedStockPoolReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecType?: Array<_TAF_MODULE_F_.FuPan.E_UNITED_STK_POOL_TYPE>;
            lRefreshTime?: number;
            iDate?: number;
        }
    }

    class FUnitedPoolStock {
        eType: _TAF_MODULE_F_.FuPan.E_UNITED_STK_POOL_TYPE;
        vecStk: TafStream.List<_TAF_MODULE_B_.FuPan.StockInfo>;

        toObject(): FUnitedPoolStock.Object;
        readFromObject(json: FUnitedPoolStock.Object): FUnitedPoolStock;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FUnitedPoolStock;
        static create(is: TafStream.JceInputStream): FUnitedPoolStock;
    }

    namespace FUnitedPoolStock {
        interface Object {
            eType?: _TAF_MODULE_F_.FuPan.E_UNITED_STK_POOL_TYPE;
            vecStk?: Array<_TAF_MODULE_B_.FuPan.StockInfo.Object>;
        }
    }

    class FBatchUnitedStockPoolRsq {
        vecStkPool: TafStream.List<FuPan.FUnitedPoolStock>;
        lRefreshTime: number;
        iDate: number;

        toObject(): FBatchUnitedStockPoolRsq.Object;
        readFromObject(json: FBatchUnitedStockPoolRsq.Object): FBatchUnitedStockPoolRsq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FBatchUnitedStockPoolRsq;
        static create(is: TafStream.JceInputStream): FBatchUnitedStockPoolRsq;
    }

    namespace FBatchUnitedStockPoolRsq {
        interface Object {
            vecStkPool?: Array<FuPan.FUnitedPoolStock.Object>;
            lRefreshTime?: number;
            iDate?: number;
        }
    }

    class FZTTagReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        vecTagType: TafStream.List<_TAF_MODULE_F_.FuPan.E_ZT_TAG_TYPE>;
        eDataType: _TAF_MODULE_F_.FuPan.E_TAG_DATA_TYPE;
        nStartDate: number;
        nEndDate: number;

        toObject(): FZTTagReq.Object;
        readFromObject(json: FZTTagReq.Object): FZTTagReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZTTagReq;
        static create(is: TafStream.JceInputStream): FZTTagReq;
    }

    namespace FZTTagReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            vecTagType?: Array<_TAF_MODULE_F_.FuPan.E_ZT_TAG_TYPE>;
            eDataType?: _TAF_MODULE_F_.FuPan.E_TAG_DATA_TYPE;
            nStartDate?: number;
            nEndDate?: number;
        }
    }

    class FZTTagRsp {
        vecTagData: TafStream.List<_TAF_MODULE_F_.FuPan.FStockZTTag>;

        toObject(): FZTTagRsp.Object;
        readFromObject(json: FZTTagRsp.Object): FZTTagRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZTTagRsp;
        static create(is: TafStream.JceInputStream): FZTTagRsp;
    }

    namespace FZTTagRsp {
        interface Object {
            vecTagData?: Array<_TAF_MODULE_F_.FuPan.FStockZTTag.Object>;
        }
    }

    class FZTAllTagTypeReq {
        stHeader: _TAF_MODULE_E_.HQSys.HeaderInfo;
        lRefreshTime: number;
        eTagType: _TAF_MODULE_F_.FuPan.E_TAG_DATA_TYPE;

        toObject(): FZTAllTagTypeReq.Object;
        readFromObject(json: FZTAllTagTypeReq.Object): FZTAllTagTypeReq;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZTAllTagTypeReq;
        static create(is: TafStream.JceInputStream): FZTAllTagTypeReq;
    }

    namespace FZTAllTagTypeReq {
        interface Object {
            stHeader?: _TAF_MODULE_E_.HQSys.HeaderInfo.Object;
            lRefreshTime?: number;
            eTagType?: _TAF_MODULE_F_.FuPan.E_TAG_DATA_TYPE;
        }
    }

    class FTagTypeInfo {
        eType: _TAF_MODULE_F_.FuPan.E_ZT_TAG_TYPE;
        strTypeName: string;

        toObject(): FTagTypeInfo.Object;
        readFromObject(json: FTagTypeInfo.Object): FTagTypeInfo;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FTagTypeInfo;
        static create(is: TafStream.JceInputStream): FTagTypeInfo;
    }

    namespace FTagTypeInfo {
        interface Object {
            eType?: _TAF_MODULE_F_.FuPan.E_ZT_TAG_TYPE;
            strTypeName?: string;
        }
    }

    class FZTAllTagTypeRsp {
        vecType: TafStream.List<FuPan.FTagTypeInfo>;
        lRefreshTime: number;

        toObject(): FZTAllTagTypeRsp.Object;
        readFromObject(json: FZTAllTagTypeRsp.Object): FZTAllTagTypeRsp;
        toBinBuffer(): TafStream.BinBuffer;
        static new(): FZTAllTagTypeRsp;
        static create(is: TafStream.JceInputStream): FZTAllTagTypeRsp;
    }

    namespace FZTAllTagTypeRsp {
        interface Object {
            vecType?: Array<FuPan.FTagTypeInfo.Object>;
            lRefreshTime?: number;
        }
    }

}


