// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 5.0.0 by TAF Team.
// Generated from `./Common.jce'
// **********************************************************************

var assert    = require('assert');
var TafStream = require('@taf/taf-stream');

if(TafStream.JceStruct == undefined){
TafStream.JceStruct = function() {
this._jce_double_precision_ = -1;
}
TafStream.JceStruct.prototype.setPrecision = function(d) {
if ((d == -1) || (d >= 0 && d <= 15)) {
this._jce_double_precision_ = d;
return true;
}
return false;
}
TafStream.JceStruct.prototype.resetPrecision = function() { this._jce_double_precision_ = -1;}
TafStream.JceStruct.prototype.hasSetPrecision = function() { return (this._jce_double_precision_ >= 0 && this._jce_double_precision_ <= 15);}
TafStream.JceStruct.prototype.getPrecision = function() { return this._jce_double_precision_; }
}



var HQSys = HQSys || {};
module.exports.HQSys = HQSys;

HQSys.PUSH_VERSION = 100;
HQSys.PUSH_CANCEL = 110;

HQSys.E_CLI_COMP_TYPE = {
    E_CLI_NO_COMP : 0,
    E_CLI_COMPRESS : 1,
    E_CLT_LZMA_COMPRESS : 2
};

HQSys.E_CLI_COMP_TYPE.etos = function(enm) {
    switch(enm){
        case 0 : return 'E_CLI_NO_COMP';
        case 1 : return 'E_CLI_COMPRESS';
        case 2 : return 'E_CLT_LZMA_COMPRESS';
    }
    return undefined;
};

HQSys.E_CLI_COMP_TYPE.stoe = function(enm) {
    switch(enm){
        case 'E_CLI_NO_COMP' : return 0;
        case 'E_CLI_COMPRESS' : return 1;
        case 'E_CLT_LZMA_COMPRESS' : return 2;
    }
    return undefined;
};

HQSys.E_CLI_COMP_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_CLI_COMP_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_HQ_PACKET_TYPE = {
    E_HQ_DIFF_PACKET : 100,
    E_HQ_LZ4_PACKET : 101,
    E_HQ_LZ4_DIFF : 102,
    E_HQ_LZMA_PACKET : 103,
    E_HQ_LZMA_DIFF : 104
};

HQSys.E_HQ_PACKET_TYPE.etos = function(enm) {
    switch(enm){
        case 100 : return 'E_HQ_DIFF_PACKET';
        case 101 : return 'E_HQ_LZ4_PACKET';
        case 102 : return 'E_HQ_LZ4_DIFF';
        case 103 : return 'E_HQ_LZMA_PACKET';
        case 104 : return 'E_HQ_LZMA_DIFF';
    }
    return undefined;
};

HQSys.E_HQ_PACKET_TYPE.stoe = function(enm) {
    switch(enm){
        case 'E_HQ_DIFF_PACKET' : return 100;
        case 'E_HQ_LZ4_PACKET' : return 101;
        case 'E_HQ_LZ4_DIFF' : return 102;
        case 'E_HQ_LZMA_PACKET' : return 103;
        case 'E_HQ_LZMA_DIFF' : return 104;
    }
    return undefined;
};

HQSys.E_HQ_PACKET_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_HQ_PACKET_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.HISTORY_DATA_TYPE = {
    HDT_DAY_KLINE : 0,
    HDT_MIN1_KLINE : 1,
    HDT_MIN5_KLINE : 2,
    HDT_MIN15_KLINE : 3,
    HDT_MIN30_KLINE : 4,
    HDT_MIN60_KLINE : 5,
    HDT_RTMIN : 6,
    HDT_WEEK_KLINE : 7,
    HDT_MONTH_KLINE : 8,
    HDT_SEASON_KLINE : 9,
    HDT_YEAR_KLINE : 10,
    HDT_DAY_MONEYFLOW : 11,
    HDT_TICK : 12,
    HDT_WEEK_MONEYFLOW : 13,
    HDT_MONTH_MONEYFLOW : 14,
    HDT_SEASON_MONEYFLOW : 15,
    HDT_YEAR_MONEYFLOW : 16,
    HDT_FLOW_MIN1 : 17,
    HDT_FLOW_MIN5 : 18,
    HDT_FLOW_MIN15 : 19,
    HDT_FLOW_MIN30 : 20,
    HDT_FLOW_MIN60 : 21,
    HDT_MIN120_KLINE : 22,
    HDT_FLOW_MIN120 : 23
};

HQSys.HISTORY_DATA_TYPE.etos = function(enm) {
    switch(enm){
        case 0 : return 'HDT_DAY_KLINE';
        case 1 : return 'HDT_MIN1_KLINE';
        case 2 : return 'HDT_MIN5_KLINE';
        case 3 : return 'HDT_MIN15_KLINE';
        case 4 : return 'HDT_MIN30_KLINE';
        case 5 : return 'HDT_MIN60_KLINE';
        case 6 : return 'HDT_RTMIN';
        case 7 : return 'HDT_WEEK_KLINE';
        case 8 : return 'HDT_MONTH_KLINE';
        case 9 : return 'HDT_SEASON_KLINE';
        case 10 : return 'HDT_YEAR_KLINE';
        case 11 : return 'HDT_DAY_MONEYFLOW';
        case 12 : return 'HDT_TICK';
        case 13 : return 'HDT_WEEK_MONEYFLOW';
        case 14 : return 'HDT_MONTH_MONEYFLOW';
        case 15 : return 'HDT_SEASON_MONEYFLOW';
        case 16 : return 'HDT_YEAR_MONEYFLOW';
        case 17 : return 'HDT_FLOW_MIN1';
        case 18 : return 'HDT_FLOW_MIN5';
        case 19 : return 'HDT_FLOW_MIN15';
        case 20 : return 'HDT_FLOW_MIN30';
        case 21 : return 'HDT_FLOW_MIN60';
        case 22 : return 'HDT_MIN120_KLINE';
        case 23 : return 'HDT_FLOW_MIN120';
    }
    return undefined;
};

HQSys.HISTORY_DATA_TYPE.stoe = function(enm) {
    switch(enm){
        case 'HDT_DAY_KLINE' : return 0;
        case 'HDT_MIN1_KLINE' : return 1;
        case 'HDT_MIN5_KLINE' : return 2;
        case 'HDT_MIN15_KLINE' : return 3;
        case 'HDT_MIN30_KLINE' : return 4;
        case 'HDT_MIN60_KLINE' : return 5;
        case 'HDT_RTMIN' : return 6;
        case 'HDT_WEEK_KLINE' : return 7;
        case 'HDT_MONTH_KLINE' : return 8;
        case 'HDT_SEASON_KLINE' : return 9;
        case 'HDT_YEAR_KLINE' : return 10;
        case 'HDT_DAY_MONEYFLOW' : return 11;
        case 'HDT_TICK' : return 12;
        case 'HDT_WEEK_MONEYFLOW' : return 13;
        case 'HDT_MONTH_MONEYFLOW' : return 14;
        case 'HDT_SEASON_MONEYFLOW' : return 15;
        case 'HDT_YEAR_MONEYFLOW' : return 16;
        case 'HDT_FLOW_MIN1' : return 17;
        case 'HDT_FLOW_MIN5' : return 18;
        case 'HDT_FLOW_MIN15' : return 19;
        case 'HDT_FLOW_MIN30' : return 20;
        case 'HDT_FLOW_MIN60' : return 21;
        case 'HDT_MIN120_KLINE' : return 22;
        case 'HDT_FLOW_MIN120' : return 23;
    }
    return undefined;
};

HQSys.HISTORY_DATA_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.HISTORY_DATA_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_QX_MODE = {
    EQM_QX_NONE : 0,
    EQM_QX_FRONT : 1,
    EQM_QX_BACK : 2
};

HQSys.E_QX_MODE.etos = function(enm) {
    switch(enm){
        case 0 : return 'EQM_QX_NONE';
        case 1 : return 'EQM_QX_FRONT';
        case 2 : return 'EQM_QX_BACK';
    }
    return undefined;
};

HQSys.E_QX_MODE.stoe = function(enm) {
    switch(enm){
        case 'EQM_QX_NONE' : return 0;
        case 'EQM_QX_FRONT' : return 1;
        case 'EQM_QX_BACK' : return 2;
    }
    return undefined;
};

HQSys.E_QX_MODE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_QX_MODE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_STOCK_TYPE_SUMMARAY = {
    ESTS_ALL : 0,
    ESTS_STOCK : 1,
    ESTS_BLOCK : 2,
    ESTS_ZHISHU : 3
};

HQSys.E_STOCK_TYPE_SUMMARAY.etos = function(enm) {
    switch(enm){
        case 0 : return 'ESTS_ALL';
        case 1 : return 'ESTS_STOCK';
        case 2 : return 'ESTS_BLOCK';
        case 3 : return 'ESTS_ZHISHU';
    }
    return undefined;
};

HQSys.E_STOCK_TYPE_SUMMARAY.stoe = function(enm) {
    switch(enm){
        case 'ESTS_ALL' : return 0;
        case 'ESTS_STOCK' : return 1;
        case 'ESTS_BLOCK' : return 2;
        case 'ESTS_ZHISHU' : return 3;
    }
    return undefined;
};

HQSys.E_STOCK_TYPE_SUMMARAY._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_STOCK_TYPE_SUMMARAY._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_BLOCK_TYPE = {
    EBT_BK_ALL : 0,
    EBT_BK_HY : 22,
    EBT_BK_DQ : 23,
    EBT_BK_GN : 24
};

HQSys.E_BLOCK_TYPE.etos = function(enm) {
    switch(enm){
        case 0 : return 'EBT_BK_ALL';
        case 22 : return 'EBT_BK_HY';
        case 23 : return 'EBT_BK_DQ';
        case 24 : return 'EBT_BK_GN';
    }
    return undefined;
};

HQSys.E_BLOCK_TYPE.stoe = function(enm) {
    switch(enm){
        case 'EBT_BK_ALL' : return 0;
        case 'EBT_BK_HY' : return 22;
        case 'EBT_BK_DQ' : return 23;
        case 'EBT_BK_GN' : return 24;
    }
    return undefined;
};

HQSys.E_BLOCK_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_BLOCK_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_STOCK_CATEGORY = {
    STKC_SH_ZS : 1,
    STKC_SH_AG : 2,
    STKC_SH_BG : 3,
    STKC_SH_ZQ : 4,
    STKC_SZ_ZS : 5,
    STKC_SZ_AG : 6,
    STKC_SZ_BG : 7,
    STKC_SZ_ZQ : 8,
    STKC_SH_JJ : 9,
    STKC_SZ_JJ : 10,
    STKC_SH_QZ : 11,
    STKC_SZ_QZ : 12,
    STKC_SZ_SM : 13,
    STKC_NO_LO : 14,
    STKC_SH_ZS_IM9 : 15,
    STKC_SH_ZS_IM6 : 16,
    STKC_SZ_ALL_AG : 17,
    STKC_AH : 20,
    STKC_SH_TS : 18,
    STKC_SH_FX : 19,
    STKC_SZ_TS : 21,
    STKC_BK_HY : 22,
    STKC_BK_DQ : 23,
    STKC_BK_GN : 24,
    STKC_QH : 31,
    STKC_FOREX : 32,
    STKC_GWQH : 33,
    STKC_ALL_AG : 40,
    STKC_ALL_QZ : 41,
    STKC_ALL_ZQ : 42,
    STKC_SZ_CY : 80,
    STKC_SZ_SB : 81,
    STKC_UNKNOWN : 99,
    STKC_HK : 101,
    STKC_QH_ZSQQ : 165,
    STKC_QH_ZSQQ_C : 166,
    STKC_QH_ZSQQ_P : 167,
    STKC_QH_GZQH : 168,
    STKC_QH_TBQH : 169,
    STKC_QH_ALL : 170,
    STKC_SH_ISP : 171,
    STKC_SH_OPTION : 172,
    STKC_SH_OPTION_C : 173,
    STKC_SH_OPTION_P : 174,
    STKC_M_OTHER : 200,
    STKC_M_FOREX : 201,
    STKC_M_FUTURES : 202,
    STKC_M_METAL : 203,
    STKC_M_INDEX : 204,
    STKC_M_FUND : 205,
    STKC_M_HK : 206,
    STKC_M_US : 207,
    STKC_M_XSB : 208,
    STKC_M_COIN : 209
};

HQSys.E_STOCK_CATEGORY.etos = function(enm) {
    switch(enm){
        case 1 : return 'STKC_SH_ZS';
        case 2 : return 'STKC_SH_AG';
        case 3 : return 'STKC_SH_BG';
        case 4 : return 'STKC_SH_ZQ';
        case 5 : return 'STKC_SZ_ZS';
        case 6 : return 'STKC_SZ_AG';
        case 7 : return 'STKC_SZ_BG';
        case 8 : return 'STKC_SZ_ZQ';
        case 9 : return 'STKC_SH_JJ';
        case 10 : return 'STKC_SZ_JJ';
        case 11 : return 'STKC_SH_QZ';
        case 12 : return 'STKC_SZ_QZ';
        case 13 : return 'STKC_SZ_SM';
        case 14 : return 'STKC_NO_LO';
        case 15 : return 'STKC_SH_ZS_IM9';
        case 16 : return 'STKC_SH_ZS_IM6';
        case 17 : return 'STKC_SZ_ALL_AG';
        case 18 : return 'STKC_SH_TS';
        case 19 : return 'STKC_SH_FX';
        case 20 : return 'STKC_AH';
        case 21 : return 'STKC_SZ_TS';
        case 22 : return 'STKC_BK_HY';
        case 23 : return 'STKC_BK_DQ';
        case 24 : return 'STKC_BK_GN';
        case 31 : return 'STKC_QH';
        case 32 : return 'STKC_FOREX';
        case 33 : return 'STKC_GWQH';
        case 40 : return 'STKC_ALL_AG';
        case 41 : return 'STKC_ALL_QZ';
        case 42 : return 'STKC_ALL_ZQ';
        case 80 : return 'STKC_SZ_CY';
        case 81 : return 'STKC_SZ_SB';
        case 99 : return 'STKC_UNKNOWN';
        case 101 : return 'STKC_HK';
        case 165 : return 'STKC_QH_ZSQQ';
        case 166 : return 'STKC_QH_ZSQQ_C';
        case 167 : return 'STKC_QH_ZSQQ_P';
        case 168 : return 'STKC_QH_GZQH';
        case 169 : return 'STKC_QH_TBQH';
        case 170 : return 'STKC_QH_ALL';
        case 171 : return 'STKC_SH_ISP';
        case 172 : return 'STKC_SH_OPTION';
        case 173 : return 'STKC_SH_OPTION_C';
        case 174 : return 'STKC_SH_OPTION_P';
        case 200 : return 'STKC_M_OTHER';
        case 201 : return 'STKC_M_FOREX';
        case 202 : return 'STKC_M_FUTURES';
        case 203 : return 'STKC_M_METAL';
        case 204 : return 'STKC_M_INDEX';
        case 205 : return 'STKC_M_FUND';
        case 206 : return 'STKC_M_HK';
        case 207 : return 'STKC_M_US';
        case 208 : return 'STKC_M_XSB';
        case 209 : return 'STKC_M_COIN';
    }
    return undefined;
};

HQSys.E_STOCK_CATEGORY.stoe = function(enm) {
    switch(enm){
        case 'STKC_SH_ZS' : return 1;
        case 'STKC_SH_AG' : return 2;
        case 'STKC_SH_BG' : return 3;
        case 'STKC_SH_ZQ' : return 4;
        case 'STKC_SZ_ZS' : return 5;
        case 'STKC_SZ_AG' : return 6;
        case 'STKC_SZ_BG' : return 7;
        case 'STKC_SZ_ZQ' : return 8;
        case 'STKC_SH_JJ' : return 9;
        case 'STKC_SZ_JJ' : return 10;
        case 'STKC_SH_QZ' : return 11;
        case 'STKC_SZ_QZ' : return 12;
        case 'STKC_SZ_SM' : return 13;
        case 'STKC_NO_LO' : return 14;
        case 'STKC_SH_ZS_IM9' : return 15;
        case 'STKC_SH_ZS_IM6' : return 16;
        case 'STKC_SZ_ALL_AG' : return 17;
        case 'STKC_SH_TS' : return 18;
        case 'STKC_SH_FX' : return 19;
        case 'STKC_AH' : return 20;
        case 'STKC_SZ_TS' : return 21;
        case 'STKC_BK_HY' : return 22;
        case 'STKC_BK_DQ' : return 23;
        case 'STKC_BK_GN' : return 24;
        case 'STKC_QH' : return 31;
        case 'STKC_FOREX' : return 32;
        case 'STKC_GWQH' : return 33;
        case 'STKC_ALL_AG' : return 40;
        case 'STKC_ALL_QZ' : return 41;
        case 'STKC_ALL_ZQ' : return 42;
        case 'STKC_SZ_CY' : return 80;
        case 'STKC_SZ_SB' : return 81;
        case 'STKC_UNKNOWN' : return 99;
        case 'STKC_HK' : return 101;
        case 'STKC_QH_ZSQQ' : return 165;
        case 'STKC_QH_ZSQQ_C' : return 166;
        case 'STKC_QH_ZSQQ_P' : return 167;
        case 'STKC_QH_GZQH' : return 168;
        case 'STKC_QH_TBQH' : return 169;
        case 'STKC_QH_ALL' : return 170;
        case 'STKC_SH_ISP' : return 171;
        case 'STKC_SH_OPTION' : return 172;
        case 'STKC_SH_OPTION_C' : return 173;
        case 'STKC_SH_OPTION_P' : return 174;
        case 'STKC_M_OTHER' : return 200;
        case 'STKC_M_FOREX' : return 201;
        case 'STKC_M_FUTURES' : return 202;
        case 'STKC_M_METAL' : return 203;
        case 'STKC_M_INDEX' : return 204;
        case 'STKC_M_FUND' : return 205;
        case 'STKC_M_HK' : return 206;
        case 'STKC_M_US' : return 207;
        case 'STKC_M_XSB' : return 208;
        case 'STKC_M_COIN' : return 209;
    }
    return undefined;
};

HQSys.E_STOCK_CATEGORY._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_STOCK_CATEGORY._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_MARKET_CODE = {
    E_MARKET_SZ : 0,
    E_MARKET_SH : 1,
    E_MARKET_HK : 2,
    E_MARKET_SF : 3,
    E_MARKET_SC : 4,
    E_MARKET_DC : 5,
    E_MARKET_ZC : 6,
    E_MARKET_BH : 7,
    E_MARKET_SJ : 8,
    E_MARKET_LDJ : 9,
    E_MARKET_TJ : 10,
    E_MARKET_DY : 11,
    E_MARKET_GJ : 12,
    E_MARKET_NASDAQ : 13,
    E_MARKET_NYSE : 14,
    E_MARKET_AMEX : 15,
    E_MARKET_HSI : 16,
    E_MARKET_USI : 17,
    E_MARKET_NK225 : 18,
    E_MARKET_KOSPI : 19,
    E_MARKET_TWII : 20,
    E_MARKET_STI : 21,
    E_MARKET_KLSE : 22,
    E_MARKET_SETI : 23,
    E_MARKET_JKSE : 24,
    E_MARKET_AORD : 25,
    E_MARKET_NZSE : 26,
    E_MARKET_SENSEX : 27,
    E_MARKET_GSPTSE : 28,
    E_MARKET_USD : 29,
    E_MARKET_CAC : 30,
    E_MARKET_DAX : 31,
    E_MARKET_AEX : 32,
    E_MARKET_OMX20 : 33,
    E_MARKET_BFX : 34,
    E_MARKET_SSMI : 35,
    E_MARKET_IBOVESPA : 36,
    E_MARKET_RTS : 37,
    E_MARKET_MIB : 38,
    E_MARKET_FX : 39,
    E_MARKET_FTSE : 40,
    E_MARKET_COMEX : 41,
    E_MARKET_LME : 42,
    E_MARKET_NYMEX : 43,
    E_MARKET_CBOT : 44,
    E_MARKET_IPE : 45,
    E_MARKET_FUND : 46,
    E_MARKET_TB : 47,
    E_MARKET_CNY : 48,
    E_MARKET_XS : 49,
    E_MARKET_DELAY_HK : 50,
    E_MARKET_BS : 51,
    E_MARKET_HT : 52,
    E_MARKET_WT : 53,
    E_MARKET_SC1 : 90,
    E_MARKET_SC2 : 91,
    E_MARKET_SC3 : 92,
    E_MARKET_SC4 : 93,
    E_MARKET_DC1 : 94,
    E_MARKET_DC2 : 95,
    E_MARKET_ZC1 : 96,
    E_MARKET_ZC2 : 97
};

HQSys.E_MARKET_CODE.etos = function(enm) {
    switch(enm){
        case 0 : return 'E_MARKET_SZ';
        case 1 : return 'E_MARKET_SH';
        case 2 : return 'E_MARKET_HK';
        case 3 : return 'E_MARKET_SF';
        case 4 : return 'E_MARKET_SC';
        case 5 : return 'E_MARKET_DC';
        case 6 : return 'E_MARKET_ZC';
        case 7 : return 'E_MARKET_BH';
        case 8 : return 'E_MARKET_SJ';
        case 9 : return 'E_MARKET_LDJ';
        case 10 : return 'E_MARKET_TJ';
        case 11 : return 'E_MARKET_DY';
        case 12 : return 'E_MARKET_GJ';
        case 13 : return 'E_MARKET_NASDAQ';
        case 14 : return 'E_MARKET_NYSE';
        case 15 : return 'E_MARKET_AMEX';
        case 16 : return 'E_MARKET_HSI';
        case 17 : return 'E_MARKET_USI';
        case 18 : return 'E_MARKET_NK225';
        case 19 : return 'E_MARKET_KOSPI';
        case 20 : return 'E_MARKET_TWII';
        case 21 : return 'E_MARKET_STI';
        case 22 : return 'E_MARKET_KLSE';
        case 23 : return 'E_MARKET_SETI';
        case 24 : return 'E_MARKET_JKSE';
        case 25 : return 'E_MARKET_AORD';
        case 26 : return 'E_MARKET_NZSE';
        case 27 : return 'E_MARKET_SENSEX';
        case 28 : return 'E_MARKET_GSPTSE';
        case 29 : return 'E_MARKET_USD';
        case 30 : return 'E_MARKET_CAC';
        case 31 : return 'E_MARKET_DAX';
        case 32 : return 'E_MARKET_AEX';
        case 33 : return 'E_MARKET_OMX20';
        case 34 : return 'E_MARKET_BFX';
        case 35 : return 'E_MARKET_SSMI';
        case 36 : return 'E_MARKET_IBOVESPA';
        case 37 : return 'E_MARKET_RTS';
        case 38 : return 'E_MARKET_MIB';
        case 39 : return 'E_MARKET_FX';
        case 40 : return 'E_MARKET_FTSE';
        case 41 : return 'E_MARKET_COMEX';
        case 42 : return 'E_MARKET_LME';
        case 43 : return 'E_MARKET_NYMEX';
        case 44 : return 'E_MARKET_CBOT';
        case 45 : return 'E_MARKET_IPE';
        case 46 : return 'E_MARKET_FUND';
        case 47 : return 'E_MARKET_TB';
        case 48 : return 'E_MARKET_CNY';
        case 49 : return 'E_MARKET_XS';
        case 50 : return 'E_MARKET_DELAY_HK';
        case 51 : return 'E_MARKET_BS';
        case 52 : return 'E_MARKET_HT';
        case 53 : return 'E_MARKET_WT';
        case 90 : return 'E_MARKET_SC1';
        case 91 : return 'E_MARKET_SC2';
        case 92 : return 'E_MARKET_SC3';
        case 93 : return 'E_MARKET_SC4';
        case 94 : return 'E_MARKET_DC1';
        case 95 : return 'E_MARKET_DC2';
        case 96 : return 'E_MARKET_ZC1';
        case 97 : return 'E_MARKET_ZC2';
    }
    return undefined;
};

HQSys.E_MARKET_CODE.stoe = function(enm) {
    switch(enm){
        case 'E_MARKET_SZ' : return 0;
        case 'E_MARKET_SH' : return 1;
        case 'E_MARKET_HK' : return 2;
        case 'E_MARKET_SF' : return 3;
        case 'E_MARKET_SC' : return 4;
        case 'E_MARKET_DC' : return 5;
        case 'E_MARKET_ZC' : return 6;
        case 'E_MARKET_BH' : return 7;
        case 'E_MARKET_SJ' : return 8;
        case 'E_MARKET_LDJ' : return 9;
        case 'E_MARKET_TJ' : return 10;
        case 'E_MARKET_DY' : return 11;
        case 'E_MARKET_GJ' : return 12;
        case 'E_MARKET_NASDAQ' : return 13;
        case 'E_MARKET_NYSE' : return 14;
        case 'E_MARKET_AMEX' : return 15;
        case 'E_MARKET_HSI' : return 16;
        case 'E_MARKET_USI' : return 17;
        case 'E_MARKET_NK225' : return 18;
        case 'E_MARKET_KOSPI' : return 19;
        case 'E_MARKET_TWII' : return 20;
        case 'E_MARKET_STI' : return 21;
        case 'E_MARKET_KLSE' : return 22;
        case 'E_MARKET_SETI' : return 23;
        case 'E_MARKET_JKSE' : return 24;
        case 'E_MARKET_AORD' : return 25;
        case 'E_MARKET_NZSE' : return 26;
        case 'E_MARKET_SENSEX' : return 27;
        case 'E_MARKET_GSPTSE' : return 28;
        case 'E_MARKET_USD' : return 29;
        case 'E_MARKET_CAC' : return 30;
        case 'E_MARKET_DAX' : return 31;
        case 'E_MARKET_AEX' : return 32;
        case 'E_MARKET_OMX20' : return 33;
        case 'E_MARKET_BFX' : return 34;
        case 'E_MARKET_SSMI' : return 35;
        case 'E_MARKET_IBOVESPA' : return 36;
        case 'E_MARKET_RTS' : return 37;
        case 'E_MARKET_MIB' : return 38;
        case 'E_MARKET_FX' : return 39;
        case 'E_MARKET_FTSE' : return 40;
        case 'E_MARKET_COMEX' : return 41;
        case 'E_MARKET_LME' : return 42;
        case 'E_MARKET_NYMEX' : return 43;
        case 'E_MARKET_CBOT' : return 44;
        case 'E_MARKET_IPE' : return 45;
        case 'E_MARKET_FUND' : return 46;
        case 'E_MARKET_TB' : return 47;
        case 'E_MARKET_CNY' : return 48;
        case 'E_MARKET_XS' : return 49;
        case 'E_MARKET_DELAY_HK' : return 50;
        case 'E_MARKET_BS' : return 51;
        case 'E_MARKET_HT' : return 52;
        case 'E_MARKET_WT' : return 53;
        case 'E_MARKET_SC1' : return 90;
        case 'E_MARKET_SC2' : return 91;
        case 'E_MARKET_SC3' : return 92;
        case 'E_MARKET_SC4' : return 93;
        case 'E_MARKET_DC1' : return 94;
        case 'E_MARKET_DC2' : return 95;
        case 'E_MARKET_ZC1' : return 96;
        case 'E_MARKET_ZC2' : return 97;
    }
    return undefined;
};

HQSys.E_MARKET_CODE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_MARKET_CODE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_SC_CATEGORY = {
    E_SC_AU : 1,
    E_SC_AG : 2,
    E_SC_AL : 3,
    E_SC_BU : 4,
    E_SC_CU : 5,
    E_SC_FU : 6,
    E_SC_HC : 7,
    E_SC_PB : 8,
    E_SC_RB : 9,
    E_SC_RU : 10,
    E_SC_WR : 11,
    E_SC_ZN : 12,
    E_SC_NI : 13,
    E_SC_SN : 14
};

HQSys.E_SC_CATEGORY.etos = function(enm) {
    switch(enm){
        case 1 : return 'E_SC_AU';
        case 2 : return 'E_SC_AG';
        case 3 : return 'E_SC_AL';
        case 4 : return 'E_SC_BU';
        case 5 : return 'E_SC_CU';
        case 6 : return 'E_SC_FU';
        case 7 : return 'E_SC_HC';
        case 8 : return 'E_SC_PB';
        case 9 : return 'E_SC_RB';
        case 10 : return 'E_SC_RU';
        case 11 : return 'E_SC_WR';
        case 12 : return 'E_SC_ZN';
        case 13 : return 'E_SC_NI';
        case 14 : return 'E_SC_SN';
    }
    return undefined;
};

HQSys.E_SC_CATEGORY.stoe = function(enm) {
    switch(enm){
        case 'E_SC_AU' : return 1;
        case 'E_SC_AG' : return 2;
        case 'E_SC_AL' : return 3;
        case 'E_SC_BU' : return 4;
        case 'E_SC_CU' : return 5;
        case 'E_SC_FU' : return 6;
        case 'E_SC_HC' : return 7;
        case 'E_SC_PB' : return 8;
        case 'E_SC_RB' : return 9;
        case 'E_SC_RU' : return 10;
        case 'E_SC_WR' : return 11;
        case 'E_SC_ZN' : return 12;
        case 'E_SC_NI' : return 13;
        case 'E_SC_SN' : return 14;
    }
    return undefined;
};

HQSys.E_SC_CATEGORY._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_SC_CATEGORY._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_DC_CATEGORY = {
    E_DC_BB : 1,
    E_DC_FB : 2,
    E_DC_A : 3,
    E_DC_B : 4,
    E_DC_C : 5,
    E_DC_I : 6,
    E_DC_JD : 7,
    E_DC_JM : 8,
    E_DC_L : 9,
    E_DC_M : 10,
    E_DC_P : 11,
    E_DC_PP : 12,
    E_DC_V : 13,
    E_DC_Y : 14,
    E_DC_J : 17,
    E_DC_CS : 18
};

HQSys.E_DC_CATEGORY.etos = function(enm) {
    switch(enm){
        case 1 : return 'E_DC_BB';
        case 2 : return 'E_DC_FB';
        case 3 : return 'E_DC_A';
        case 4 : return 'E_DC_B';
        case 5 : return 'E_DC_C';
        case 6 : return 'E_DC_I';
        case 7 : return 'E_DC_JD';
        case 8 : return 'E_DC_JM';
        case 9 : return 'E_DC_L';
        case 10 : return 'E_DC_M';
        case 11 : return 'E_DC_P';
        case 12 : return 'E_DC_PP';
        case 13 : return 'E_DC_V';
        case 14 : return 'E_DC_Y';
        case 17 : return 'E_DC_J';
        case 18 : return 'E_DC_CS';
    }
    return undefined;
};

HQSys.E_DC_CATEGORY.stoe = function(enm) {
    switch(enm){
        case 'E_DC_BB' : return 1;
        case 'E_DC_FB' : return 2;
        case 'E_DC_A' : return 3;
        case 'E_DC_B' : return 4;
        case 'E_DC_C' : return 5;
        case 'E_DC_I' : return 6;
        case 'E_DC_JD' : return 7;
        case 'E_DC_JM' : return 8;
        case 'E_DC_L' : return 9;
        case 'E_DC_M' : return 10;
        case 'E_DC_P' : return 11;
        case 'E_DC_PP' : return 12;
        case 'E_DC_V' : return 13;
        case 'E_DC_Y' : return 14;
        case 'E_DC_J' : return 17;
        case 'E_DC_CS' : return 18;
    }
    return undefined;
};

HQSys.E_DC_CATEGORY._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_DC_CATEGORY._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_ZC_CATEGORY = {
    E_ZC_CF : 2,
    E_ZC_FG : 3,
    E_ZC_JR : 4,
    E_ZC_LR : 5,
    E_ZC_MA : 6,
    E_ZC_OI : 8,
    E_ZC_PM : 9,
    E_ZC_RI : 10,
    E_ZC_RM : 11,
    E_ZC_RS : 12,
    E_ZC_SM : 14,
    E_ZC_SF : 13,
    E_ZC_SR : 15,
    E_ZC_TA : 16,
    E_ZC_TC : 17,
    E_ZC_WH : 18,
    E_ZC_ZC : 19,
    E_ZC_CY : 20,
    E_ZC_AP : 21
};

HQSys.E_ZC_CATEGORY.etos = function(enm) {
    switch(enm){
        case 2 : return 'E_ZC_CF';
        case 3 : return 'E_ZC_FG';
        case 4 : return 'E_ZC_JR';
        case 5 : return 'E_ZC_LR';
        case 6 : return 'E_ZC_MA';
        case 8 : return 'E_ZC_OI';
        case 9 : return 'E_ZC_PM';
        case 10 : return 'E_ZC_RI';
        case 11 : return 'E_ZC_RM';
        case 12 : return 'E_ZC_RS';
        case 13 : return 'E_ZC_SF';
        case 14 : return 'E_ZC_SM';
        case 15 : return 'E_ZC_SR';
        case 16 : return 'E_ZC_TA';
        case 17 : return 'E_ZC_TC';
        case 18 : return 'E_ZC_WH';
        case 19 : return 'E_ZC_ZC';
        case 20 : return 'E_ZC_CY';
        case 21 : return 'E_ZC_AP';
    }
    return undefined;
};

HQSys.E_ZC_CATEGORY.stoe = function(enm) {
    switch(enm){
        case 'E_ZC_CF' : return 2;
        case 'E_ZC_FG' : return 3;
        case 'E_ZC_JR' : return 4;
        case 'E_ZC_LR' : return 5;
        case 'E_ZC_MA' : return 6;
        case 'E_ZC_OI' : return 8;
        case 'E_ZC_PM' : return 9;
        case 'E_ZC_RI' : return 10;
        case 'E_ZC_RM' : return 11;
        case 'E_ZC_RS' : return 12;
        case 'E_ZC_SF' : return 13;
        case 'E_ZC_SM' : return 14;
        case 'E_ZC_SR' : return 15;
        case 'E_ZC_TA' : return 16;
        case 'E_ZC_TC' : return 17;
        case 'E_ZC_WH' : return 18;
        case 'E_ZC_ZC' : return 19;
        case 'E_ZC_CY' : return 20;
        case 'E_ZC_AP' : return 21;
    }
    return undefined;
};

HQSys.E_ZC_CATEGORY._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_ZC_CATEGORY._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_HK_CATEGORY = {
    E_HK_ZQ : 66,
    E_HK_NXZ : 67,
    E_HK_JJ : 70,
    E_HK_CYB : 71,
    E_HK_ZB : 77,
    E_HK_QZ : 87
};

HQSys.E_HK_CATEGORY.etos = function(enm) {
    switch(enm){
        case 66 : return 'E_HK_ZQ';
        case 67 : return 'E_HK_NXZ';
        case 70 : return 'E_HK_JJ';
        case 71 : return 'E_HK_CYB';
        case 77 : return 'E_HK_ZB';
        case 87 : return 'E_HK_QZ';
    }
    return undefined;
};

HQSys.E_HK_CATEGORY.stoe = function(enm) {
    switch(enm){
        case 'E_HK_ZQ' : return 66;
        case 'E_HK_NXZ' : return 67;
        case 'E_HK_JJ' : return 70;
        case 'E_HK_CYB' : return 71;
        case 'E_HK_ZB' : return 77;
        case 'E_HK_QZ' : return 87;
    }
    return undefined;
};

HQSys.E_HK_CATEGORY._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_HK_CATEGORY._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_TB_CATEGORY = {
    E_TB_LW : 1,
    E_TB_XYZR_A : 2,
    E_TB_ZSZR_A : 3,
    E_TB_XYZR_B : 4,
    E_TB_ZSZR_B : 5,
    E_TB_ZS : 6,
    E_TB_YZB : 7,
    E_TB_DSC : 8,
    E_TB_DGP : 9
};

HQSys.E_TB_CATEGORY.etos = function(enm) {
    switch(enm){
        case 1 : return 'E_TB_LW';
        case 2 : return 'E_TB_XYZR_A';
        case 3 : return 'E_TB_ZSZR_A';
        case 4 : return 'E_TB_XYZR_B';
        case 5 : return 'E_TB_ZSZR_B';
        case 6 : return 'E_TB_ZS';
        case 7 : return 'E_TB_YZB';
        case 8 : return 'E_TB_DSC';
        case 9 : return 'E_TB_DGP';
    }
    return undefined;
};

HQSys.E_TB_CATEGORY.stoe = function(enm) {
    switch(enm){
        case 'E_TB_LW' : return 1;
        case 'E_TB_XYZR_A' : return 2;
        case 'E_TB_ZSZR_A' : return 3;
        case 'E_TB_XYZR_B' : return 4;
        case 'E_TB_ZSZR_B' : return 5;
        case 'E_TB_ZS' : return 6;
        case 'E_TB_YZB' : return 7;
        case 'E_TB_DSC' : return 8;
        case 'E_TB_DGP' : return 9;
    }
    return undefined;
};

HQSys.E_TB_CATEGORY._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_TB_CATEGORY._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_BUSS_TYPE = {
    EBT_A : 6,
    EBT_B : 7,
    EBT_JJ : 9,
    EBT_SH_A : 0,
    EBT_SH_B : 1,
    EBT_SH_ZQ : 4,
    EBT_SZ_A : 2,
    EBT_SZ_B : 3,
    EBT_SZ_CY : 18,
    EBT_SZ_SM : 12,
    EBT_SZ_ZQ : 5,
    EBT_ZQ : 8,
    EBT_BLK_HY : 32,
    EBT_BLK_DY : 31,
    EBT_BLK_GN : 33,
    EBT_BLK_ALL : 30,
    EBT_ZS_BK : 11,
    EBT_QZ : 17,
    EBT_ZJ : 23,
    EBT_SH_JJ : 9100,
    EBT_SZ_JJ : 9101,
    EBT_ZS : 10422,
    EBT_SH_ZS : 10423,
    EBT_SZ_ZS : 10424,
    EBT_M_BH : 19,
    EBT_M_TG : 26,
    EBT_M_SHJ : 24,
    EBT_M_GJJ : 25,
    EBT_M_DS : 20,
    EBT_M_ZS : 21,
    EBT_M_SQ : 22,
    EBT_M_DY : 34,
    EBT_M_GJ : 35,
    EBT_M_HSI : 49,
    EBT_M_US : 50,
    EBT_M_NASDAQ : 51,
    EBT_M_NYSE : 52,
    EBT_M_AMEX : 53,
    EBT_M_USI : 54,
    EBT_M_XS : 10500,
    EBT_M_FUND : 10350,
    EBT_M_CBOT : 10400,
    EBT_M_COMEX : 10401,
    EBT_M_NYMEX : 10402,
    EBT_M_LME : 10403,
    EBT_M_FX : 10410,
    EBT_M_CNY : 10412,
    EBT_T_HK : 36,
    EBT_T_HK_ZB : 37,
    EBT_T_HK_CYB : 38,
    EBT_T_HK_ZQ : 39,
    EBT_T_HK_QZ : 41,
    EBT_T_HK_NXZ : 42,
    EBT_T_HK_JJ : 43,
    EBT_T_SC_CU : 10000,
    EBT_T_SC_AL : 10001,
    EBT_T_SC_ZN : 10002,
    EBT_T_SC_PB : 10003,
    EBT_T_SC_AU : 10004,
    EBT_T_SC_AG : 10005,
    EBT_T_SC_RB : 10006,
    EBT_T_SC_RU : 10007,
    EBT_T_SC_FU : 10008,
    EBT_T_SC_WR : 10009,
    EBT_T_SC_BU : 10010,
    EBT_T_SC_HC : 10011,
    EBT_T_SC_NI : 10012,
    EBT_T_SC_SN : 10013,
    EBT_T_DC_A : 10100,
    EBT_T_DC_M : 10101,
    EBT_T_DC_Y : 10102,
    EBT_T_DC_P : 10103,
    EBT_T_DC_C : 10104,
    EBT_T_DC_I : 10105,
    EBT_T_DC_JM : 10106,
    EBT_T_DC_J : 10107,
    EBT_T_DC_L : 10108,
    EBT_T_DC_V : 10109,
    EBT_T_DC_B : 10110,
    EBT_T_DC_JD : 10111,
    EBT_T_DC_FB : 10112,
    EBT_T_DC_BB : 10113,
    EBT_T_DC_PP : 10114,
    EBT_T_DC_CS : 10115,
    EBT_T_ZC_WH : 10200,
    EBT_T_ZC_OI : 10201,
    EBT_T_ZC_CF : 10202,
    EBT_T_ZC_SR : 10203,
    EBT_T_ZC_RI : 10204,
    EBT_T_ZC_TC : 10205,
    EBT_T_ZC_TA : 10206,
    EBT_T_ZC_FG : 10207,
    EBT_T_ZC_MA : 10208,
    EBT_T_ZC_RM : 10209,
    EBT_T_ZC_RS : 10210,
    EBT_T_ZC_PM : 10211,
    EBT_T_ZC_JR : 10212,
    EBT_T_ZC_LR : 10213,
    EBT_T_ZC_SM : 10214,
    EBT_T_ZC_SF : 10215,
    EBT_TB : 10438,
    EBT_TB_ZS : 10439,
    EBT_TB_ZSZR : 10440,
    EBT_TB_XYZR : 10441,
    EBT_TB_LW : 10442,
    EBT_TB_DSC : 10443,
    EBT_TB_DGP : 10444,
    EBT_TB_YZB : 10445,
    EBT_M_DS_SUB : 10550,
    EBT_M_ZS_SUB : 10551,
    EBT_M_SQ_SUB : 10552
};

HQSys.E_BUSS_TYPE.etos = function(enm) {
    switch(enm){
        case 0 : return 'EBT_SH_A';
        case 1 : return 'EBT_SH_B';
        case 2 : return 'EBT_SZ_A';
        case 3 : return 'EBT_SZ_B';
        case 4 : return 'EBT_SH_ZQ';
        case 5 : return 'EBT_SZ_ZQ';
        case 6 : return 'EBT_A';
        case 7 : return 'EBT_B';
        case 8 : return 'EBT_ZQ';
        case 9 : return 'EBT_JJ';
        case 11 : return 'EBT_ZS_BK';
        case 12 : return 'EBT_SZ_SM';
        case 17 : return 'EBT_QZ';
        case 18 : return 'EBT_SZ_CY';
        case 19 : return 'EBT_M_BH';
        case 20 : return 'EBT_M_DS';
        case 21 : return 'EBT_M_ZS';
        case 22 : return 'EBT_M_SQ';
        case 23 : return 'EBT_ZJ';
        case 24 : return 'EBT_M_SHJ';
        case 25 : return 'EBT_M_GJJ';
        case 26 : return 'EBT_M_TG';
        case 30 : return 'EBT_BLK_ALL';
        case 31 : return 'EBT_BLK_DY';
        case 32 : return 'EBT_BLK_HY';
        case 33 : return 'EBT_BLK_GN';
        case 34 : return 'EBT_M_DY';
        case 35 : return 'EBT_M_GJ';
        case 36 : return 'EBT_T_HK';
        case 37 : return 'EBT_T_HK_ZB';
        case 38 : return 'EBT_T_HK_CYB';
        case 39 : return 'EBT_T_HK_ZQ';
        case 41 : return 'EBT_T_HK_QZ';
        case 42 : return 'EBT_T_HK_NXZ';
        case 43 : return 'EBT_T_HK_JJ';
        case 49 : return 'EBT_M_HSI';
        case 50 : return 'EBT_M_US';
        case 51 : return 'EBT_M_NASDAQ';
        case 52 : return 'EBT_M_NYSE';
        case 53 : return 'EBT_M_AMEX';
        case 54 : return 'EBT_M_USI';
        case 9100 : return 'EBT_SH_JJ';
        case 9101 : return 'EBT_SZ_JJ';
        case 10000 : return 'EBT_T_SC_CU';
        case 10001 : return 'EBT_T_SC_AL';
        case 10002 : return 'EBT_T_SC_ZN';
        case 10003 : return 'EBT_T_SC_PB';
        case 10004 : return 'EBT_T_SC_AU';
        case 10005 : return 'EBT_T_SC_AG';
        case 10006 : return 'EBT_T_SC_RB';
        case 10007 : return 'EBT_T_SC_RU';
        case 10008 : return 'EBT_T_SC_FU';
        case 10009 : return 'EBT_T_SC_WR';
        case 10010 : return 'EBT_T_SC_BU';
        case 10011 : return 'EBT_T_SC_HC';
        case 10012 : return 'EBT_T_SC_NI';
        case 10013 : return 'EBT_T_SC_SN';
        case 10100 : return 'EBT_T_DC_A';
        case 10101 : return 'EBT_T_DC_M';
        case 10102 : return 'EBT_T_DC_Y';
        case 10103 : return 'EBT_T_DC_P';
        case 10104 : return 'EBT_T_DC_C';
        case 10105 : return 'EBT_T_DC_I';
        case 10106 : return 'EBT_T_DC_JM';
        case 10107 : return 'EBT_T_DC_J';
        case 10108 : return 'EBT_T_DC_L';
        case 10109 : return 'EBT_T_DC_V';
        case 10110 : return 'EBT_T_DC_B';
        case 10111 : return 'EBT_T_DC_JD';
        case 10112 : return 'EBT_T_DC_FB';
        case 10113 : return 'EBT_T_DC_BB';
        case 10114 : return 'EBT_T_DC_PP';
        case 10115 : return 'EBT_T_DC_CS';
        case 10200 : return 'EBT_T_ZC_WH';
        case 10201 : return 'EBT_T_ZC_OI';
        case 10202 : return 'EBT_T_ZC_CF';
        case 10203 : return 'EBT_T_ZC_SR';
        case 10204 : return 'EBT_T_ZC_RI';
        case 10205 : return 'EBT_T_ZC_TC';
        case 10206 : return 'EBT_T_ZC_TA';
        case 10207 : return 'EBT_T_ZC_FG';
        case 10208 : return 'EBT_T_ZC_MA';
        case 10209 : return 'EBT_T_ZC_RM';
        case 10210 : return 'EBT_T_ZC_RS';
        case 10211 : return 'EBT_T_ZC_PM';
        case 10212 : return 'EBT_T_ZC_JR';
        case 10213 : return 'EBT_T_ZC_LR';
        case 10214 : return 'EBT_T_ZC_SM';
        case 10215 : return 'EBT_T_ZC_SF';
        case 10350 : return 'EBT_M_FUND';
        case 10400 : return 'EBT_M_CBOT';
        case 10401 : return 'EBT_M_COMEX';
        case 10402 : return 'EBT_M_NYMEX';
        case 10403 : return 'EBT_M_LME';
        case 10410 : return 'EBT_M_FX';
        case 10412 : return 'EBT_M_CNY';
        case 10422 : return 'EBT_ZS';
        case 10423 : return 'EBT_SH_ZS';
        case 10424 : return 'EBT_SZ_ZS';
        case 10438 : return 'EBT_TB';
        case 10439 : return 'EBT_TB_ZS';
        case 10440 : return 'EBT_TB_ZSZR';
        case 10441 : return 'EBT_TB_XYZR';
        case 10442 : return 'EBT_TB_LW';
        case 10443 : return 'EBT_TB_DSC';
        case 10444 : return 'EBT_TB_DGP';
        case 10445 : return 'EBT_TB_YZB';
        case 10500 : return 'EBT_M_XS';
        case 10550 : return 'EBT_M_DS_SUB';
        case 10551 : return 'EBT_M_ZS_SUB';
        case 10552 : return 'EBT_M_SQ_SUB';
    }
    return undefined;
};

HQSys.E_BUSS_TYPE.stoe = function(enm) {
    switch(enm){
        case 'EBT_SH_A' : return 0;
        case 'EBT_SH_B' : return 1;
        case 'EBT_SZ_A' : return 2;
        case 'EBT_SZ_B' : return 3;
        case 'EBT_SH_ZQ' : return 4;
        case 'EBT_SZ_ZQ' : return 5;
        case 'EBT_A' : return 6;
        case 'EBT_B' : return 7;
        case 'EBT_ZQ' : return 8;
        case 'EBT_JJ' : return 9;
        case 'EBT_ZS_BK' : return 11;
        case 'EBT_SZ_SM' : return 12;
        case 'EBT_QZ' : return 17;
        case 'EBT_SZ_CY' : return 18;
        case 'EBT_M_BH' : return 19;
        case 'EBT_M_DS' : return 20;
        case 'EBT_M_ZS' : return 21;
        case 'EBT_M_SQ' : return 22;
        case 'EBT_ZJ' : return 23;
        case 'EBT_M_SHJ' : return 24;
        case 'EBT_M_GJJ' : return 25;
        case 'EBT_M_TG' : return 26;
        case 'EBT_BLK_ALL' : return 30;
        case 'EBT_BLK_DY' : return 31;
        case 'EBT_BLK_HY' : return 32;
        case 'EBT_BLK_GN' : return 33;
        case 'EBT_M_DY' : return 34;
        case 'EBT_M_GJ' : return 35;
        case 'EBT_T_HK' : return 36;
        case 'EBT_T_HK_ZB' : return 37;
        case 'EBT_T_HK_CYB' : return 38;
        case 'EBT_T_HK_ZQ' : return 39;
        case 'EBT_T_HK_QZ' : return 41;
        case 'EBT_T_HK_NXZ' : return 42;
        case 'EBT_T_HK_JJ' : return 43;
        case 'EBT_M_HSI' : return 49;
        case 'EBT_M_US' : return 50;
        case 'EBT_M_NASDAQ' : return 51;
        case 'EBT_M_NYSE' : return 52;
        case 'EBT_M_AMEX' : return 53;
        case 'EBT_M_USI' : return 54;
        case 'EBT_SH_JJ' : return 9100;
        case 'EBT_SZ_JJ' : return 9101;
        case 'EBT_T_SC_CU' : return 10000;
        case 'EBT_T_SC_AL' : return 10001;
        case 'EBT_T_SC_ZN' : return 10002;
        case 'EBT_T_SC_PB' : return 10003;
        case 'EBT_T_SC_AU' : return 10004;
        case 'EBT_T_SC_AG' : return 10005;
        case 'EBT_T_SC_RB' : return 10006;
        case 'EBT_T_SC_RU' : return 10007;
        case 'EBT_T_SC_FU' : return 10008;
        case 'EBT_T_SC_WR' : return 10009;
        case 'EBT_T_SC_BU' : return 10010;
        case 'EBT_T_SC_HC' : return 10011;
        case 'EBT_T_SC_NI' : return 10012;
        case 'EBT_T_SC_SN' : return 10013;
        case 'EBT_T_DC_A' : return 10100;
        case 'EBT_T_DC_M' : return 10101;
        case 'EBT_T_DC_Y' : return 10102;
        case 'EBT_T_DC_P' : return 10103;
        case 'EBT_T_DC_C' : return 10104;
        case 'EBT_T_DC_I' : return 10105;
        case 'EBT_T_DC_JM' : return 10106;
        case 'EBT_T_DC_J' : return 10107;
        case 'EBT_T_DC_L' : return 10108;
        case 'EBT_T_DC_V' : return 10109;
        case 'EBT_T_DC_B' : return 10110;
        case 'EBT_T_DC_JD' : return 10111;
        case 'EBT_T_DC_FB' : return 10112;
        case 'EBT_T_DC_BB' : return 10113;
        case 'EBT_T_DC_PP' : return 10114;
        case 'EBT_T_DC_CS' : return 10115;
        case 'EBT_T_ZC_WH' : return 10200;
        case 'EBT_T_ZC_OI' : return 10201;
        case 'EBT_T_ZC_CF' : return 10202;
        case 'EBT_T_ZC_SR' : return 10203;
        case 'EBT_T_ZC_RI' : return 10204;
        case 'EBT_T_ZC_TC' : return 10205;
        case 'EBT_T_ZC_TA' : return 10206;
        case 'EBT_T_ZC_FG' : return 10207;
        case 'EBT_T_ZC_MA' : return 10208;
        case 'EBT_T_ZC_RM' : return 10209;
        case 'EBT_T_ZC_RS' : return 10210;
        case 'EBT_T_ZC_PM' : return 10211;
        case 'EBT_T_ZC_JR' : return 10212;
        case 'EBT_T_ZC_LR' : return 10213;
        case 'EBT_T_ZC_SM' : return 10214;
        case 'EBT_T_ZC_SF' : return 10215;
        case 'EBT_M_FUND' : return 10350;
        case 'EBT_M_CBOT' : return 10400;
        case 'EBT_M_COMEX' : return 10401;
        case 'EBT_M_NYMEX' : return 10402;
        case 'EBT_M_LME' : return 10403;
        case 'EBT_M_FX' : return 10410;
        case 'EBT_M_CNY' : return 10412;
        case 'EBT_ZS' : return 10422;
        case 'EBT_SH_ZS' : return 10423;
        case 'EBT_SZ_ZS' : return 10424;
        case 'EBT_TB' : return 10438;
        case 'EBT_TB_ZS' : return 10439;
        case 'EBT_TB_ZSZR' : return 10440;
        case 'EBT_TB_XYZR' : return 10441;
        case 'EBT_TB_LW' : return 10442;
        case 'EBT_TB_DSC' : return 10443;
        case 'EBT_TB_DGP' : return 10444;
        case 'EBT_TB_YZB' : return 10445;
        case 'EBT_M_XS' : return 10500;
        case 'EBT_M_DS_SUB' : return 10550;
        case 'EBT_M_ZS_SUB' : return 10551;
        case 'EBT_M_SQ_SUB' : return 10552;
    }
    return undefined;
};

HQSys.E_BUSS_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_BUSS_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_SORT_METHOD = {
    E_SORT_DEFAULT : 0,
    E_SORT_ASCEND : 1,
    E_SORT_DESCEN : 2
};

HQSys.E_SORT_METHOD.etos = function(enm) {
    switch(enm){
        case 0 : return 'E_SORT_DEFAULT';
        case 1 : return 'E_SORT_ASCEND';
        case 2 : return 'E_SORT_DESCEN';
    }
    return undefined;
};

HQSys.E_SORT_METHOD.stoe = function(enm) {
    switch(enm){
        case 'E_SORT_DEFAULT' : return 0;
        case 'E_SORT_ASCEND' : return 1;
        case 'E_SORT_DESCEN' : return 2;
    }
    return undefined;
};

HQSys.E_SORT_METHOD._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_SORT_METHOD._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_MF_RANK_DAY = {
    EMR_DAY_1 : 1,
    EMR_DAY_3 : 3,
    EMR_DAY_5 : 5,
    EMR_DAY_10 : 10
};

HQSys.E_MF_RANK_DAY.etos = function(enm) {
    switch(enm){
        case 1 : return 'EMR_DAY_1';
        case 3 : return 'EMR_DAY_3';
        case 5 : return 'EMR_DAY_5';
        case 10 : return 'EMR_DAY_10';
    }
    return undefined;
};

HQSys.E_MF_RANK_DAY.stoe = function(enm) {
    switch(enm){
        case 'EMR_DAY_1' : return 1;
        case 'EMR_DAY_3' : return 3;
        case 'EMR_DAY_5' : return 5;
        case 'EMR_DAY_10' : return 10;
    }
    return undefined;
};

HQSys.E_MF_RANK_DAY._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_MF_RANK_DAY._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_MF_RANK_SORT_COLUMN = {
    EMRC_CODE : 1,
    EMRC_NAME : 2,
    EMRC_NOWPRICE : 3,
    EMRC_CHG : 4,
    EMRC_CHANGE : 5,
    EMRC_DAY_ZLLR : 6,
    EMRC_DAY_ZLZB : 7,
    EMRC_DAY_SHLR : 8,
    EMRC_DAY_SHZB : 9,
    EMRC_DAY_CDDZJLR : 10,
    EMRC_DAY_CDDZJZB : 11,
    EMRC_DAY_DDZJLR : 12,
    EMRC_DAY_DDZJZB : 13,
    EMRC_DAY_ZDZJLR : 14,
    EMRC_DAY_ZDZJZB : 15,
    EMRC_DAY_XDZJLR : 16,
    EMRC_DAY_XDZJZB : 17,
    EMRC_3DAY_ZLLR : 18,
    EMRC_3DAY_ZLZB : 19,
    EMRC_3DAY_SHLR : 20,
    EMRC_3DAY_SHZB : 21,
    EMRC_3DAY_CDDZJLR : 22,
    EMRC_3DAY_CDDZJZB : 23,
    EMRC_3DAY_DDZJLR : 24,
    EMRC_3DAY_DDZJZB : 25,
    EMRC_3DAY_ZDZJLR : 26,
    EMRC_3DAY_ZDZJZB : 27,
    EMRC_3DAY_XDZJLR : 28,
    EMRC_3DAY_XDZJZB : 29,
    EMRC_5DAY_ZLLR : 30,
    EMRC_5DAY_ZLZB : 31,
    EMRC_5DAY_SHLR : 32,
    EMRC_5DAY_SHZB : 33,
    EMRC_5DAY_CDDZJLR : 34,
    EMRC_5DAY_CDDZJZB : 35,
    EMRC_5DAY_DDZJLR : 36,
    EMRC_5DAY_DDZJZB : 37,
    EMRC_5DAY_ZDZJLR : 38,
    EMRC_5DAY_ZDZJZB : 39,
    EMRC_5DAY_XDZJLR : 40,
    EMRC_5DAY_XDZJZB : 41,
    EMRC_10DAY_ZLLR : 42,
    EMRC_10DAY_ZLZB : 43,
    EMRC_10DAY_SHLR : 44,
    EMRC_10DAY_SHZB : 45,
    EMRC_10DAY_CDDZJLR : 46,
    EMRC_10DAY_CDDZJZB : 47,
    EMRC_10DAY_DDZJLR : 48,
    EMRC_10DAY_DDZJZB : 49,
    EMRC_10DAY_ZDZJLR : 50,
    EMRC_10DAY_ZDZJZB : 51,
    EMRC_10DAY_XDZJLR : 52,
    EMRC_10DAY_XDZJZB : 53
};

HQSys.E_MF_RANK_SORT_COLUMN.etos = function(enm) {
    switch(enm){
        case 1 : return 'EMRC_CODE';
        case 2 : return 'EMRC_NAME';
        case 3 : return 'EMRC_NOWPRICE';
        case 4 : return 'EMRC_CHG';
        case 5 : return 'EMRC_CHANGE';
        case 6 : return 'EMRC_DAY_ZLLR';
        case 7 : return 'EMRC_DAY_ZLZB';
        case 8 : return 'EMRC_DAY_SHLR';
        case 9 : return 'EMRC_DAY_SHZB';
        case 10 : return 'EMRC_DAY_CDDZJLR';
        case 11 : return 'EMRC_DAY_CDDZJZB';
        case 12 : return 'EMRC_DAY_DDZJLR';
        case 13 : return 'EMRC_DAY_DDZJZB';
        case 14 : return 'EMRC_DAY_ZDZJLR';
        case 15 : return 'EMRC_DAY_ZDZJZB';
        case 16 : return 'EMRC_DAY_XDZJLR';
        case 17 : return 'EMRC_DAY_XDZJZB';
        case 18 : return 'EMRC_3DAY_ZLLR';
        case 19 : return 'EMRC_3DAY_ZLZB';
        case 20 : return 'EMRC_3DAY_SHLR';
        case 21 : return 'EMRC_3DAY_SHZB';
        case 22 : return 'EMRC_3DAY_CDDZJLR';
        case 23 : return 'EMRC_3DAY_CDDZJZB';
        case 24 : return 'EMRC_3DAY_DDZJLR';
        case 25 : return 'EMRC_3DAY_DDZJZB';
        case 26 : return 'EMRC_3DAY_ZDZJLR';
        case 27 : return 'EMRC_3DAY_ZDZJZB';
        case 28 : return 'EMRC_3DAY_XDZJLR';
        case 29 : return 'EMRC_3DAY_XDZJZB';
        case 30 : return 'EMRC_5DAY_ZLLR';
        case 31 : return 'EMRC_5DAY_ZLZB';
        case 32 : return 'EMRC_5DAY_SHLR';
        case 33 : return 'EMRC_5DAY_SHZB';
        case 34 : return 'EMRC_5DAY_CDDZJLR';
        case 35 : return 'EMRC_5DAY_CDDZJZB';
        case 36 : return 'EMRC_5DAY_DDZJLR';
        case 37 : return 'EMRC_5DAY_DDZJZB';
        case 38 : return 'EMRC_5DAY_ZDZJLR';
        case 39 : return 'EMRC_5DAY_ZDZJZB';
        case 40 : return 'EMRC_5DAY_XDZJLR';
        case 41 : return 'EMRC_5DAY_XDZJZB';
        case 42 : return 'EMRC_10DAY_ZLLR';
        case 43 : return 'EMRC_10DAY_ZLZB';
        case 44 : return 'EMRC_10DAY_SHLR';
        case 45 : return 'EMRC_10DAY_SHZB';
        case 46 : return 'EMRC_10DAY_CDDZJLR';
        case 47 : return 'EMRC_10DAY_CDDZJZB';
        case 48 : return 'EMRC_10DAY_DDZJLR';
        case 49 : return 'EMRC_10DAY_DDZJZB';
        case 50 : return 'EMRC_10DAY_ZDZJLR';
        case 51 : return 'EMRC_10DAY_ZDZJZB';
        case 52 : return 'EMRC_10DAY_XDZJLR';
        case 53 : return 'EMRC_10DAY_XDZJZB';
    }
    return undefined;
};

HQSys.E_MF_RANK_SORT_COLUMN.stoe = function(enm) {
    switch(enm){
        case 'EMRC_CODE' : return 1;
        case 'EMRC_NAME' : return 2;
        case 'EMRC_NOWPRICE' : return 3;
        case 'EMRC_CHG' : return 4;
        case 'EMRC_CHANGE' : return 5;
        case 'EMRC_DAY_ZLLR' : return 6;
        case 'EMRC_DAY_ZLZB' : return 7;
        case 'EMRC_DAY_SHLR' : return 8;
        case 'EMRC_DAY_SHZB' : return 9;
        case 'EMRC_DAY_CDDZJLR' : return 10;
        case 'EMRC_DAY_CDDZJZB' : return 11;
        case 'EMRC_DAY_DDZJLR' : return 12;
        case 'EMRC_DAY_DDZJZB' : return 13;
        case 'EMRC_DAY_ZDZJLR' : return 14;
        case 'EMRC_DAY_ZDZJZB' : return 15;
        case 'EMRC_DAY_XDZJLR' : return 16;
        case 'EMRC_DAY_XDZJZB' : return 17;
        case 'EMRC_3DAY_ZLLR' : return 18;
        case 'EMRC_3DAY_ZLZB' : return 19;
        case 'EMRC_3DAY_SHLR' : return 20;
        case 'EMRC_3DAY_SHZB' : return 21;
        case 'EMRC_3DAY_CDDZJLR' : return 22;
        case 'EMRC_3DAY_CDDZJZB' : return 23;
        case 'EMRC_3DAY_DDZJLR' : return 24;
        case 'EMRC_3DAY_DDZJZB' : return 25;
        case 'EMRC_3DAY_ZDZJLR' : return 26;
        case 'EMRC_3DAY_ZDZJZB' : return 27;
        case 'EMRC_3DAY_XDZJLR' : return 28;
        case 'EMRC_3DAY_XDZJZB' : return 29;
        case 'EMRC_5DAY_ZLLR' : return 30;
        case 'EMRC_5DAY_ZLZB' : return 31;
        case 'EMRC_5DAY_SHLR' : return 32;
        case 'EMRC_5DAY_SHZB' : return 33;
        case 'EMRC_5DAY_CDDZJLR' : return 34;
        case 'EMRC_5DAY_CDDZJZB' : return 35;
        case 'EMRC_5DAY_DDZJLR' : return 36;
        case 'EMRC_5DAY_DDZJZB' : return 37;
        case 'EMRC_5DAY_ZDZJLR' : return 38;
        case 'EMRC_5DAY_ZDZJZB' : return 39;
        case 'EMRC_5DAY_XDZJLR' : return 40;
        case 'EMRC_5DAY_XDZJZB' : return 41;
        case 'EMRC_10DAY_ZLLR' : return 42;
        case 'EMRC_10DAY_ZLZB' : return 43;
        case 'EMRC_10DAY_SHLR' : return 44;
        case 'EMRC_10DAY_SHZB' : return 45;
        case 'EMRC_10DAY_CDDZJLR' : return 46;
        case 'EMRC_10DAY_CDDZJZB' : return 47;
        case 'EMRC_10DAY_DDZJLR' : return 48;
        case 'EMRC_10DAY_DDZJZB' : return 49;
        case 'EMRC_10DAY_ZDZJLR' : return 50;
        case 'EMRC_10DAY_ZDZJZB' : return 51;
        case 'EMRC_10DAY_XDZJLR' : return 52;
        case 'EMRC_10DAY_XDZJZB' : return 53;
    }
    return undefined;
};

HQSys.E_MF_RANK_SORT_COLUMN._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_MF_RANK_SORT_COLUMN._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_DDERANK_SORT_COLUMN = {
    E_DDERANK_CODE : 1,
    E_DDERANK_NAME : 2,
    E_DDERANK_NOWPRICE : 3,
    E_DDERANK_CHG : 4,
    E_DDERANK_TURNOVERRATE : 5,
    E_DDERANK_DDX : 6,
    E_DDERANK_DDY : 7,
    E_DDERANK_DDZ : 8,
    E_DDERANK_DDF : 9,
    E_DDERANK_DDX5 : 10,
    E_DDERANK_DDY5 : 11,
    E_DDERANK_DDX60 : 12,
    E_DDERANK_DDY60 : 13
};

HQSys.E_DDERANK_SORT_COLUMN.etos = function(enm) {
    switch(enm){
        case 1 : return 'E_DDERANK_CODE';
        case 2 : return 'E_DDERANK_NAME';
        case 3 : return 'E_DDERANK_NOWPRICE';
        case 4 : return 'E_DDERANK_CHG';
        case 5 : return 'E_DDERANK_TURNOVERRATE';
        case 6 : return 'E_DDERANK_DDX';
        case 7 : return 'E_DDERANK_DDY';
        case 8 : return 'E_DDERANK_DDZ';
        case 9 : return 'E_DDERANK_DDF';
        case 10 : return 'E_DDERANK_DDX5';
        case 11 : return 'E_DDERANK_DDY5';
        case 12 : return 'E_DDERANK_DDX60';
        case 13 : return 'E_DDERANK_DDY60';
    }
    return undefined;
};

HQSys.E_DDERANK_SORT_COLUMN.stoe = function(enm) {
    switch(enm){
        case 'E_DDERANK_CODE' : return 1;
        case 'E_DDERANK_NAME' : return 2;
        case 'E_DDERANK_NOWPRICE' : return 3;
        case 'E_DDERANK_CHG' : return 4;
        case 'E_DDERANK_TURNOVERRATE' : return 5;
        case 'E_DDERANK_DDX' : return 6;
        case 'E_DDERANK_DDY' : return 7;
        case 'E_DDERANK_DDZ' : return 8;
        case 'E_DDERANK_DDF' : return 9;
        case 'E_DDERANK_DDX5' : return 10;
        case 'E_DDERANK_DDY5' : return 11;
        case 'E_DDERANK_DDX60' : return 12;
        case 'E_DDERANK_DDY60' : return 13;
    }
    return undefined;
};

HQSys.E_DDERANK_SORT_COLUMN._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_DDERANK_SORT_COLUMN._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_STOCK_ORDER_TYPE = {
    E_STOCK_SUPER_BUY : 0,
    E_STOCK_SUPER_SELL : 1,
    E_STOCK_UP_STOP : 2,
    E_STOCK_DOWN_STOP : 3,
    E_STOCK_OPEN_UP_STOP : 4,
    E_STOCK_OPEN_DOWN_STOP : 5,
    E_STOCK_POST_LARGE_BUY : 6,
    E_STOCK_POST_LARGE_SELL : 7,
    E_STOCK_SUPER_LARGE_BUY : 8,
    E_STOCK_SUPER_LARGE_SELL : 9,
    E_STOCK_LARGE_BUY_IN : 14,
    E_STOCK_LAGRGE_SELL_OUT : 15,
    E_STOCK_BUY_FEN_DAN : 16,
    E_STOCK_SELL_FEN_DAN : 17,
    E_STOCK_ROCKET_RUSH : 22,
    E_STOCK_QUICK_BUCKUP : 23,
    E_STOCK_HIGH_DIVING : 24,
    E_STOCK_QUICK_DOWN : 25,
    E_STOCK_CANCEL_BUY : 26,
    E_STOCK_CANCEL_SELL : 27,
    E_STOCK_RADAR : 51,
    E_STOCK_PAD_ORDER : 55,
    E_STOCK_PRESS_ORDER : 56,
    E_STOCK_CLIP_ORDER : 57,
    E_STOCK_HEDGE_ORDER : 58,
    E_STOCK_JUMP_PRICE_DOWN_ORDER : 59,
    E_STOCK_JUMP_PRICE_UP_ORDER : 60,
    E_STOCK_ORDER_ALL : 99
};

HQSys.E_STOCK_ORDER_TYPE.etos = function(enm) {
    switch(enm){
        case 0 : return 'E_STOCK_SUPER_BUY';
        case 1 : return 'E_STOCK_SUPER_SELL';
        case 2 : return 'E_STOCK_UP_STOP';
        case 3 : return 'E_STOCK_DOWN_STOP';
        case 4 : return 'E_STOCK_OPEN_UP_STOP';
        case 5 : return 'E_STOCK_OPEN_DOWN_STOP';
        case 6 : return 'E_STOCK_POST_LARGE_BUY';
        case 7 : return 'E_STOCK_POST_LARGE_SELL';
        case 8 : return 'E_STOCK_SUPER_LARGE_BUY';
        case 9 : return 'E_STOCK_SUPER_LARGE_SELL';
        case 14 : return 'E_STOCK_LARGE_BUY_IN';
        case 15 : return 'E_STOCK_LAGRGE_SELL_OUT';
        case 16 : return 'E_STOCK_BUY_FEN_DAN';
        case 17 : return 'E_STOCK_SELL_FEN_DAN';
        case 22 : return 'E_STOCK_ROCKET_RUSH';
        case 23 : return 'E_STOCK_QUICK_BUCKUP';
        case 24 : return 'E_STOCK_HIGH_DIVING';
        case 25 : return 'E_STOCK_QUICK_DOWN';
        case 26 : return 'E_STOCK_CANCEL_BUY';
        case 27 : return 'E_STOCK_CANCEL_SELL';
        case 51 : return 'E_STOCK_RADAR';
        case 55 : return 'E_STOCK_PAD_ORDER';
        case 56 : return 'E_STOCK_PRESS_ORDER';
        case 57 : return 'E_STOCK_CLIP_ORDER';
        case 58 : return 'E_STOCK_HEDGE_ORDER';
        case 59 : return 'E_STOCK_JUMP_PRICE_DOWN_ORDER';
        case 60 : return 'E_STOCK_JUMP_PRICE_UP_ORDER';
        case 99 : return 'E_STOCK_ORDER_ALL';
    }
    return undefined;
};

HQSys.E_STOCK_ORDER_TYPE.stoe = function(enm) {
    switch(enm){
        case 'E_STOCK_SUPER_BUY' : return 0;
        case 'E_STOCK_SUPER_SELL' : return 1;
        case 'E_STOCK_UP_STOP' : return 2;
        case 'E_STOCK_DOWN_STOP' : return 3;
        case 'E_STOCK_OPEN_UP_STOP' : return 4;
        case 'E_STOCK_OPEN_DOWN_STOP' : return 5;
        case 'E_STOCK_POST_LARGE_BUY' : return 6;
        case 'E_STOCK_POST_LARGE_SELL' : return 7;
        case 'E_STOCK_SUPER_LARGE_BUY' : return 8;
        case 'E_STOCK_SUPER_LARGE_SELL' : return 9;
        case 'E_STOCK_LARGE_BUY_IN' : return 14;
        case 'E_STOCK_LAGRGE_SELL_OUT' : return 15;
        case 'E_STOCK_BUY_FEN_DAN' : return 16;
        case 'E_STOCK_SELL_FEN_DAN' : return 17;
        case 'E_STOCK_ROCKET_RUSH' : return 22;
        case 'E_STOCK_QUICK_BUCKUP' : return 23;
        case 'E_STOCK_HIGH_DIVING' : return 24;
        case 'E_STOCK_QUICK_DOWN' : return 25;
        case 'E_STOCK_CANCEL_BUY' : return 26;
        case 'E_STOCK_CANCEL_SELL' : return 27;
        case 'E_STOCK_RADAR' : return 51;
        case 'E_STOCK_PAD_ORDER' : return 55;
        case 'E_STOCK_PRESS_ORDER' : return 56;
        case 'E_STOCK_CLIP_ORDER' : return 57;
        case 'E_STOCK_HEDGE_ORDER' : return 58;
        case 'E_STOCK_JUMP_PRICE_DOWN_ORDER' : return 59;
        case 'E_STOCK_JUMP_PRICE_UP_ORDER' : return 60;
        case 'E_STOCK_ORDER_ALL' : return 99;
    }
    return undefined;
};

HQSys.E_STOCK_ORDER_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_STOCK_ORDER_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_SZFY_ORDER_TYPE = {
    E_SZFY_TIMES : 0,
    E_SZFY_VOL : 1,
    E_SZFY_AMT : 2
};

HQSys.E_SZFY_ORDER_TYPE.etos = function(enm) {
    switch(enm){
        case 0 : return 'E_SZFY_TIMES';
        case 1 : return 'E_SZFY_VOL';
        case 2 : return 'E_SZFY_AMT';
    }
    return undefined;
};

HQSys.E_SZFY_ORDER_TYPE.stoe = function(enm) {
    switch(enm){
        case 'E_SZFY_TIMES' : return 0;
        case 'E_SZFY_VOL' : return 1;
        case 'E_SZFY_AMT' : return 2;
    }
    return undefined;
};

HQSys.E_SZFY_ORDER_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_SZFY_ORDER_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_COM_ORDER_TYPE = {
    E_COT_TLJ : 0,
    E_COT_DJ : 1,
    E_COT_ZL : 2
};

HQSys.E_COM_ORDER_TYPE.etos = function(enm) {
    switch(enm){
        case 0 : return 'E_COT_TLJ';
        case 1 : return 'E_COT_DJ';
        case 2 : return 'E_COT_ZL';
    }
    return undefined;
};

HQSys.E_COM_ORDER_TYPE.stoe = function(enm) {
    switch(enm){
        case 'E_COT_TLJ' : return 0;
        case 'E_COT_DJ' : return 1;
        case 'E_COT_ZL' : return 2;
    }
    return undefined;
};

HQSys.E_COM_ORDER_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_COM_ORDER_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_HQ_SORT_COLUMN = {
    E_HQ_COLUMN_CODE : 1,
    E_HQ_COLUMN_NAME : 2,
    E_HQ_COLUMN_YCLOSE : 3,
    E_HQ_COLUMN_OPEN : 4,
    E_HQ_COLUMN_HIGH : 5,
    E_HQ_COLUMN_LOW : 6,
    E_HQ_COLUMN_NOWPRICE : 7,
    E_HQ_COLUMN_BUY : 8,
    E_HQ_COLUMN_SELL : 9,
    E_HQ_COLUMN_VOLUME : 10,
    E_HQ_COLUMN_AMOUNT : 11,
    E_HQ_COLUMN_CURVOL : 12,
    E_HQ_COLUMN_CHANGE : 13,
    E_HQ_COLUMN_CHG : 14,
    E_HQ_COLUMN_AMPLITUDE : 15,
    E_HQ_COLUMN_AVGPRICE : 16,
    E_HQ_COLUMN_PREOPENINTEREST : 17,
    E_HQ_COLUMN_PRESETTLEMENTPRICE : 18,
    E_HQ_COLUMN_OPENINTEREST : 19,
    E_HQ_COLUMN_TURNOVERRATE : 20,
    E_HQ_COLUMN_LIANGBI : 23,
    E_HQ_COLUMN_MAIN_NET_BUY : 24,
    E_HQ_COLUMN_MAIN_RATIO : 25,
    E_HQ_COLUMN_UP_SPEED : 26,
    E_HQ_COLUMN_WEIBI : 27,
    E_HQ_COLUMN_PERATIO : 28,
    E_HQ_COLUMN_PRICERATIO : 29,
    E_HQ_COLUMN_CURRENTMARKET : 30,
    E_HQ_COLUMN_TOTALMARKET : 31,
    E_HQ_COLUMN_MGSY : 32,
    E_HQ_COLUMN_MGJZC : 33,
    E_HQ_COLUMN_JZCSYL : 34,
    E_HQ_COLUMN_YSZZL3Y : 35,
    E_HQ_COLUMN_JLSZZL3Y : 36
};

HQSys.E_HQ_SORT_COLUMN.etos = function(enm) {
    switch(enm){
        case 1 : return 'E_HQ_COLUMN_CODE';
        case 2 : return 'E_HQ_COLUMN_NAME';
        case 3 : return 'E_HQ_COLUMN_YCLOSE';
        case 4 : return 'E_HQ_COLUMN_OPEN';
        case 5 : return 'E_HQ_COLUMN_HIGH';
        case 6 : return 'E_HQ_COLUMN_LOW';
        case 7 : return 'E_HQ_COLUMN_NOWPRICE';
        case 8 : return 'E_HQ_COLUMN_BUY';
        case 9 : return 'E_HQ_COLUMN_SELL';
        case 10 : return 'E_HQ_COLUMN_VOLUME';
        case 11 : return 'E_HQ_COLUMN_AMOUNT';
        case 12 : return 'E_HQ_COLUMN_CURVOL';
        case 13 : return 'E_HQ_COLUMN_CHANGE';
        case 14 : return 'E_HQ_COLUMN_CHG';
        case 15 : return 'E_HQ_COLUMN_AMPLITUDE';
        case 16 : return 'E_HQ_COLUMN_AVGPRICE';
        case 17 : return 'E_HQ_COLUMN_PREOPENINTEREST';
        case 18 : return 'E_HQ_COLUMN_PRESETTLEMENTPRICE';
        case 19 : return 'E_HQ_COLUMN_OPENINTEREST';
        case 20 : return 'E_HQ_COLUMN_TURNOVERRATE';
        case 23 : return 'E_HQ_COLUMN_LIANGBI';
        case 24 : return 'E_HQ_COLUMN_MAIN_NET_BUY';
        case 25 : return 'E_HQ_COLUMN_MAIN_RATIO';
        case 26 : return 'E_HQ_COLUMN_UP_SPEED';
        case 27 : return 'E_HQ_COLUMN_WEIBI';
        case 28 : return 'E_HQ_COLUMN_PERATIO';
        case 29 : return 'E_HQ_COLUMN_PRICERATIO';
        case 30 : return 'E_HQ_COLUMN_CURRENTMARKET';
        case 31 : return 'E_HQ_COLUMN_TOTALMARKET';
        case 32 : return 'E_HQ_COLUMN_MGSY';
        case 33 : return 'E_HQ_COLUMN_MGJZC';
        case 34 : return 'E_HQ_COLUMN_JZCSYL';
        case 35 : return 'E_HQ_COLUMN_YSZZL3Y';
        case 36 : return 'E_HQ_COLUMN_JLSZZL3Y';
    }
    return undefined;
};

HQSys.E_HQ_SORT_COLUMN.stoe = function(enm) {
    switch(enm){
        case 'E_HQ_COLUMN_CODE' : return 1;
        case 'E_HQ_COLUMN_NAME' : return 2;
        case 'E_HQ_COLUMN_YCLOSE' : return 3;
        case 'E_HQ_COLUMN_OPEN' : return 4;
        case 'E_HQ_COLUMN_HIGH' : return 5;
        case 'E_HQ_COLUMN_LOW' : return 6;
        case 'E_HQ_COLUMN_NOWPRICE' : return 7;
        case 'E_HQ_COLUMN_BUY' : return 8;
        case 'E_HQ_COLUMN_SELL' : return 9;
        case 'E_HQ_COLUMN_VOLUME' : return 10;
        case 'E_HQ_COLUMN_AMOUNT' : return 11;
        case 'E_HQ_COLUMN_CURVOL' : return 12;
        case 'E_HQ_COLUMN_CHANGE' : return 13;
        case 'E_HQ_COLUMN_CHG' : return 14;
        case 'E_HQ_COLUMN_AMPLITUDE' : return 15;
        case 'E_HQ_COLUMN_AVGPRICE' : return 16;
        case 'E_HQ_COLUMN_PREOPENINTEREST' : return 17;
        case 'E_HQ_COLUMN_PRESETTLEMENTPRICE' : return 18;
        case 'E_HQ_COLUMN_OPENINTEREST' : return 19;
        case 'E_HQ_COLUMN_TURNOVERRATE' : return 20;
        case 'E_HQ_COLUMN_LIANGBI' : return 23;
        case 'E_HQ_COLUMN_MAIN_NET_BUY' : return 24;
        case 'E_HQ_COLUMN_MAIN_RATIO' : return 25;
        case 'E_HQ_COLUMN_UP_SPEED' : return 26;
        case 'E_HQ_COLUMN_WEIBI' : return 27;
        case 'E_HQ_COLUMN_PERATIO' : return 28;
        case 'E_HQ_COLUMN_PRICERATIO' : return 29;
        case 'E_HQ_COLUMN_CURRENTMARKET' : return 30;
        case 'E_HQ_COLUMN_TOTALMARKET' : return 31;
        case 'E_HQ_COLUMN_MGSY' : return 32;
        case 'E_HQ_COLUMN_MGJZC' : return 33;
        case 'E_HQ_COLUMN_JZCSYL' : return 34;
        case 'E_HQ_COLUMN_YSZZL3Y' : return 35;
        case 'E_HQ_COLUMN_JLSZZL3Y' : return 36;
    }
    return undefined;
};

HQSys.E_HQ_SORT_COLUMN._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_HQ_SORT_COLUMN._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_AH_SORT_COLUMN = {
    E_AH_PREMIUMRATE : 1,
    E_AH_ACODE : 2,
    E_AH_ANAME : 3,
    E_AH_ANOWPRICE : 4,
    E_AH_ACHG : 5,
    E_AH_ACURMARKETVALUE : 6,
    E_AH_ATURNOVERRATE : 7,
    E_AH_ATOTALHAND : 8,
    E_AH_AOWNINDUSTRY : 9,
    E_AH_HCODE : 10,
    E_AH_HNAME : 11,
    E_AH_HNOWPRICE : 12,
    E_AH_HCHG : 13,
    E_AH_HCURMARKETVALUE : 14,
    E_AH_HTURNOVERRATE : 15,
    E_AH_HTOTALHAND : 16,
    E_AH_HOWNINDUSTRY : 17
};

HQSys.E_AH_SORT_COLUMN.etos = function(enm) {
    switch(enm){
        case 1 : return 'E_AH_PREMIUMRATE';
        case 2 : return 'E_AH_ACODE';
        case 3 : return 'E_AH_ANAME';
        case 4 : return 'E_AH_ANOWPRICE';
        case 5 : return 'E_AH_ACHG';
        case 6 : return 'E_AH_ACURMARKETVALUE';
        case 7 : return 'E_AH_ATURNOVERRATE';
        case 8 : return 'E_AH_ATOTALHAND';
        case 9 : return 'E_AH_AOWNINDUSTRY';
        case 10 : return 'E_AH_HCODE';
        case 11 : return 'E_AH_HNAME';
        case 12 : return 'E_AH_HNOWPRICE';
        case 13 : return 'E_AH_HCHG';
        case 14 : return 'E_AH_HCURMARKETVALUE';
        case 15 : return 'E_AH_HTURNOVERRATE';
        case 16 : return 'E_AH_HTOTALHAND';
        case 17 : return 'E_AH_HOWNINDUSTRY';
    }
    return undefined;
};

HQSys.E_AH_SORT_COLUMN.stoe = function(enm) {
    switch(enm){
        case 'E_AH_PREMIUMRATE' : return 1;
        case 'E_AH_ACODE' : return 2;
        case 'E_AH_ANAME' : return 3;
        case 'E_AH_ANOWPRICE' : return 4;
        case 'E_AH_ACHG' : return 5;
        case 'E_AH_ACURMARKETVALUE' : return 6;
        case 'E_AH_ATURNOVERRATE' : return 7;
        case 'E_AH_ATOTALHAND' : return 8;
        case 'E_AH_AOWNINDUSTRY' : return 9;
        case 'E_AH_HCODE' : return 10;
        case 'E_AH_HNAME' : return 11;
        case 'E_AH_HNOWPRICE' : return 12;
        case 'E_AH_HCHG' : return 13;
        case 'E_AH_HCURMARKETVALUE' : return 14;
        case 'E_AH_HTURNOVERRATE' : return 15;
        case 'E_AH_HTOTALHAND' : return 16;
        case 'E_AH_HOWNINDUSTRY' : return 17;
    }
    return undefined;
};

HQSys.E_AH_SORT_COLUMN._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_AH_SORT_COLUMN._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_SUGGEST_STOCK_TYPE = {
    E_SUGGEST_ALL : 1,
    E_SUGGEST_STOCK_ONLY : 2,
    E_SUGGEST_INDEX_ONLY : 3,
    E_SUGGEST_STOCK_AB : 4
};

HQSys.E_SUGGEST_STOCK_TYPE.etos = function(enm) {
    switch(enm){
        case 1 : return 'E_SUGGEST_ALL';
        case 2 : return 'E_SUGGEST_STOCK_ONLY';
        case 3 : return 'E_SUGGEST_INDEX_ONLY';
        case 4 : return 'E_SUGGEST_STOCK_AB';
    }
    return undefined;
};

HQSys.E_SUGGEST_STOCK_TYPE.stoe = function(enm) {
    switch(enm){
        case 'E_SUGGEST_ALL' : return 1;
        case 'E_SUGGEST_STOCK_ONLY' : return 2;
        case 'E_SUGGEST_INDEX_ONLY' : return 3;
        case 'E_SUGGEST_STOCK_AB' : return 4;
    }
    return undefined;
};

HQSys.E_SUGGEST_STOCK_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_SUGGEST_STOCK_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
HQSys.E_SUGGEST_STOCK_EXT = {
    E_SUGGEST_EXT_INS : -1
};

HQSys.E_SUGGEST_STOCK_EXT.etos = function(enm) {
    switch(enm){
        case -1 : return 'E_SUGGEST_EXT_INS';
    }
    return undefined;
};

HQSys.E_SUGGEST_STOCK_EXT.stoe = function(enm) {
    switch(enm){
        case 'E_SUGGEST_EXT_INS' : return -1;
    }
    return undefined;
};

HQSys.E_SUGGEST_STOCK_EXT._write = function(os, tag, val) { return os.writeInt32(tag, val); }
HQSys.E_SUGGEST_STOCK_EXT._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }

HQSys.ClientInfo = function() {
    this.vGuid = new TafStream.BinBuffer();
    this.sXua = "";
    this._classname = "HQSys.ClientInfo";
};
HQSys.ClientInfo.prototype = new TafStream.JceStruct();
HQSys.ClientInfo._classname = "HQSys.ClientInfo";

HQSys.ClientInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
HQSys.ClientInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
HQSys.ClientInfo._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new HQSys.ClientInfo();
    tmp.vGuid = is.readBytes(0, false, TafStream.BinBuffer);
    tmp.sXua = is.readString(1, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
HQSys.ClientInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeBytes(0, this.vGuid);
    os.writeString(1, this.sXua);
    os.resumePrecision && os.resumePrecision();
};
HQSys.ClientInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
HQSys.ClientInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
HQSys.ClientInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.vGuid = this.vGuid.toObject();
    tmp.sXua = this.sXua;
    
    return tmp;
}
HQSys.ClientInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vGuid") || (this.vGuid.readFromObject(json.vGuid));
    !json.hasOwnProperty("sXua") || (this.sXua = json.sXua);
}
HQSys.ClientInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
HQSys.ClientInfo.new = function () {
    return new HQSys.ClientInfo();
}
HQSys.ClientInfo.create = function (is) {
    return HQSys.ClientInfo._readFrom(is);
}
HQSys.HeaderInfo = function() {
    this.shtMarket = -1;
    this.stClientInfo = new HQSys.ClientInfo();
    this.eCompress = HQSys.E_CLI_COMP_TYPE.E_CLI_NO_COMP;
    this.bCancelWithReqId = false;
    this._classname = "HQSys.HeaderInfo";
};
HQSys.HeaderInfo.prototype = new TafStream.JceStruct();
HQSys.HeaderInfo._classname = "HQSys.HeaderInfo";

HQSys.HeaderInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
HQSys.HeaderInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
HQSys.HeaderInfo._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new HQSys.HeaderInfo();
    tmp.shtMarket = is.readInt16(0, false, -1);
    tmp.stClientInfo = is.readStruct(1, false, HQSys.ClientInfo);
    tmp.eCompress = is.readInt32(2, false, HQSys.E_CLI_COMP_TYPE.E_CLI_NO_COMP);
    tmp.bCancelWithReqId = is.readBoolean(3, false, false);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
HQSys.HeaderInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt16(0, this.shtMarket);
    os.writeStruct(1, this.stClientInfo);
    os.writeInt32(2, this.eCompress);
    os.writeBoolean(3, this.bCancelWithReqId);
    os.resumePrecision && os.resumePrecision();
};
HQSys.HeaderInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
HQSys.HeaderInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
HQSys.HeaderInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.shtMarket = this.shtMarket;
    tmp.stClientInfo = this.stClientInfo.toObject();
    tmp.eCompress = this.eCompress;
    tmp.bCancelWithReqId = this.bCancelWithReqId;
    
    return tmp;
}
HQSys.HeaderInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("shtMarket") || (this.shtMarket = json.shtMarket);
    !json.hasOwnProperty("stClientInfo") || (this.stClientInfo.readFromObject(json.stClientInfo));
    !json.hasOwnProperty("eCompress") || (this.eCompress = json.eCompress);
    !json.hasOwnProperty("bCancelWithReqId") || (this.bCancelWithReqId = json.bCancelWithReqId);
}
HQSys.HeaderInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
HQSys.HeaderInfo.new = function () {
    return new HQSys.HeaderInfo();
}
HQSys.HeaderInfo.create = function (is) {
    return HQSys.HeaderInfo._readFrom(is);
}


