// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 5.3.1 by TAF Team.
// Generated from `./CommonData.jce'
// **********************************************************************

var TafStream = require('@taf/taf-stream');
var TafError  = require('@taf/taf-rpc').error;

if(TafStream.JceStruct == undefined){
TafStream.JceStruct = function() {
this._jce_double_precision_ = -1;
}
TafStream.JceStruct.prototype.setPrecision = function(d) {
if ((d == -1) || (d >= 0 && d <= 15)) {
this._jce_double_precision_ = d;
return true;
}
return false;
}
TafStream.JceStruct.prototype.resetPrecision = function() { this._jce_double_precision_ = -1;}
TafStream.JceStruct.prototype.hasSetPrecision = function() { return (this._jce_double_precision_ >= 0 && this._jce_double_precision_ <= 15);}
TafStream.JceStruct.prototype.getPrecision = function() { return this._jce_double_precision_; }
}
var _TAF_MODULE_C_ = require('./BasicDataJce.js');
var _TAF_MODULE_E_ = require('./CommonDataJce.js');
var _TAF_MODULE_A_ = require('./FuPanBasicDataJce.js');
var _TAF_MODULE_B_ = require('./FuPanCommonJce.js');
var _TAF_MODULE_D_ = require('./RadarDataJce.js');

var FuPan = FuPan || {};
module.exports.FuPan = FuPan;


FuPan.E_CALL_AUCTION_DATA_TYPE = {
    E_CA_DATA_TYPE_TS : 0,
    E_CA_DATA_TYPE_EXTERN_DATA : 1,
    E_CA_DATA_TYPE_UNU_ACT_RUSH : 2,
    E_CA_DATA_TYPE_UNU_ACT_HIT : 3,
    E_CA_DATA_TYPE_UNU_ACT_OPEN_HIGH : 4,
    E_CA_DATA_TYPE_UNU_ACT_OPEN_LOW : 5,
    E_CA_DATA_TYPE_UNU_ACT_ZT_TRAIL : 6,
    E_CA_DATA_TYPE_UNU_ACT_DT_TRAIL : 7,
    E_CA_DATA_TYPE_UNU_ACT_BUY_STRENGTH : 8,
    E_CA_DATA_TYPE_UNU_ACT_SELL_STRENGTH : 9,
    E_CA_DATA_TYPE_UNU_ACT_LARGE_BUY : 10,
    E_CA_DATA_TYPE_UNU_ACT_LARGE_SELL : 11,
    E_CA_DATA_TYPE_UNU_ACT_RAPID_RISE : 12,
    E_CA_DATA_TYPE_UNU_ACT_RAPID_FALL : 13,
    E_CA_UNU_ACT_TYPE_END : 14
};

FuPan.E_CALL_AUCTION_DATA_TYPE.etos = function(enm) {
    switch(enm){
        case 0 : return 'E_CA_DATA_TYPE_TS';
        case 1 : return 'E_CA_DATA_TYPE_EXTERN_DATA';
        case 2 : return 'E_CA_DATA_TYPE_UNU_ACT_RUSH';
        case 3 : return 'E_CA_DATA_TYPE_UNU_ACT_HIT';
        case 4 : return 'E_CA_DATA_TYPE_UNU_ACT_OPEN_HIGH';
        case 5 : return 'E_CA_DATA_TYPE_UNU_ACT_OPEN_LOW';
        case 6 : return 'E_CA_DATA_TYPE_UNU_ACT_ZT_TRAIL';
        case 7 : return 'E_CA_DATA_TYPE_UNU_ACT_DT_TRAIL';
        case 8 : return 'E_CA_DATA_TYPE_UNU_ACT_BUY_STRENGTH';
        case 9 : return 'E_CA_DATA_TYPE_UNU_ACT_SELL_STRENGTH';
        case 10 : return 'E_CA_DATA_TYPE_UNU_ACT_LARGE_BUY';
        case 11 : return 'E_CA_DATA_TYPE_UNU_ACT_LARGE_SELL';
        case 12 : return 'E_CA_DATA_TYPE_UNU_ACT_RAPID_RISE';
        case 13 : return 'E_CA_DATA_TYPE_UNU_ACT_RAPID_FALL';
        case 14 : return 'E_CA_UNU_ACT_TYPE_END';
    }
    return undefined;
};

FuPan.E_CALL_AUCTION_DATA_TYPE.stoe = function(enm) {
    switch(enm){
        case 'E_CA_DATA_TYPE_TS' : return 0;
        case 'E_CA_DATA_TYPE_EXTERN_DATA' : return 1;
        case 'E_CA_DATA_TYPE_UNU_ACT_RUSH' : return 2;
        case 'E_CA_DATA_TYPE_UNU_ACT_HIT' : return 3;
        case 'E_CA_DATA_TYPE_UNU_ACT_OPEN_HIGH' : return 4;
        case 'E_CA_DATA_TYPE_UNU_ACT_OPEN_LOW' : return 5;
        case 'E_CA_DATA_TYPE_UNU_ACT_ZT_TRAIL' : return 6;
        case 'E_CA_DATA_TYPE_UNU_ACT_DT_TRAIL' : return 7;
        case 'E_CA_DATA_TYPE_UNU_ACT_BUY_STRENGTH' : return 8;
        case 'E_CA_DATA_TYPE_UNU_ACT_SELL_STRENGTH' : return 9;
        case 'E_CA_DATA_TYPE_UNU_ACT_LARGE_BUY' : return 10;
        case 'E_CA_DATA_TYPE_UNU_ACT_LARGE_SELL' : return 11;
        case 'E_CA_DATA_TYPE_UNU_ACT_RAPID_RISE' : return 12;
        case 'E_CA_DATA_TYPE_UNU_ACT_RAPID_FALL' : return 13;
        case 'E_CA_UNU_ACT_TYPE_END' : return 14;
    }
    return undefined;
};

FuPan.E_CALL_AUCTION_DATA_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
FuPan.E_CALL_AUCTION_DATA_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
FuPan.E_CA_UNU_ACT_LEVEL = {
    E_CA_UNU_ACT_LEVEL_BULLISH : 0,
    E_CA_UNU_ACT_LEVEL_PARTIAL_BULLISH : 1,
    E_CA_UNU_ACT_LEVEL_CHAOS : 2,
    E_CA_UNU_ACT_LEVEL_PARTIAL_BEARISH : 3,
    E_CA_UNU_ACT_LEVEL_BEARISH : 4,
    E_CA_UNU_ACT_LEVEL_END : 5
};

FuPan.E_CA_UNU_ACT_LEVEL.etos = function(enm) {
    switch(enm){
        case 0 : return 'E_CA_UNU_ACT_LEVEL_BULLISH';
        case 1 : return 'E_CA_UNU_ACT_LEVEL_PARTIAL_BULLISH';
        case 2 : return 'E_CA_UNU_ACT_LEVEL_CHAOS';
        case 3 : return 'E_CA_UNU_ACT_LEVEL_PARTIAL_BEARISH';
        case 4 : return 'E_CA_UNU_ACT_LEVEL_BEARISH';
        case 5 : return 'E_CA_UNU_ACT_LEVEL_END';
    }
    return undefined;
};

FuPan.E_CA_UNU_ACT_LEVEL.stoe = function(enm) {
    switch(enm){
        case 'E_CA_UNU_ACT_LEVEL_BULLISH' : return 0;
        case 'E_CA_UNU_ACT_LEVEL_PARTIAL_BULLISH' : return 1;
        case 'E_CA_UNU_ACT_LEVEL_CHAOS' : return 2;
        case 'E_CA_UNU_ACT_LEVEL_PARTIAL_BEARISH' : return 3;
        case 'E_CA_UNU_ACT_LEVEL_BEARISH' : return 4;
        case 'E_CA_UNU_ACT_LEVEL_END' : return 5;
    }
    return undefined;
};

FuPan.E_CA_UNU_ACT_LEVEL._write = function(os, tag, val) { return os.writeInt32(tag, val); }
FuPan.E_CA_UNU_ACT_LEVEL._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }

FuPan.FCaUnuActInfo = function() {
    this.iBeginTime = 0;
    this.iEndTime = 0;
    this.dBeginChgRatio = 0;
    this.dBeginPrice = 0;
    this.dEndChgRatio = 0;
    this.dEndPrice = 0;
    this.eCaLv = FuPan.E_CA_UNU_ACT_LEVEL.E_CA_UNU_ACT_LEVEL_BULLISH;
    this.dMatchVol = 0;
    this.dUnMatchVol = 0;
    this.dCallAmount = 0;
    this._classname = "FuPan.FCaUnuActInfo";
};
FuPan.FCaUnuActInfo.prototype = new TafStream.JceStruct();
FuPan.FCaUnuActInfo._classname = "FuPan.FCaUnuActInfo";

FuPan.FCaUnuActInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FCaUnuActInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FCaUnuActInfo._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FCaUnuActInfo();
    tmp.iBeginTime = is.readInt32(0, false, 0);
    tmp.iEndTime = is.readInt32(1, false, 0);
    tmp.dBeginChgRatio = is.readDouble(2, false, 0);
    tmp.dBeginPrice = is.readDouble(3, false, 0);
    tmp.dEndChgRatio = is.readDouble(4, false, 0);
    tmp.dEndPrice = is.readDouble(5, false, 0);
    tmp.eCaLv = is.readInt32(6, false, FuPan.E_CA_UNU_ACT_LEVEL.E_CA_UNU_ACT_LEVEL_BULLISH);
    tmp.dMatchVol = is.readDouble(7, false, 0);
    tmp.dUnMatchVol = is.readDouble(8, false, 0);
    tmp.dCallAmount = is.readDouble(9, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FCaUnuActInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iBeginTime != undefined && this.iBeginTime != 0) {
        os.writeInt32(0, this.iBeginTime);
    }
    if (this.iEndTime != undefined && this.iEndTime != 0) {
        os.writeInt32(1, this.iEndTime);
    }
    if (this.dBeginChgRatio != undefined && this.dBeginChgRatio != 0) {
        os.writeDouble(2, this.dBeginChgRatio);
    }
    if (this.dBeginPrice != undefined && this.dBeginPrice != 0) {
        os.writeDouble(3, this.dBeginPrice);
    }
    if (this.dEndChgRatio != undefined && this.dEndChgRatio != 0) {
        os.writeDouble(4, this.dEndChgRatio);
    }
    if (this.dEndPrice != undefined && this.dEndPrice != 0) {
        os.writeDouble(5, this.dEndPrice);
    }
    if (this.eCaLv != undefined) {
        os.writeInt32(6, this.eCaLv);
    }
    if (this.dMatchVol != undefined && this.dMatchVol != 0) {
        os.writeDouble(7, this.dMatchVol);
    }
    if (this.dUnMatchVol != undefined && this.dUnMatchVol != 0) {
        os.writeDouble(8, this.dUnMatchVol);
    }
    if (this.dCallAmount != undefined && this.dCallAmount != 0) {
        os.writeDouble(9, this.dCallAmount);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FCaUnuActInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FCaUnuActInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FCaUnuActInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.iBeginTime = this.iBeginTime;
    tmp.iEndTime = this.iEndTime;
    tmp.dBeginChgRatio = this.dBeginChgRatio;
    tmp.dBeginPrice = this.dBeginPrice;
    tmp.dEndChgRatio = this.dEndChgRatio;
    tmp.dEndPrice = this.dEndPrice;
    tmp.eCaLv = this.eCaLv;
    tmp.dMatchVol = this.dMatchVol;
    tmp.dUnMatchVol = this.dUnMatchVol;
    tmp.dCallAmount = this.dCallAmount;
    
    return tmp;
}
FuPan.FCaUnuActInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iBeginTime") || (this.iBeginTime = json.iBeginTime);
    !json.hasOwnProperty("iEndTime") || (this.iEndTime = json.iEndTime);
    !json.hasOwnProperty("dBeginChgRatio") || (this.dBeginChgRatio = json.dBeginChgRatio);
    !json.hasOwnProperty("dBeginPrice") || (this.dBeginPrice = json.dBeginPrice);
    !json.hasOwnProperty("dEndChgRatio") || (this.dEndChgRatio = json.dEndChgRatio);
    !json.hasOwnProperty("dEndPrice") || (this.dEndPrice = json.dEndPrice);
    !json.hasOwnProperty("eCaLv") || (this.eCaLv = json.eCaLv);
    !json.hasOwnProperty("dMatchVol") || (this.dMatchVol = json.dMatchVol);
    !json.hasOwnProperty("dUnMatchVol") || (this.dUnMatchVol = json.dUnMatchVol);
    !json.hasOwnProperty("dCallAmount") || (this.dCallAmount = json.dCallAmount);
}
FuPan.FCaUnuActInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FCaUnuActInfo.new = function () {
    return new FuPan.FCaUnuActInfo();
}
FuPan.FCaUnuActInfo.create = function (is) {
    return FuPan.FCaUnuActInfo._readFrom(is);
}
FuPan.FCaTsInfo = function() {
    this.iTime = 0;
    this.dChgRatio = 0;
    this.dNowPrice = 0;
    this._classname = "FuPan.FCaTsInfo";
};
FuPan.FCaTsInfo.prototype = new TafStream.JceStruct();
FuPan.FCaTsInfo._classname = "FuPan.FCaTsInfo";

FuPan.FCaTsInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FCaTsInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FCaTsInfo._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FCaTsInfo();
    tmp.iTime = is.readInt32(0, false, 0);
    tmp.dChgRatio = is.readDouble(1, false, 0);
    tmp.dNowPrice = is.readDouble(2, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FCaTsInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iTime != undefined && this.iTime != 0) {
        os.writeInt32(0, this.iTime);
    }
    if (this.dChgRatio != undefined && this.dChgRatio != 0) {
        os.writeDouble(1, this.dChgRatio);
    }
    if (this.dNowPrice != undefined && this.dNowPrice != 0) {
        os.writeDouble(2, this.dNowPrice);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FCaTsInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FCaTsInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FCaTsInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.iTime = this.iTime;
    tmp.dChgRatio = this.dChgRatio;
    tmp.dNowPrice = this.dNowPrice;
    
    return tmp;
}
FuPan.FCaTsInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iTime") || (this.iTime = json.iTime);
    !json.hasOwnProperty("dChgRatio") || (this.dChgRatio = json.dChgRatio);
    !json.hasOwnProperty("dNowPrice") || (this.dNowPrice = json.dNowPrice);
}
FuPan.FCaTsInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FCaTsInfo.new = function () {
    return new FuPan.FCaTsInfo();
}
FuPan.FCaTsInfo.create = function (is) {
    return FuPan.FCaTsInfo._readFrom(is);
}
FuPan.FLastCaUnuActTypeInfo = function() {
    this.eCaType = FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS;
    this.stCaUnuAct = new FuPan.FCaUnuActInfo();
    this.dOpenPrice = 0;
    this.dOpenChgRatio = 0;
    this.dOpenAmount = 0;
    this.dNowChgRatio = 0;
    this.dPreCallAmoutRatio = 0;
    this._classname = "FuPan.FLastCaUnuActTypeInfo";
};
FuPan.FLastCaUnuActTypeInfo.prototype = new TafStream.JceStruct();
FuPan.FLastCaUnuActTypeInfo._classname = "FuPan.FLastCaUnuActTypeInfo";

FuPan.FLastCaUnuActTypeInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FLastCaUnuActTypeInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FLastCaUnuActTypeInfo._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FLastCaUnuActTypeInfo();
    tmp.eCaType = is.readInt32(0, false, FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS);
    tmp.stCaUnuAct = is.readStruct(1, false, FuPan.FCaUnuActInfo);
    tmp.dOpenPrice = is.readDouble(2, false, 0);
    tmp.dOpenChgRatio = is.readDouble(3, false, 0);
    tmp.dOpenAmount = is.readDouble(4, false, 0);
    tmp.dNowChgRatio = is.readDouble(5, false, 0);
    tmp.dPreCallAmoutRatio = is.readDouble(6, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FLastCaUnuActTypeInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.eCaType != undefined) {
        os.writeInt32(0, this.eCaType);
    }
    os.writeStruct(1, this.stCaUnuAct);
    if (this.dOpenPrice != undefined && this.dOpenPrice != 0) {
        os.writeDouble(2, this.dOpenPrice);
    }
    if (this.dOpenChgRatio != undefined && this.dOpenChgRatio != 0) {
        os.writeDouble(3, this.dOpenChgRatio);
    }
    if (this.dOpenAmount != undefined && this.dOpenAmount != 0) {
        os.writeDouble(4, this.dOpenAmount);
    }
    if (this.dNowChgRatio != undefined && this.dNowChgRatio != 0) {
        os.writeDouble(5, this.dNowChgRatio);
    }
    if (this.dPreCallAmoutRatio != undefined && this.dPreCallAmoutRatio != 0) {
        os.writeDouble(6, this.dPreCallAmoutRatio);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FLastCaUnuActTypeInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FLastCaUnuActTypeInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FLastCaUnuActTypeInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.eCaType = this.eCaType;
    tmp.stCaUnuAct = this.stCaUnuAct.toObject();
    tmp.dOpenPrice = this.dOpenPrice;
    tmp.dOpenChgRatio = this.dOpenChgRatio;
    tmp.dOpenAmount = this.dOpenAmount;
    tmp.dNowChgRatio = this.dNowChgRatio;
    tmp.dPreCallAmoutRatio = this.dPreCallAmoutRatio;
    
    return tmp;
}
FuPan.FLastCaUnuActTypeInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("eCaType") || (this.eCaType = json.eCaType);
    !json.hasOwnProperty("stCaUnuAct") || (this.stCaUnuAct.readFromObject(json.stCaUnuAct));
    !json.hasOwnProperty("dOpenPrice") || (this.dOpenPrice = json.dOpenPrice);
    !json.hasOwnProperty("dOpenChgRatio") || (this.dOpenChgRatio = json.dOpenChgRatio);
    !json.hasOwnProperty("dOpenAmount") || (this.dOpenAmount = json.dOpenAmount);
    !json.hasOwnProperty("dNowChgRatio") || (this.dNowChgRatio = json.dNowChgRatio);
    !json.hasOwnProperty("dPreCallAmoutRatio") || (this.dPreCallAmoutRatio = json.dPreCallAmoutRatio);
}
FuPan.FLastCaUnuActTypeInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FLastCaUnuActTypeInfo.new = function () {
    return new FuPan.FLastCaUnuActTypeInfo();
}
FuPan.FLastCaUnuActTypeInfo.create = function (is) {
    return FuPan.FLastCaUnuActTypeInfo._readFrom(is);
}
FuPan.FStkLastCaUnuAct = function() {
    this.stk = new _TAF_MODULE_A_.FuPan.StkSimpInfo();
    this.lastCaTypeInfo = new FuPan.FLastCaUnuActTypeInfo();
    this._classname = "FuPan.FStkLastCaUnuAct";
};
FuPan.FStkLastCaUnuAct.prototype = new TafStream.JceStruct();
FuPan.FStkLastCaUnuAct._classname = "FuPan.FStkLastCaUnuAct";

FuPan.FStkLastCaUnuAct._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FStkLastCaUnuAct._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FStkLastCaUnuAct._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FStkLastCaUnuAct();
    tmp.stk = is.readStruct(0, false, _TAF_MODULE_A_.FuPan.StkSimpInfo);
    tmp.lastCaTypeInfo = is.readStruct(1, false, FuPan.FLastCaUnuActTypeInfo);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FStkLastCaUnuAct.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.stk);
    os.writeStruct(1, this.lastCaTypeInfo);
    os.resumePrecision && os.resumePrecision();
};
FuPan.FStkLastCaUnuAct.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FStkLastCaUnuAct.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FStkLastCaUnuAct.prototype.toObject = function() { 
    var tmp = {};

    tmp.stk = this.stk.toObject();
    tmp.lastCaTypeInfo = this.lastCaTypeInfo.toObject();
    
    return tmp;
}
FuPan.FStkLastCaUnuAct.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("stk") || (this.stk.readFromObject(json.stk));
    !json.hasOwnProperty("lastCaTypeInfo") || (this.lastCaTypeInfo.readFromObject(json.lastCaTypeInfo));
}
FuPan.FStkLastCaUnuAct.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FStkLastCaUnuAct.new = function () {
    return new FuPan.FStkLastCaUnuAct();
}
FuPan.FStkLastCaUnuAct.create = function (is) {
    return FuPan.FStkLastCaUnuAct._readFrom(is);
}
FuPan.FBlkLastCaUnuAct = function() {
    this.blk = new _TAF_MODULE_A_.FuPan.FBlockSimpleInfo();
    this.lastCaTypeInfo = new FuPan.FLastCaUnuActTypeInfo();
    this._classname = "FuPan.FBlkLastCaUnuAct";
};
FuPan.FBlkLastCaUnuAct.prototype = new TafStream.JceStruct();
FuPan.FBlkLastCaUnuAct._classname = "FuPan.FBlkLastCaUnuAct";

FuPan.FBlkLastCaUnuAct._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FBlkLastCaUnuAct._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FBlkLastCaUnuAct._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FBlkLastCaUnuAct();
    tmp.blk = is.readStruct(0, false, _TAF_MODULE_A_.FuPan.FBlockSimpleInfo);
    tmp.lastCaTypeInfo = is.readStruct(1, false, FuPan.FLastCaUnuActTypeInfo);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FBlkLastCaUnuAct.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.blk);
    os.writeStruct(1, this.lastCaTypeInfo);
    os.resumePrecision && os.resumePrecision();
};
FuPan.FBlkLastCaUnuAct.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FBlkLastCaUnuAct.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FBlkLastCaUnuAct.prototype.toObject = function() { 
    var tmp = {};

    tmp.blk = this.blk.toObject();
    tmp.lastCaTypeInfo = this.lastCaTypeInfo.toObject();
    
    return tmp;
}
FuPan.FBlkLastCaUnuAct.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("blk") || (this.blk.readFromObject(json.blk));
    !json.hasOwnProperty("lastCaTypeInfo") || (this.lastCaTypeInfo.readFromObject(json.lastCaTypeInfo));
}
FuPan.FBlkLastCaUnuAct.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FBlkLastCaUnuAct.new = function () {
    return new FuPan.FBlkLastCaUnuAct();
}
FuPan.FBlkLastCaUnuAct.create = function (is) {
    return FuPan.FBlkLastCaUnuAct._readFrom(is);
}
FuPan.FLastCaUnuActLevelStk = function() {
    this.iDate = 0;
    this.eCaLevel = FuPan.E_CA_UNU_ACT_LEVEL.E_CA_UNU_ACT_LEVEL_BULLISH;
    this.mapStkCaUnuAct = new TafStream.Map(TafStream.String, FuPan.FStkLastCaUnuAct);
    this.mapBlkCaUnuAct = new TafStream.Map(TafStream.String, FuPan.FBlkLastCaUnuAct);
    this._classname = "FuPan.FLastCaUnuActLevelStk";
};
FuPan.FLastCaUnuActLevelStk.prototype = new TafStream.JceStruct();
FuPan.FLastCaUnuActLevelStk._classname = "FuPan.FLastCaUnuActLevelStk";

FuPan.FLastCaUnuActLevelStk._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FLastCaUnuActLevelStk._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FLastCaUnuActLevelStk._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FLastCaUnuActLevelStk();
    tmp.iDate = is.readInt32(0, false, 0);
    tmp.eCaLevel = is.readInt32(1, false, FuPan.E_CA_UNU_ACT_LEVEL.E_CA_UNU_ACT_LEVEL_BULLISH);
    tmp.mapStkCaUnuAct = is.readMap(2, false, TafStream.Map(TafStream.String, FuPan.FStkLastCaUnuAct));
    tmp.mapBlkCaUnuAct = is.readMap(3, false, TafStream.Map(TafStream.String, FuPan.FBlkLastCaUnuAct));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FLastCaUnuActLevelStk.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iDate != undefined && this.iDate != 0) {
        os.writeInt32(0, this.iDate);
    }
    if (this.eCaLevel != undefined) {
        os.writeInt32(1, this.eCaLevel);
    }
    if (this.mapStkCaUnuAct != undefined) {
        os.writeMap(2, this.mapStkCaUnuAct);
    }
    if (this.mapBlkCaUnuAct != undefined) {
        os.writeMap(3, this.mapBlkCaUnuAct);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FLastCaUnuActLevelStk.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FLastCaUnuActLevelStk.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FLastCaUnuActLevelStk.prototype.toObject = function() { 
    var tmp = {};

    tmp.iDate = this.iDate;
    tmp.eCaLevel = this.eCaLevel;
    tmp.mapStkCaUnuAct = this.mapStkCaUnuAct.toObject();
    tmp.mapBlkCaUnuAct = this.mapBlkCaUnuAct.toObject();
    
    return tmp;
}
FuPan.FLastCaUnuActLevelStk.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iDate") || (this.iDate = json.iDate);
    !json.hasOwnProperty("eCaLevel") || (this.eCaLevel = json.eCaLevel);
    !json.hasOwnProperty("mapStkCaUnuAct") || (this.mapStkCaUnuAct.readFromObject(json.mapStkCaUnuAct));
    !json.hasOwnProperty("mapBlkCaUnuAct") || (this.mapBlkCaUnuAct.readFromObject(json.mapBlkCaUnuAct));
}
FuPan.FLastCaUnuActLevelStk.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FLastCaUnuActLevelStk.new = function () {
    return new FuPan.FLastCaUnuActLevelStk();
}
FuPan.FLastCaUnuActLevelStk.create = function (is) {
    return FuPan.FLastCaUnuActLevelStk._readFrom(is);
}
FuPan.FStkCaUnuActTypeInfo = function() {
    this.stk = new _TAF_MODULE_A_.FuPan.StkSimpInfo();
    this.eCaType = FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS;
    this.vecCaUnuAct = new TafStream.List(FuPan.FCaUnuActInfo);
    this.dOpenPrice = 0;
    this.dOpenChgRatio = 0;
    this.dOpenAmount = 0;
    this.dNowChgRatio = 0;
    this.vecBlk = new TafStream.List(_TAF_MODULE_A_.FuPan.FBlockSimpleInfo);
    this.strCaUnuActDesc = "";
    this.bIsSTStk = false;
    this.bSubNewStock = false;
    this.dPreCallAmoutRatio = 0;
    this._classname = "FuPan.FStkCaUnuActTypeInfo";
};
FuPan.FStkCaUnuActTypeInfo.prototype = new TafStream.JceStruct();
FuPan.FStkCaUnuActTypeInfo._classname = "FuPan.FStkCaUnuActTypeInfo";

FuPan.FStkCaUnuActTypeInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FStkCaUnuActTypeInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FStkCaUnuActTypeInfo._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FStkCaUnuActTypeInfo();
    tmp.stk = is.readStruct(0, false, _TAF_MODULE_A_.FuPan.StkSimpInfo);
    tmp.eCaType = is.readInt32(1, false, FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS);
    tmp.vecCaUnuAct = is.readList(2, false, TafStream.List(FuPan.FCaUnuActInfo));
    tmp.dOpenPrice = is.readDouble(3, false, 0);
    tmp.dOpenChgRatio = is.readDouble(4, false, 0);
    tmp.dOpenAmount = is.readDouble(5, false, 0);
    tmp.dNowChgRatio = is.readDouble(6, false, 0);
    tmp.vecBlk = is.readList(7, false, TafStream.List(_TAF_MODULE_A_.FuPan.FBlockSimpleInfo));
    tmp.strCaUnuActDesc = is.readString(8, false, "");
    tmp.bIsSTStk = is.readBoolean(9, false, false);
    tmp.bSubNewStock = is.readBoolean(10, false, false);
    tmp.dPreCallAmoutRatio = is.readDouble(11, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FStkCaUnuActTypeInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.stk);
    if (this.eCaType != undefined) {
        os.writeInt32(1, this.eCaType);
    }
    if (this.vecCaUnuAct != undefined) {
        os.writeList(2, this.vecCaUnuAct);
    }
    if (this.dOpenPrice != undefined && this.dOpenPrice != 0) {
        os.writeDouble(3, this.dOpenPrice);
    }
    if (this.dOpenChgRatio != undefined && this.dOpenChgRatio != 0) {
        os.writeDouble(4, this.dOpenChgRatio);
    }
    if (this.dOpenAmount != undefined && this.dOpenAmount != 0) {
        os.writeDouble(5, this.dOpenAmount);
    }
    if (this.dNowChgRatio != undefined && this.dNowChgRatio != 0) {
        os.writeDouble(6, this.dNowChgRatio);
    }
    if (this.vecBlk != undefined) {
        os.writeList(7, this.vecBlk);
    }
    if (this.strCaUnuActDesc != undefined && this.strCaUnuActDesc != "") {
        os.writeString(8, this.strCaUnuActDesc);
    }
    if (this.bIsSTStk != undefined && this.bIsSTStk != false) {
        os.writeBoolean(9, this.bIsSTStk);
    }
    if (this.bSubNewStock != undefined && this.bSubNewStock != false) {
        os.writeBoolean(10, this.bSubNewStock);
    }
    if (this.dPreCallAmoutRatio != undefined && this.dPreCallAmoutRatio != 0) {
        os.writeDouble(11, this.dPreCallAmoutRatio);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FStkCaUnuActTypeInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FStkCaUnuActTypeInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FStkCaUnuActTypeInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.stk = this.stk.toObject();
    tmp.eCaType = this.eCaType;
    tmp.vecCaUnuAct = this.vecCaUnuAct.toObject();
    tmp.dOpenPrice = this.dOpenPrice;
    tmp.dOpenChgRatio = this.dOpenChgRatio;
    tmp.dOpenAmount = this.dOpenAmount;
    tmp.dNowChgRatio = this.dNowChgRatio;
    tmp.vecBlk = this.vecBlk.toObject();
    tmp.strCaUnuActDesc = this.strCaUnuActDesc;
    tmp.bIsSTStk = this.bIsSTStk;
    tmp.bSubNewStock = this.bSubNewStock;
    tmp.dPreCallAmoutRatio = this.dPreCallAmoutRatio;
    
    return tmp;
}
FuPan.FStkCaUnuActTypeInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("stk") || (this.stk.readFromObject(json.stk));
    !json.hasOwnProperty("eCaType") || (this.eCaType = json.eCaType);
    !json.hasOwnProperty("vecCaUnuAct") || (this.vecCaUnuAct.readFromObject(json.vecCaUnuAct));
    !json.hasOwnProperty("dOpenPrice") || (this.dOpenPrice = json.dOpenPrice);
    !json.hasOwnProperty("dOpenChgRatio") || (this.dOpenChgRatio = json.dOpenChgRatio);
    !json.hasOwnProperty("dOpenAmount") || (this.dOpenAmount = json.dOpenAmount);
    !json.hasOwnProperty("dNowChgRatio") || (this.dNowChgRatio = json.dNowChgRatio);
    !json.hasOwnProperty("vecBlk") || (this.vecBlk.readFromObject(json.vecBlk));
    !json.hasOwnProperty("strCaUnuActDesc") || (this.strCaUnuActDesc = json.strCaUnuActDesc);
    !json.hasOwnProperty("bIsSTStk") || (this.bIsSTStk = json.bIsSTStk);
    !json.hasOwnProperty("bSubNewStock") || (this.bSubNewStock = json.bSubNewStock);
    !json.hasOwnProperty("dPreCallAmoutRatio") || (this.dPreCallAmoutRatio = json.dPreCallAmoutRatio);
}
FuPan.FStkCaUnuActTypeInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FStkCaUnuActTypeInfo.new = function () {
    return new FuPan.FStkCaUnuActTypeInfo();
}
FuPan.FStkCaUnuActTypeInfo.create = function (is) {
    return FuPan.FStkCaUnuActTypeInfo._readFrom(is);
}
FuPan.FStkCaTs = function() {
    this.stk = new _TAF_MODULE_A_.FuPan.StkSimpInfo();
    this.vecTs = new TafStream.List(FuPan.FCaTsInfo);
    this._classname = "FuPan.FStkCaTs";
};
FuPan.FStkCaTs.prototype = new TafStream.JceStruct();
FuPan.FStkCaTs._classname = "FuPan.FStkCaTs";

FuPan.FStkCaTs._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FStkCaTs._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FStkCaTs._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FStkCaTs();
    tmp.stk = is.readStruct(0, false, _TAF_MODULE_A_.FuPan.StkSimpInfo);
    tmp.vecTs = is.readList(1, false, TafStream.List(FuPan.FCaTsInfo));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FStkCaTs.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.stk);
    if (this.vecTs != undefined) {
        os.writeList(1, this.vecTs);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FStkCaTs.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FStkCaTs.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FStkCaTs.prototype.toObject = function() { 
    var tmp = {};

    tmp.stk = this.stk.toObject();
    tmp.vecTs = this.vecTs.toObject();
    
    return tmp;
}
FuPan.FStkCaTs.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("stk") || (this.stk.readFromObject(json.stk));
    !json.hasOwnProperty("vecTs") || (this.vecTs.readFromObject(json.vecTs));
}
FuPan.FStkCaTs.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FStkCaTs.new = function () {
    return new FuPan.FStkCaTs();
}
FuPan.FStkCaTs.create = function (is) {
    return FuPan.FStkCaTs._readFrom(is);
}
FuPan.FBlkCaUnuActTypeInfo = function() {
    this.blk = new _TAF_MODULE_A_.FuPan.FBlockSimpleInfo();
    this.vecCaUnuAct = new TafStream.List(FuPan.FCaUnuActInfo);
    this.dOpenPrice = 0;
    this.dOpenChgRatio = 0;
    this._classname = "FuPan.FBlkCaUnuActTypeInfo";
};
FuPan.FBlkCaUnuActTypeInfo.prototype = new TafStream.JceStruct();
FuPan.FBlkCaUnuActTypeInfo._classname = "FuPan.FBlkCaUnuActTypeInfo";

FuPan.FBlkCaUnuActTypeInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FBlkCaUnuActTypeInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FBlkCaUnuActTypeInfo._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FBlkCaUnuActTypeInfo();
    tmp.blk = is.readStruct(0, false, _TAF_MODULE_A_.FuPan.FBlockSimpleInfo);
    tmp.vecCaUnuAct = is.readList(1, false, TafStream.List(FuPan.FCaUnuActInfo));
    tmp.dOpenPrice = is.readDouble(2, false, 0);
    tmp.dOpenChgRatio = is.readDouble(3, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FBlkCaUnuActTypeInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.blk);
    if (this.vecCaUnuAct != undefined) {
        os.writeList(1, this.vecCaUnuAct);
    }
    if (this.dOpenPrice != undefined && this.dOpenPrice != 0) {
        os.writeDouble(2, this.dOpenPrice);
    }
    if (this.dOpenChgRatio != undefined && this.dOpenChgRatio != 0) {
        os.writeDouble(3, this.dOpenChgRatio);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FBlkCaUnuActTypeInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FBlkCaUnuActTypeInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FBlkCaUnuActTypeInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.blk = this.blk.toObject();
    tmp.vecCaUnuAct = this.vecCaUnuAct.toObject();
    tmp.dOpenPrice = this.dOpenPrice;
    tmp.dOpenChgRatio = this.dOpenChgRatio;
    
    return tmp;
}
FuPan.FBlkCaUnuActTypeInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("blk") || (this.blk.readFromObject(json.blk));
    !json.hasOwnProperty("vecCaUnuAct") || (this.vecCaUnuAct.readFromObject(json.vecCaUnuAct));
    !json.hasOwnProperty("dOpenPrice") || (this.dOpenPrice = json.dOpenPrice);
    !json.hasOwnProperty("dOpenChgRatio") || (this.dOpenChgRatio = json.dOpenChgRatio);
}
FuPan.FBlkCaUnuActTypeInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FBlkCaUnuActTypeInfo.new = function () {
    return new FuPan.FBlkCaUnuActTypeInfo();
}
FuPan.FBlkCaUnuActTypeInfo.create = function (is) {
    return FuPan.FBlkCaUnuActTypeInfo._readFrom(is);
}
FuPan.FBlkCaTs = function() {
    this.blk = new _TAF_MODULE_A_.FuPan.FBlockSimpleInfo();
    this.vecTs = new TafStream.List(FuPan.FCaTsInfo);
    this._classname = "FuPan.FBlkCaTs";
};
FuPan.FBlkCaTs.prototype = new TafStream.JceStruct();
FuPan.FBlkCaTs._classname = "FuPan.FBlkCaTs";

FuPan.FBlkCaTs._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FBlkCaTs._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FBlkCaTs._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FBlkCaTs();
    tmp.blk = is.readStruct(0, false, _TAF_MODULE_A_.FuPan.FBlockSimpleInfo);
    tmp.vecTs = is.readList(1, false, TafStream.List(FuPan.FCaTsInfo));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FBlkCaTs.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.blk);
    if (this.vecTs != undefined) {
        os.writeList(1, this.vecTs);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FBlkCaTs.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FBlkCaTs.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FBlkCaTs.prototype.toObject = function() { 
    var tmp = {};

    tmp.blk = this.blk.toObject();
    tmp.vecTs = this.vecTs.toObject();
    
    return tmp;
}
FuPan.FBlkCaTs.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("blk") || (this.blk.readFromObject(json.blk));
    !json.hasOwnProperty("vecTs") || (this.vecTs.readFromObject(json.vecTs));
}
FuPan.FBlkCaTs.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FBlkCaTs.new = function () {
    return new FuPan.FBlkCaTs();
}
FuPan.FBlkCaTs.create = function (is) {
    return FuPan.FBlkCaTs._readFrom(is);
}
FuPan.FCaUnuActTypeData = function() {
    this.iDate = 0;
    this.eCaType = FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS;
    this.mapStkUnuActInfo = new TafStream.Map(TafStream.String, FuPan.FStkCaUnuActTypeInfo);
    this.mapBlkUnuActInfo = new TafStream.Map(TafStream.String, FuPan.FBlkCaUnuActTypeInfo);
    this._classname = "FuPan.FCaUnuActTypeData";
};
FuPan.FCaUnuActTypeData.prototype = new TafStream.JceStruct();
FuPan.FCaUnuActTypeData._classname = "FuPan.FCaUnuActTypeData";

FuPan.FCaUnuActTypeData._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FCaUnuActTypeData._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FCaUnuActTypeData._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FCaUnuActTypeData();
    tmp.iDate = is.readInt32(0, false, 0);
    tmp.eCaType = is.readInt32(1, false, FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS);
    tmp.mapStkUnuActInfo = is.readMap(2, false, TafStream.Map(TafStream.String, FuPan.FStkCaUnuActTypeInfo));
    tmp.mapBlkUnuActInfo = is.readMap(3, false, TafStream.Map(TafStream.String, FuPan.FBlkCaUnuActTypeInfo));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FCaUnuActTypeData.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iDate != undefined && this.iDate != 0) {
        os.writeInt32(0, this.iDate);
    }
    if (this.eCaType != undefined) {
        os.writeInt32(1, this.eCaType);
    }
    if (this.mapStkUnuActInfo != undefined) {
        os.writeMap(2, this.mapStkUnuActInfo);
    }
    if (this.mapBlkUnuActInfo != undefined) {
        os.writeMap(3, this.mapBlkUnuActInfo);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FCaUnuActTypeData.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FCaUnuActTypeData.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FCaUnuActTypeData.prototype.toObject = function() { 
    var tmp = {};

    tmp.iDate = this.iDate;
    tmp.eCaType = this.eCaType;
    tmp.mapStkUnuActInfo = this.mapStkUnuActInfo.toObject();
    tmp.mapBlkUnuActInfo = this.mapBlkUnuActInfo.toObject();
    
    return tmp;
}
FuPan.FCaUnuActTypeData.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iDate") || (this.iDate = json.iDate);
    !json.hasOwnProperty("eCaType") || (this.eCaType = json.eCaType);
    !json.hasOwnProperty("mapStkUnuActInfo") || (this.mapStkUnuActInfo.readFromObject(json.mapStkUnuActInfo));
    !json.hasOwnProperty("mapBlkUnuActInfo") || (this.mapBlkUnuActInfo.readFromObject(json.mapBlkUnuActInfo));
}
FuPan.FCaUnuActTypeData.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FCaUnuActTypeData.new = function () {
    return new FuPan.FCaUnuActTypeData();
}
FuPan.FCaUnuActTypeData.create = function (is) {
    return FuPan.FCaUnuActTypeData._readFrom(is);
}
FuPan.FCaTsData = function() {
    this.iDate = 0;
    this.eCaType = FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS;
    this.mapStkCaTs = new TafStream.Map(TafStream.String, FuPan.FStkCaTs);
    this.mapBlkCaTs = new TafStream.Map(TafStream.String, FuPan.FBlkCaTs);
    this._classname = "FuPan.FCaTsData";
};
FuPan.FCaTsData.prototype = new TafStream.JceStruct();
FuPan.FCaTsData._classname = "FuPan.FCaTsData";

FuPan.FCaTsData._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FCaTsData._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FCaTsData._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FCaTsData();
    tmp.iDate = is.readInt32(0, false, 0);
    tmp.eCaType = is.readInt32(1, false, FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS);
    tmp.mapStkCaTs = is.readMap(2, false, TafStream.Map(TafStream.String, FuPan.FStkCaTs));
    tmp.mapBlkCaTs = is.readMap(3, false, TafStream.Map(TafStream.String, FuPan.FBlkCaTs));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FCaTsData.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iDate != undefined && this.iDate != 0) {
        os.writeInt32(0, this.iDate);
    }
    if (this.eCaType != undefined) {
        os.writeInt32(1, this.eCaType);
    }
    if (this.mapStkCaTs != undefined) {
        os.writeMap(2, this.mapStkCaTs);
    }
    if (this.mapBlkCaTs != undefined) {
        os.writeMap(3, this.mapBlkCaTs);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FCaTsData.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FCaTsData.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FCaTsData.prototype.toObject = function() { 
    var tmp = {};

    tmp.iDate = this.iDate;
    tmp.eCaType = this.eCaType;
    tmp.mapStkCaTs = this.mapStkCaTs.toObject();
    tmp.mapBlkCaTs = this.mapBlkCaTs.toObject();
    
    return tmp;
}
FuPan.FCaTsData.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iDate") || (this.iDate = json.iDate);
    !json.hasOwnProperty("eCaType") || (this.eCaType = json.eCaType);
    !json.hasOwnProperty("mapStkCaTs") || (this.mapStkCaTs.readFromObject(json.mapStkCaTs));
    !json.hasOwnProperty("mapBlkCaTs") || (this.mapBlkCaTs.readFromObject(json.mapBlkCaTs));
}
FuPan.FCaTsData.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FCaTsData.new = function () {
    return new FuPan.FCaTsData();
}
FuPan.FCaTsData.create = function (is) {
    return FuPan.FCaTsData._readFrom(is);
}
FuPan.FMarketZdFenBu = function() {
    this.iMarket = 0;
    this.vecZdFenBu = new TafStream.List(TafStream.Int32);
    this._classname = "FuPan.FMarketZdFenBu";
};
FuPan.FMarketZdFenBu.prototype = new TafStream.JceStruct();
FuPan.FMarketZdFenBu._classname = "FuPan.FMarketZdFenBu";

FuPan.FMarketZdFenBu._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FMarketZdFenBu._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FMarketZdFenBu._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FMarketZdFenBu();
    tmp.iMarket = is.readInt32(0, false, 0);
    tmp.vecZdFenBu = is.readList(1, false, TafStream.List(TafStream.Int32));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FMarketZdFenBu.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iMarket != undefined && this.iMarket != 0) {
        os.writeInt32(0, this.iMarket);
    }
    if (this.vecZdFenBu != undefined) {
        os.writeList(1, this.vecZdFenBu);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FMarketZdFenBu.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FMarketZdFenBu.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FMarketZdFenBu.prototype.toObject = function() { 
    var tmp = {};

    tmp.iMarket = this.iMarket;
    tmp.vecZdFenBu = this.vecZdFenBu.toObject();
    
    return tmp;
}
FuPan.FMarketZdFenBu.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iMarket") || (this.iMarket = json.iMarket);
    !json.hasOwnProperty("vecZdFenBu") || (this.vecZdFenBu.readFromObject(json.vecZdFenBu));
}
FuPan.FMarketZdFenBu.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FMarketZdFenBu.new = function () {
    return new FuPan.FMarketZdFenBu();
}
FuPan.FMarketZdFenBu.create = function (is) {
    return FuPan.FMarketZdFenBu._readFrom(is);
}
FuPan.FBlockChgRatio = function() {
    this.blk = new _TAF_MODULE_A_.FuPan.FBlockSimpleInfo();
    this.dNowChgRatio = 0;
    this.dOpenPrice = 0;
    this.dOpenChgRatio = 0;
    this._classname = "FuPan.FBlockChgRatio";
};
FuPan.FBlockChgRatio.prototype = new TafStream.JceStruct();
FuPan.FBlockChgRatio._classname = "FuPan.FBlockChgRatio";

FuPan.FBlockChgRatio._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FBlockChgRatio._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FBlockChgRatio._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FBlockChgRatio();
    tmp.blk = is.readStruct(0, false, _TAF_MODULE_A_.FuPan.FBlockSimpleInfo);
    tmp.dNowChgRatio = is.readDouble(1, false, 0);
    tmp.dOpenPrice = is.readDouble(2, false, 0);
    tmp.dOpenChgRatio = is.readDouble(3, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FBlockChgRatio.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.blk);
    if (this.dNowChgRatio != undefined && this.dNowChgRatio != 0) {
        os.writeDouble(1, this.dNowChgRatio);
    }
    if (this.dOpenPrice != undefined && this.dOpenPrice != 0) {
        os.writeDouble(2, this.dOpenPrice);
    }
    if (this.dOpenChgRatio != undefined && this.dOpenChgRatio != 0) {
        os.writeDouble(3, this.dOpenChgRatio);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FBlockChgRatio.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FBlockChgRatio.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FBlockChgRatio.prototype.toObject = function() { 
    var tmp = {};

    tmp.blk = this.blk.toObject();
    tmp.dNowChgRatio = this.dNowChgRatio;
    tmp.dOpenPrice = this.dOpenPrice;
    tmp.dOpenChgRatio = this.dOpenChgRatio;
    
    return tmp;
}
FuPan.FBlockChgRatio.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("blk") || (this.blk.readFromObject(json.blk));
    !json.hasOwnProperty("dNowChgRatio") || (this.dNowChgRatio = json.dNowChgRatio);
    !json.hasOwnProperty("dOpenPrice") || (this.dOpenPrice = json.dOpenPrice);
    !json.hasOwnProperty("dOpenChgRatio") || (this.dOpenChgRatio = json.dOpenChgRatio);
}
FuPan.FBlockChgRatio.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FBlockChgRatio.new = function () {
    return new FuPan.FBlockChgRatio();
}
FuPan.FBlockChgRatio.create = function (is) {
    return FuPan.FBlockChgRatio._readFrom(is);
}
FuPan.FTimePrice = function() {
    this.iTime = 0;
    this.dPrice = 0;
    this._classname = "FuPan.FTimePrice";
};
FuPan.FTimePrice.prototype = new TafStream.JceStruct();
FuPan.FTimePrice._classname = "FuPan.FTimePrice";

FuPan.FTimePrice._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FTimePrice._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FTimePrice._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FTimePrice();
    tmp.iTime = is.readInt32(0, false, 0);
    tmp.dPrice = is.readDouble(1, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FTimePrice.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iTime != undefined && this.iTime != 0) {
        os.writeInt32(0, this.iTime);
    }
    if (this.dPrice != undefined && this.dPrice != 0) {
        os.writeDouble(1, this.dPrice);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FTimePrice.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FTimePrice.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FTimePrice.prototype.toObject = function() { 
    var tmp = {};

    tmp.iTime = this.iTime;
    tmp.dPrice = this.dPrice;
    
    return tmp;
}
FuPan.FTimePrice.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iTime") || (this.iTime = json.iTime);
    !json.hasOwnProperty("dPrice") || (this.dPrice = json.dPrice);
}
FuPan.FTimePrice.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FTimePrice.new = function () {
    return new FuPan.FTimePrice();
}
FuPan.FTimePrice.create = function (is) {
    return FuPan.FTimePrice._readFrom(is);
}
FuPan.FIndexPrice = function() {
    this.iMarket = 0;
    this.sCode = "";
    this.vecPrice = new TafStream.List(FuPan.FTimePrice);
    this.dPreClose = 0;
    this._classname = "FuPan.FIndexPrice";
};
FuPan.FIndexPrice.prototype = new TafStream.JceStruct();
FuPan.FIndexPrice._classname = "FuPan.FIndexPrice";

FuPan.FIndexPrice._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FIndexPrice._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FIndexPrice._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FIndexPrice();
    tmp.iMarket = is.readInt32(0, false, 0);
    tmp.sCode = is.readString(1, false, "");
    tmp.vecPrice = is.readList(2, false, TafStream.List(FuPan.FTimePrice));
    tmp.dPreClose = is.readDouble(3, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FIndexPrice.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iMarket != undefined && this.iMarket != 0) {
        os.writeInt32(0, this.iMarket);
    }
    if (this.sCode != undefined && this.sCode != "") {
        os.writeString(1, this.sCode);
    }
    if (this.vecPrice != undefined) {
        os.writeList(2, this.vecPrice);
    }
    if (this.dPreClose != undefined && this.dPreClose != 0) {
        os.writeDouble(3, this.dPreClose);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FIndexPrice.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FIndexPrice.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FIndexPrice.prototype.toObject = function() { 
    var tmp = {};

    tmp.iMarket = this.iMarket;
    tmp.sCode = this.sCode;
    tmp.vecPrice = this.vecPrice.toObject();
    tmp.dPreClose = this.dPreClose;
    
    return tmp;
}
FuPan.FIndexPrice.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iMarket") || (this.iMarket = json.iMarket);
    !json.hasOwnProperty("sCode") || (this.sCode = json.sCode);
    !json.hasOwnProperty("vecPrice") || (this.vecPrice.readFromObject(json.vecPrice));
    !json.hasOwnProperty("dPreClose") || (this.dPreClose = json.dPreClose);
}
FuPan.FIndexPrice.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FIndexPrice.new = function () {
    return new FuPan.FIndexPrice();
}
FuPan.FIndexPrice.create = function (is) {
    return FuPan.FIndexPrice._readFrom(is);
}
FuPan.FCaUnuAcTopBlkStk = function() {
    this.stCaUnuActblk = new FuPan.FBlkLastCaUnuAct();
    this.vecCaUnuActStk = new TafStream.List(FuPan.FStkLastCaUnuAct);
    this._classname = "FuPan.FCaUnuAcTopBlkStk";
};
FuPan.FCaUnuAcTopBlkStk.prototype = new TafStream.JceStruct();
FuPan.FCaUnuAcTopBlkStk._classname = "FuPan.FCaUnuAcTopBlkStk";

FuPan.FCaUnuAcTopBlkStk._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FCaUnuAcTopBlkStk._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FCaUnuAcTopBlkStk._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FCaUnuAcTopBlkStk();
    tmp.stCaUnuActblk = is.readStruct(0, false, FuPan.FBlkLastCaUnuAct);
    tmp.vecCaUnuActStk = is.readList(1, false, TafStream.List(FuPan.FStkLastCaUnuAct));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FCaUnuAcTopBlkStk.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.stCaUnuActblk);
    if (this.vecCaUnuActStk != undefined) {
        os.writeList(1, this.vecCaUnuActStk);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FCaUnuAcTopBlkStk.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FCaUnuAcTopBlkStk.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FCaUnuAcTopBlkStk.prototype.toObject = function() { 
    var tmp = {};

    tmp.stCaUnuActblk = this.stCaUnuActblk.toObject();
    tmp.vecCaUnuActStk = this.vecCaUnuActStk.toObject();
    
    return tmp;
}
FuPan.FCaUnuAcTopBlkStk.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("stCaUnuActblk") || (this.stCaUnuActblk.readFromObject(json.stCaUnuActblk));
    !json.hasOwnProperty("vecCaUnuActStk") || (this.vecCaUnuActStk.readFromObject(json.vecCaUnuActStk));
}
FuPan.FCaUnuAcTopBlkStk.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FCaUnuAcTopBlkStk.new = function () {
    return new FuPan.FCaUnuAcTopBlkStk();
}
FuPan.FCaUnuAcTopBlkStk.create = function (is) {
    return FuPan.FCaUnuAcTopBlkStk._readFrom(is);
}
FuPan.FCaUnuActHotBlockInfo = function() {
    this.block = new _TAF_MODULE_A_.FuPan.FBlockSimpleInfo();
    this.dHot = 0;
    this.dChgRatio = 0;
    this._classname = "FuPan.FCaUnuActHotBlockInfo";
};
FuPan.FCaUnuActHotBlockInfo.prototype = new TafStream.JceStruct();
FuPan.FCaUnuActHotBlockInfo._classname = "FuPan.FCaUnuActHotBlockInfo";

FuPan.FCaUnuActHotBlockInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FCaUnuActHotBlockInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FCaUnuActHotBlockInfo._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FCaUnuActHotBlockInfo();
    tmp.block = is.readStruct(0, false, _TAF_MODULE_A_.FuPan.FBlockSimpleInfo);
    tmp.dHot = is.readDouble(1, false, 0);
    tmp.dChgRatio = is.readDouble(2, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FCaUnuActHotBlockInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.block);
    if (this.dHot != undefined && this.dHot != 0) {
        os.writeDouble(1, this.dHot);
    }
    if (this.dChgRatio != undefined && this.dChgRatio != 0) {
        os.writeDouble(2, this.dChgRatio);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FCaUnuActHotBlockInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FCaUnuActHotBlockInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FCaUnuActHotBlockInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.block = this.block.toObject();
    tmp.dHot = this.dHot;
    tmp.dChgRatio = this.dChgRatio;
    
    return tmp;
}
FuPan.FCaUnuActHotBlockInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("block") || (this.block.readFromObject(json.block));
    !json.hasOwnProperty("dHot") || (this.dHot = json.dHot);
    !json.hasOwnProperty("dChgRatio") || (this.dChgRatio = json.dChgRatio);
}
FuPan.FCaUnuActHotBlockInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FCaUnuActHotBlockInfo.new = function () {
    return new FuPan.FCaUnuActHotBlockInfo();
}
FuPan.FCaUnuActHotBlockInfo.create = function (is) {
    return FuPan.FCaUnuActHotBlockInfo._readFrom(is);
}
FuPan.FCaUnuActHotStockInfo = function() {
    this.stk = new _TAF_MODULE_A_.FuPan.StkSimpInfo();
    this.eCaType = FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS;
    this.dCaUnuChgRatio = 0;
    this.iConnBoradNum = 0;
    this.bIsActZT = true;
    this._classname = "FuPan.FCaUnuActHotStockInfo";
};
FuPan.FCaUnuActHotStockInfo.prototype = new TafStream.JceStruct();
FuPan.FCaUnuActHotStockInfo._classname = "FuPan.FCaUnuActHotStockInfo";

FuPan.FCaUnuActHotStockInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FCaUnuActHotStockInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FCaUnuActHotStockInfo._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FCaUnuActHotStockInfo();
    tmp.stk = is.readStruct(0, false, _TAF_MODULE_A_.FuPan.StkSimpInfo);
    tmp.eCaType = is.readInt32(1, false, FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS);
    tmp.dCaUnuChgRatio = is.readDouble(2, false, 0);
    tmp.iConnBoradNum = is.readInt32(3, false, 0);
    tmp.bIsActZT = is.readBoolean(4, false, true);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FCaUnuActHotStockInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.stk);
    if (this.eCaType != undefined) {
        os.writeInt32(1, this.eCaType);
    }
    if (this.dCaUnuChgRatio != undefined && this.dCaUnuChgRatio != 0) {
        os.writeDouble(2, this.dCaUnuChgRatio);
    }
    if (this.iConnBoradNum != undefined && this.iConnBoradNum != 0) {
        os.writeInt32(3, this.iConnBoradNum);
    }
    if (this.bIsActZT != undefined && this.bIsActZT != true) {
        os.writeBoolean(4, this.bIsActZT);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FCaUnuActHotStockInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FCaUnuActHotStockInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FCaUnuActHotStockInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.stk = this.stk.toObject();
    tmp.eCaType = this.eCaType;
    tmp.dCaUnuChgRatio = this.dCaUnuChgRatio;
    tmp.iConnBoradNum = this.iConnBoradNum;
    tmp.bIsActZT = this.bIsActZT;
    
    return tmp;
}
FuPan.FCaUnuActHotStockInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("stk") || (this.stk.readFromObject(json.stk));
    !json.hasOwnProperty("eCaType") || (this.eCaType = json.eCaType);
    !json.hasOwnProperty("dCaUnuChgRatio") || (this.dCaUnuChgRatio = json.dCaUnuChgRatio);
    !json.hasOwnProperty("iConnBoradNum") || (this.iConnBoradNum = json.iConnBoradNum);
    !json.hasOwnProperty("bIsActZT") || (this.bIsActZT = json.bIsActZT);
}
FuPan.FCaUnuActHotStockInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FCaUnuActHotStockInfo.new = function () {
    return new FuPan.FCaUnuActHotStockInfo();
}
FuPan.FCaUnuActHotStockInfo.create = function (is) {
    return FuPan.FCaUnuActHotStockInfo._readFrom(is);
}
FuPan.FCaUnuActHotSubect = function() {
    this.blk = new FuPan.FCaUnuActHotBlockInfo();
    this.vecHotStk = new TafStream.List(FuPan.FCaUnuActHotStockInfo);
    this._classname = "FuPan.FCaUnuActHotSubect";
};
FuPan.FCaUnuActHotSubect.prototype = new TafStream.JceStruct();
FuPan.FCaUnuActHotSubect._classname = "FuPan.FCaUnuActHotSubect";

FuPan.FCaUnuActHotSubect._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FCaUnuActHotSubect._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FCaUnuActHotSubect._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FCaUnuActHotSubect();
    tmp.blk = is.readStruct(0, false, FuPan.FCaUnuActHotBlockInfo);
    tmp.vecHotStk = is.readList(1, false, TafStream.List(FuPan.FCaUnuActHotStockInfo));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FCaUnuActHotSubect.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.blk);
    if (this.vecHotStk != undefined) {
        os.writeList(1, this.vecHotStk);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FCaUnuActHotSubect.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FCaUnuActHotSubect.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FCaUnuActHotSubect.prototype.toObject = function() { 
    var tmp = {};

    tmp.blk = this.blk.toObject();
    tmp.vecHotStk = this.vecHotStk.toObject();
    
    return tmp;
}
FuPan.FCaUnuActHotSubect.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("blk") || (this.blk.readFromObject(json.blk));
    !json.hasOwnProperty("vecHotStk") || (this.vecHotStk.readFromObject(json.vecHotStk));
}
FuPan.FCaUnuActHotSubect.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FCaUnuActHotSubect.new = function () {
    return new FuPan.FCaUnuActHotSubect();
}
FuPan.FCaUnuActHotSubect.create = function (is) {
    return FuPan.FCaUnuActHotSubect._readFrom(is);
}
FuPan.FCaExternData = function() {
    this.iDate = 0;
    this.eCaType = FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS;
    this.vecMarketZdNum = new TafStream.List(FuPan.FMarketZdFenBu);
    this.vecBlkRatio = new TafStream.List(FuPan.FBlockChgRatio);
    this.vecIdxPrice = new TafStream.List(FuPan.FIndexPrice);
    this.vecTopBlkStk = new TafStream.List(FuPan.FCaUnuAcTopBlkStk);
    this.vecTopHotSubject = new TafStream.List(FuPan.FCaUnuActHotSubect);
    this._classname = "FuPan.FCaExternData";
};
FuPan.FCaExternData.prototype = new TafStream.JceStruct();
FuPan.FCaExternData._classname = "FuPan.FCaExternData";

FuPan.FCaExternData._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FCaExternData._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FCaExternData._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FCaExternData();
    tmp.iDate = is.readInt32(0, false, 0);
    tmp.eCaType = is.readInt32(1, false, FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS);
    tmp.vecMarketZdNum = is.readList(2, false, TafStream.List(FuPan.FMarketZdFenBu));
    tmp.vecBlkRatio = is.readList(3, false, TafStream.List(FuPan.FBlockChgRatio));
    tmp.vecIdxPrice = is.readList(4, false, TafStream.List(FuPan.FIndexPrice));
    tmp.vecTopBlkStk = is.readList(5, false, TafStream.List(FuPan.FCaUnuAcTopBlkStk));
    tmp.vecTopHotSubject = is.readList(6, false, TafStream.List(FuPan.FCaUnuActHotSubect));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FCaExternData.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iDate != undefined && this.iDate != 0) {
        os.writeInt32(0, this.iDate);
    }
    if (this.eCaType != undefined) {
        os.writeInt32(1, this.eCaType);
    }
    if (this.vecMarketZdNum != undefined) {
        os.writeList(2, this.vecMarketZdNum);
    }
    if (this.vecBlkRatio != undefined) {
        os.writeList(3, this.vecBlkRatio);
    }
    if (this.vecIdxPrice != undefined) {
        os.writeList(4, this.vecIdxPrice);
    }
    if (this.vecTopBlkStk != undefined) {
        os.writeList(5, this.vecTopBlkStk);
    }
    if (this.vecTopHotSubject != undefined) {
        os.writeList(6, this.vecTopHotSubject);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FCaExternData.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FCaExternData.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FCaExternData.prototype.toObject = function() { 
    var tmp = {};

    tmp.iDate = this.iDate;
    tmp.eCaType = this.eCaType;
    tmp.vecMarketZdNum = this.vecMarketZdNum.toObject();
    tmp.vecBlkRatio = this.vecBlkRatio.toObject();
    tmp.vecIdxPrice = this.vecIdxPrice.toObject();
    tmp.vecTopBlkStk = this.vecTopBlkStk.toObject();
    tmp.vecTopHotSubject = this.vecTopHotSubject.toObject();
    
    return tmp;
}
FuPan.FCaExternData.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iDate") || (this.iDate = json.iDate);
    !json.hasOwnProperty("eCaType") || (this.eCaType = json.eCaType);
    !json.hasOwnProperty("vecMarketZdNum") || (this.vecMarketZdNum.readFromObject(json.vecMarketZdNum));
    !json.hasOwnProperty("vecBlkRatio") || (this.vecBlkRatio.readFromObject(json.vecBlkRatio));
    !json.hasOwnProperty("vecIdxPrice") || (this.vecIdxPrice.readFromObject(json.vecIdxPrice));
    !json.hasOwnProperty("vecTopBlkStk") || (this.vecTopBlkStk.readFromObject(json.vecTopBlkStk));
    !json.hasOwnProperty("vecTopHotSubject") || (this.vecTopHotSubject.readFromObject(json.vecTopHotSubject));
}
FuPan.FCaExternData.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FCaExternData.new = function () {
    return new FuPan.FCaExternData();
}
FuPan.FCaExternData.create = function (is) {
    return FuPan.FCaExternData._readFrom(is);
}
FuPan.FCaUnuActData = function() {
    this.iDate = 0;
    this.stCaTs = new FuPan.FCaTsData();
    this.stExternData = new FuPan.FCaExternData();
    this.vecCaUnuActData = new TafStream.List(FuPan.FCaUnuActTypeData);
    this._classname = "FuPan.FCaUnuActData";
};
FuPan.FCaUnuActData.prototype = new TafStream.JceStruct();
FuPan.FCaUnuActData._classname = "FuPan.FCaUnuActData";

FuPan.FCaUnuActData._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FCaUnuActData._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FCaUnuActData._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FCaUnuActData();
    tmp.iDate = is.readInt32(0, false, 0);
    tmp.stCaTs = is.readStruct(1, false, FuPan.FCaTsData);
    tmp.stExternData = is.readStruct(2, false, FuPan.FCaExternData);
    tmp.vecCaUnuActData = is.readList(3, false, TafStream.List(FuPan.FCaUnuActTypeData));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FCaUnuActData.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iDate != undefined && this.iDate != 0) {
        os.writeInt32(0, this.iDate);
    }
    os.writeStruct(1, this.stCaTs);
    os.writeStruct(2, this.stExternData);
    if (this.vecCaUnuActData != undefined) {
        os.writeList(3, this.vecCaUnuActData);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FCaUnuActData.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FCaUnuActData.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FCaUnuActData.prototype.toObject = function() { 
    var tmp = {};

    tmp.iDate = this.iDate;
    tmp.stCaTs = this.stCaTs.toObject();
    tmp.stExternData = this.stExternData.toObject();
    tmp.vecCaUnuActData = this.vecCaUnuActData.toObject();
    
    return tmp;
}
FuPan.FCaUnuActData.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iDate") || (this.iDate = json.iDate);
    !json.hasOwnProperty("stCaTs") || (this.stCaTs.readFromObject(json.stCaTs));
    !json.hasOwnProperty("stExternData") || (this.stExternData.readFromObject(json.stExternData));
    !json.hasOwnProperty("vecCaUnuActData") || (this.vecCaUnuActData.readFromObject(json.vecCaUnuActData));
}
FuPan.FCaUnuActData.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FCaUnuActData.new = function () {
    return new FuPan.FCaUnuActData();
}
FuPan.FCaUnuActData.create = function (is) {
    return FuPan.FCaUnuActData._readFrom(is);
}
FuPan.FCaUnuActTypeVecInfo = function() {
    this.eCaType = FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS;
    this.vecUnuActInfo = new TafStream.List(FuPan.FCaUnuActInfo);
    this._classname = "FuPan.FCaUnuActTypeVecInfo";
};
FuPan.FCaUnuActTypeVecInfo.prototype = new TafStream.JceStruct();
FuPan.FCaUnuActTypeVecInfo._classname = "FuPan.FCaUnuActTypeVecInfo";

FuPan.FCaUnuActTypeVecInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FCaUnuActTypeVecInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FCaUnuActTypeVecInfo._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FCaUnuActTypeVecInfo();
    tmp.eCaType = is.readInt32(0, false, FuPan.E_CALL_AUCTION_DATA_TYPE.E_CA_DATA_TYPE_TS);
    tmp.vecUnuActInfo = is.readList(1, false, TafStream.List(FuPan.FCaUnuActInfo));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FCaUnuActTypeVecInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.eCaType != undefined) {
        os.writeInt32(0, this.eCaType);
    }
    if (this.vecUnuActInfo != undefined) {
        os.writeList(1, this.vecUnuActInfo);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FCaUnuActTypeVecInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FCaUnuActTypeVecInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FCaUnuActTypeVecInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.eCaType = this.eCaType;
    tmp.vecUnuActInfo = this.vecUnuActInfo.toObject();
    
    return tmp;
}
FuPan.FCaUnuActTypeVecInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("eCaType") || (this.eCaType = json.eCaType);
    !json.hasOwnProperty("vecUnuActInfo") || (this.vecUnuActInfo.readFromObject(json.vecUnuActInfo));
}
FuPan.FCaUnuActTypeVecInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FCaUnuActTypeVecInfo.new = function () {
    return new FuPan.FCaUnuActTypeVecInfo();
}
FuPan.FCaUnuActTypeVecInfo.create = function (is) {
    return FuPan.FCaUnuActTypeVecInfo._readFrom(is);
}
FuPan.FStkAllCaUnuAct = function() {
    this.stk = new _TAF_MODULE_A_.FuPan.StockInfo();
    this.vecTs = new TafStream.List(FuPan.FStkCaTs);
    this.vecUnuAct = new TafStream.List(FuPan.FCaUnuActTypeVecInfo);
    this.dOpenPrice = 0;
    this.dOpenChgRatio = 0;
    this.dOpenAmount = 0;
    this.dNowChgRatio = 0;
    this._classname = "FuPan.FStkAllCaUnuAct";
};
FuPan.FStkAllCaUnuAct.prototype = new TafStream.JceStruct();
FuPan.FStkAllCaUnuAct._classname = "FuPan.FStkAllCaUnuAct";

FuPan.FStkAllCaUnuAct._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FStkAllCaUnuAct._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FStkAllCaUnuAct._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FStkAllCaUnuAct();
    tmp.stk = is.readStruct(0, false, _TAF_MODULE_A_.FuPan.StockInfo);
    tmp.vecTs = is.readList(1, false, TafStream.List(FuPan.FStkCaTs));
    tmp.vecUnuAct = is.readList(2, false, TafStream.List(FuPan.FCaUnuActTypeVecInfo));
    tmp.dOpenPrice = is.readDouble(3, false, 0);
    tmp.dOpenChgRatio = is.readDouble(4, false, 0);
    tmp.dOpenAmount = is.readDouble(5, false, 0);
    tmp.dNowChgRatio = is.readDouble(6, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FStkAllCaUnuAct.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.stk);
    if (this.vecTs != undefined) {
        os.writeList(1, this.vecTs);
    }
    if (this.vecUnuAct != undefined) {
        os.writeList(2, this.vecUnuAct);
    }
    if (this.dOpenPrice != undefined && this.dOpenPrice != 0) {
        os.writeDouble(3, this.dOpenPrice);
    }
    if (this.dOpenChgRatio != undefined && this.dOpenChgRatio != 0) {
        os.writeDouble(4, this.dOpenChgRatio);
    }
    if (this.dOpenAmount != undefined && this.dOpenAmount != 0) {
        os.writeDouble(5, this.dOpenAmount);
    }
    if (this.dNowChgRatio != undefined && this.dNowChgRatio != 0) {
        os.writeDouble(6, this.dNowChgRatio);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FStkAllCaUnuAct.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FStkAllCaUnuAct.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FStkAllCaUnuAct.prototype.toObject = function() { 
    var tmp = {};

    tmp.stk = this.stk.toObject();
    tmp.vecTs = this.vecTs.toObject();
    tmp.vecUnuAct = this.vecUnuAct.toObject();
    tmp.dOpenPrice = this.dOpenPrice;
    tmp.dOpenChgRatio = this.dOpenChgRatio;
    tmp.dOpenAmount = this.dOpenAmount;
    tmp.dNowChgRatio = this.dNowChgRatio;
    
    return tmp;
}
FuPan.FStkAllCaUnuAct.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("stk") || (this.stk.readFromObject(json.stk));
    !json.hasOwnProperty("vecTs") || (this.vecTs.readFromObject(json.vecTs));
    !json.hasOwnProperty("vecUnuAct") || (this.vecUnuAct.readFromObject(json.vecUnuAct));
    !json.hasOwnProperty("dOpenPrice") || (this.dOpenPrice = json.dOpenPrice);
    !json.hasOwnProperty("dOpenChgRatio") || (this.dOpenChgRatio = json.dOpenChgRatio);
    !json.hasOwnProperty("dOpenAmount") || (this.dOpenAmount = json.dOpenAmount);
    !json.hasOwnProperty("dNowChgRatio") || (this.dNowChgRatio = json.dNowChgRatio);
}
FuPan.FStkAllCaUnuAct.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FStkAllCaUnuAct.new = function () {
    return new FuPan.FStkAllCaUnuAct();
}
FuPan.FStkAllCaUnuAct.create = function (is) {
    return FuPan.FStkAllCaUnuAct._readFrom(is);
}
FuPan.FBlkAllCaUnuAct = function() {
    this.blk = new _TAF_MODULE_A_.FuPan.FBlockSimpleInfo();
    this.vecTs = new TafStream.List(FuPan.FBlkCaTs);
    this.vecUnuAct = new TafStream.List(FuPan.FCaUnuActTypeVecInfo);
    this._classname = "FuPan.FBlkAllCaUnuAct";
};
FuPan.FBlkAllCaUnuAct.prototype = new TafStream.JceStruct();
FuPan.FBlkAllCaUnuAct._classname = "FuPan.FBlkAllCaUnuAct";

FuPan.FBlkAllCaUnuAct._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FBlkAllCaUnuAct._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FBlkAllCaUnuAct._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FBlkAllCaUnuAct();
    tmp.blk = is.readStruct(0, false, _TAF_MODULE_A_.FuPan.FBlockSimpleInfo);
    tmp.vecTs = is.readList(1, false, TafStream.List(FuPan.FBlkCaTs));
    tmp.vecUnuAct = is.readList(2, false, TafStream.List(FuPan.FCaUnuActTypeVecInfo));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FBlkAllCaUnuAct.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.blk);
    if (this.vecTs != undefined) {
        os.writeList(1, this.vecTs);
    }
    if (this.vecUnuAct != undefined) {
        os.writeList(2, this.vecUnuAct);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FBlkAllCaUnuAct.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FBlkAllCaUnuAct.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FBlkAllCaUnuAct.prototype.toObject = function() { 
    var tmp = {};

    tmp.blk = this.blk.toObject();
    tmp.vecTs = this.vecTs.toObject();
    tmp.vecUnuAct = this.vecUnuAct.toObject();
    
    return tmp;
}
FuPan.FBlkAllCaUnuAct.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("blk") || (this.blk.readFromObject(json.blk));
    !json.hasOwnProperty("vecTs") || (this.vecTs.readFromObject(json.vecTs));
    !json.hasOwnProperty("vecUnuAct") || (this.vecUnuAct.readFromObject(json.vecUnuAct));
}
FuPan.FBlkAllCaUnuAct.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FBlkAllCaUnuAct.new = function () {
    return new FuPan.FBlkAllCaUnuAct();
}
FuPan.FBlkAllCaUnuAct.create = function (is) {
    return FuPan.FBlkAllCaUnuAct._readFrom(is);
}
FuPan.FBlkStkAllCaUnuAct = function() {
    this.iDate = 0;
    this.mapStkCaUnuAct = new TafStream.Map(TafStream.String, FuPan.FStkAllCaUnuAct);
    this.mapBlkCaUnuAct = new TafStream.Map(TafStream.String, FuPan.FBlkAllCaUnuAct);
    this._classname = "FuPan.FBlkStkAllCaUnuAct";
};
FuPan.FBlkStkAllCaUnuAct.prototype = new TafStream.JceStruct();
FuPan.FBlkStkAllCaUnuAct._classname = "FuPan.FBlkStkAllCaUnuAct";

FuPan.FBlkStkAllCaUnuAct._write = function (os, tag, value) { os.writeStruct(tag, value); }
FuPan.FBlkStkAllCaUnuAct._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
FuPan.FBlkStkAllCaUnuAct._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new FuPan.FBlkStkAllCaUnuAct();
    tmp.iDate = is.readInt32(0, false, 0);
    tmp.mapStkCaUnuAct = is.readMap(1, false, TafStream.Map(TafStream.String, FuPan.FStkAllCaUnuAct));
    tmp.mapBlkCaUnuAct = is.readMap(2, false, TafStream.Map(TafStream.String, FuPan.FBlkAllCaUnuAct));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
FuPan.FBlkStkAllCaUnuAct.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iDate != undefined && this.iDate != 0) {
        os.writeInt32(0, this.iDate);
    }
    if (this.mapStkCaUnuAct != undefined) {
        os.writeMap(1, this.mapStkCaUnuAct);
    }
    if (this.mapBlkCaUnuAct != undefined) {
        os.writeMap(2, this.mapBlkCaUnuAct);
    }
    os.resumePrecision && os.resumePrecision();
};
FuPan.FBlkStkAllCaUnuAct.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
FuPan.FBlkStkAllCaUnuAct.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
FuPan.FBlkStkAllCaUnuAct.prototype.toObject = function() { 
    var tmp = {};

    tmp.iDate = this.iDate;
    tmp.mapStkCaUnuAct = this.mapStkCaUnuAct.toObject();
    tmp.mapBlkCaUnuAct = this.mapBlkCaUnuAct.toObject();
    
    return tmp;
}
FuPan.FBlkStkAllCaUnuAct.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iDate") || (this.iDate = json.iDate);
    !json.hasOwnProperty("mapStkCaUnuAct") || (this.mapStkCaUnuAct.readFromObject(json.mapStkCaUnuAct));
    !json.hasOwnProperty("mapBlkCaUnuAct") || (this.mapBlkCaUnuAct.readFromObject(json.mapBlkCaUnuAct));
}
FuPan.FBlkStkAllCaUnuAct.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
FuPan.FBlkStkAllCaUnuAct.new = function () {
    return new FuPan.FBlkStkAllCaUnuAct();
}
FuPan.FBlkStkAllCaUnuAct.create = function (is) {
    return FuPan.FBlkStkAllCaUnuAct._readFrom(is);
}


