// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 5.0.0 by TAF Team.
// Generated from `./RadarData.jce'
// **********************************************************************

var assert    = require('assert');
var TafStream = require('@taf/taf-stream');

if(TafStream.JceStruct == undefined){
TafStream.JceStruct = function() {
this._jce_double_precision_ = -1;
}
TafStream.JceStruct.prototype.setPrecision = function(d) {
if ((d == -1) || (d >= 0 && d <= 15)) {
this._jce_double_precision_ = d;
return true;
}
return false;
}
TafStream.JceStruct.prototype.resetPrecision = function() { this._jce_double_precision_ = -1;}
TafStream.JceStruct.prototype.hasSetPrecision = function() { return (this._jce_double_precision_ >= 0 && this._jce_double_precision_ <= 15);}
TafStream.JceStruct.prototype.getPrecision = function() { return this._jce_double_precision_; }
}



var RadarData = RadarData || {};
module.exports.RadarData = RadarData;

RadarData.E_STARS_LEVEL = {
    E_STARS_NONE : 0,
    E_STARS_LEVEL1 : 1,
    E_STARS_LEVEL2 : 2,
    E_STARS_LEVEL3 : 3,
    E_STARS_LEVEL4 : 4
};

RadarData.E_STARS_LEVEL.etos = function(enm) {
    switch(enm){
        case 0 : return 'E_STARS_NONE';
        case 1 : return 'E_STARS_LEVEL1';
        case 2 : return 'E_STARS_LEVEL2';
        case 3 : return 'E_STARS_LEVEL3';
        case 4 : return 'E_STARS_LEVEL4';
    }
    return undefined;
};

RadarData.E_STARS_LEVEL.stoe = function(enm) {
    switch(enm){
        case 'E_STARS_NONE' : return 0;
        case 'E_STARS_LEVEL1' : return 1;
        case 'E_STARS_LEVEL2' : return 2;
        case 'E_STARS_LEVEL3' : return 3;
        case 'E_STARS_LEVEL4' : return 4;
    }
    return undefined;
};

RadarData.E_STARS_LEVEL._write = function(os, tag, val) { return os.writeInt32(tag, val); }
RadarData.E_STARS_LEVEL._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
RadarData.E_STRENGTH_CHANGE = {
    NO_CHANGE : 1,
    UP_CHANGE : 2,
    DOWN_CHANGE : 3
};

RadarData.E_STRENGTH_CHANGE.etos = function(enm) {
    switch(enm){
        case 1 : return 'NO_CHANGE';
        case 2 : return 'UP_CHANGE';
        case 3 : return 'DOWN_CHANGE';
    }
    return undefined;
};

RadarData.E_STRENGTH_CHANGE.stoe = function(enm) {
    switch(enm){
        case 'NO_CHANGE' : return 1;
        case 'UP_CHANGE' : return 2;
        case 'DOWN_CHANGE' : return 3;
    }
    return undefined;
};

RadarData.E_STRENGTH_CHANGE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
RadarData.E_STRENGTH_CHANGE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
RadarData.E_RADAR_TYPE = {
    E_RADAR_BUY : 1,
    E_RADAR_SELL : 2
};

RadarData.E_RADAR_TYPE.etos = function(enm) {
    switch(enm){
        case 1 : return 'E_RADAR_BUY';
        case 2 : return 'E_RADAR_SELL';
    }
    return undefined;
};

RadarData.E_RADAR_TYPE.stoe = function(enm) {
    switch(enm){
        case 'E_RADAR_BUY' : return 1;
        case 'E_RADAR_SELL' : return 2;
    }
    return undefined;
};

RadarData.E_RADAR_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
RadarData.E_RADAR_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }

RadarData.Temperature = function() {
    this.iMarket = 0;
    this.sCode = "";
    this.iUpdateTime = 0;
    this.dblStrength = 0;
    this.lStrengthBuy = 0;
    this.lStrengthSell = 0;
    this.dblLatent = 0;
    this.lLatentBuy = 0;
    this.lLatentSell = 0;
    this._classname = "RadarData.Temperature";
};
RadarData.Temperature.prototype = new TafStream.JceStruct();
RadarData.Temperature._classname = "RadarData.Temperature";

RadarData.Temperature._write = function (os, tag, value) { os.writeStruct(tag, value); }
RadarData.Temperature._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
RadarData.Temperature._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new RadarData.Temperature();
    tmp.iMarket = is.readInt32(0, false, 0);
    tmp.sCode = is.readString(1, false, "");
    tmp.iUpdateTime = is.readInt32(2, false, 0);
    tmp.dblStrength = is.readDouble(3, false, 0);
    tmp.lStrengthBuy = is.readInt64(4, false, 0);
    tmp.lStrengthSell = is.readInt64(5, false, 0);
    tmp.dblLatent = is.readDouble(6, false, 0);
    tmp.lLatentBuy = is.readInt64(7, false, 0);
    tmp.lLatentSell = is.readInt64(8, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
RadarData.Temperature.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.iMarket);
    os.writeString(1, this.sCode);
    os.writeInt32(2, this.iUpdateTime);
    os.writeDouble(3, this.dblStrength);
    os.writeInt64(4, this.lStrengthBuy);
    os.writeInt64(5, this.lStrengthSell);
    os.writeDouble(6, this.dblLatent);
    os.writeInt64(7, this.lLatentBuy);
    os.writeInt64(8, this.lLatentSell);
    os.resumePrecision && os.resumePrecision();
};
RadarData.Temperature.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
RadarData.Temperature.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
RadarData.Temperature.prototype.toObject = function() { 
    var tmp = {};

    tmp.iMarket = this.iMarket;
    tmp.sCode = this.sCode;
    tmp.iUpdateTime = this.iUpdateTime;
    tmp.dblStrength = this.dblStrength;
    tmp.lStrengthBuy = this.lStrengthBuy;
    tmp.lStrengthSell = this.lStrengthSell;
    tmp.dblLatent = this.dblLatent;
    tmp.lLatentBuy = this.lLatentBuy;
    tmp.lLatentSell = this.lLatentSell;
    
    return tmp;
}
RadarData.Temperature.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iMarket") || (this.iMarket = json.iMarket);
    !json.hasOwnProperty("sCode") || (this.sCode = json.sCode);
    !json.hasOwnProperty("iUpdateTime") || (this.iUpdateTime = json.iUpdateTime);
    !json.hasOwnProperty("dblStrength") || (this.dblStrength = json.dblStrength);
    !json.hasOwnProperty("lStrengthBuy") || (this.lStrengthBuy = json.lStrengthBuy);
    !json.hasOwnProperty("lStrengthSell") || (this.lStrengthSell = json.lStrengthSell);
    !json.hasOwnProperty("dblLatent") || (this.dblLatent = json.dblLatent);
    !json.hasOwnProperty("lLatentBuy") || (this.lLatentBuy = json.lLatentBuy);
    !json.hasOwnProperty("lLatentSell") || (this.lLatentSell = json.lLatentSell);
}
RadarData.Temperature.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
RadarData.Temperature.new = function () {
    return new RadarData.Temperature();
}
RadarData.Temperature.create = function (is) {
    return RadarData.Temperature._readFrom(is);
}
RadarData.RadarQt = function() {
    this.iStockID = 0;
    this.iTime = 0;
    this.dblStrength = 0;
    this.eStarsLevel = RadarData.E_STARS_LEVEL.E_STARS_NONE;
    this.lStrengthBuy = 0;
    this.lStrengthSell = 0;
    this.eChgFlag = RadarData.E_STRENGTH_CHANGE.NO_CHANGE;
    this.dNowPrice = 0;
    this.dPrevPrice = 0;
    this._classname = "RadarData.RadarQt";
};
RadarData.RadarQt.prototype = new TafStream.JceStruct();
RadarData.RadarQt._classname = "RadarData.RadarQt";

RadarData.RadarQt._write = function (os, tag, value) { os.writeStruct(tag, value); }
RadarData.RadarQt._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
RadarData.RadarQt._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new RadarData.RadarQt();
    tmp.iStockID = is.readInt32(1, false, 0);
    tmp.iTime = is.readInt32(2, false, 0);
    tmp.dblStrength = is.readDouble(3, false, 0);
    tmp.eStarsLevel = is.readInt32(4, false, RadarData.E_STARS_LEVEL.E_STARS_NONE);
    tmp.lStrengthBuy = is.readInt64(5, false, 0);
    tmp.lStrengthSell = is.readInt64(6, false, 0);
    tmp.eChgFlag = is.readInt32(7, false, RadarData.E_STRENGTH_CHANGE.NO_CHANGE);
    tmp.dNowPrice = is.readDouble(8, false, 0);
    tmp.dPrevPrice = is.readDouble(9, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
RadarData.RadarQt.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(1, this.iStockID);
    os.writeInt32(2, this.iTime);
    os.writeDouble(3, this.dblStrength);
    os.writeInt32(4, this.eStarsLevel);
    os.writeInt64(5, this.lStrengthBuy);
    os.writeInt64(6, this.lStrengthSell);
    os.writeInt32(7, this.eChgFlag);
    os.writeDouble(8, this.dNowPrice);
    os.writeDouble(9, this.dPrevPrice);
    os.resumePrecision && os.resumePrecision();
};
RadarData.RadarQt.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
RadarData.RadarQt.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
RadarData.RadarQt.prototype.toObject = function() { 
    var tmp = {};

    tmp.iStockID = this.iStockID;
    tmp.iTime = this.iTime;
    tmp.dblStrength = this.dblStrength;
    tmp.eStarsLevel = this.eStarsLevel;
    tmp.lStrengthBuy = this.lStrengthBuy;
    tmp.lStrengthSell = this.lStrengthSell;
    tmp.eChgFlag = this.eChgFlag;
    tmp.dNowPrice = this.dNowPrice;
    tmp.dPrevPrice = this.dPrevPrice;
    
    return tmp;
}
RadarData.RadarQt.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iStockID") || (this.iStockID = json.iStockID);
    !json.hasOwnProperty("iTime") || (this.iTime = json.iTime);
    !json.hasOwnProperty("dblStrength") || (this.dblStrength = json.dblStrength);
    !json.hasOwnProperty("eStarsLevel") || (this.eStarsLevel = json.eStarsLevel);
    !json.hasOwnProperty("lStrengthBuy") || (this.lStrengthBuy = json.lStrengthBuy);
    !json.hasOwnProperty("lStrengthSell") || (this.lStrengthSell = json.lStrengthSell);
    !json.hasOwnProperty("eChgFlag") || (this.eChgFlag = json.eChgFlag);
    !json.hasOwnProperty("dNowPrice") || (this.dNowPrice = json.dNowPrice);
    !json.hasOwnProperty("dPrevPrice") || (this.dPrevPrice = json.dPrevPrice);
}
RadarData.RadarQt.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
RadarData.RadarQt.new = function () {
    return new RadarData.RadarQt();
}
RadarData.RadarQt.create = function (is) {
    return RadarData.RadarQt._readFrom(is);
}
RadarData.RadarChg = function() {
    this.iStockID = 0;
    this.iTime = 0;
    this.eType = RadarData.E_RADAR_TYPE.E_RADAR_BUY;
    this.eStarsLevel = RadarData.E_STARS_LEVEL.E_STARS_NONE;
    this.lStrengthBuy = 0;
    this.lStrengthSell = 0;
    this.eChgFlag = RadarData.E_STRENGTH_CHANGE.NO_CHANGE;
    this.dNowPrice = 0;
    this.dPrevPrice = 0;
    this._classname = "RadarData.RadarChg";
};
RadarData.RadarChg.prototype = new TafStream.JceStruct();
RadarData.RadarChg._classname = "RadarData.RadarChg";

RadarData.RadarChg._write = function (os, tag, value) { os.writeStruct(tag, value); }
RadarData.RadarChg._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
RadarData.RadarChg._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new RadarData.RadarChg();
    tmp.iStockID = is.readInt32(1, false, 0);
    tmp.iTime = is.readInt32(2, false, 0);
    tmp.eType = is.readInt32(3, false, RadarData.E_RADAR_TYPE.E_RADAR_BUY);
    tmp.eStarsLevel = is.readInt32(4, false, RadarData.E_STARS_LEVEL.E_STARS_NONE);
    tmp.lStrengthBuy = is.readInt64(5, false, 0);
    tmp.lStrengthSell = is.readInt64(6, false, 0);
    tmp.eChgFlag = is.readInt32(7, false, RadarData.E_STRENGTH_CHANGE.NO_CHANGE);
    tmp.dNowPrice = is.readDouble(8, false, 0);
    tmp.dPrevPrice = is.readDouble(9, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
RadarData.RadarChg.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(1, this.iStockID);
    os.writeInt32(2, this.iTime);
    os.writeInt32(3, this.eType);
    os.writeInt32(4, this.eStarsLevel);
    os.writeInt64(5, this.lStrengthBuy);
    os.writeInt64(6, this.lStrengthSell);
    os.writeInt32(7, this.eChgFlag);
    os.writeDouble(8, this.dNowPrice);
    os.writeDouble(9, this.dPrevPrice);
    os.resumePrecision && os.resumePrecision();
};
RadarData.RadarChg.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
RadarData.RadarChg.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
RadarData.RadarChg.prototype.toObject = function() { 
    var tmp = {};

    tmp.iStockID = this.iStockID;
    tmp.iTime = this.iTime;
    tmp.eType = this.eType;
    tmp.eStarsLevel = this.eStarsLevel;
    tmp.lStrengthBuy = this.lStrengthBuy;
    tmp.lStrengthSell = this.lStrengthSell;
    tmp.eChgFlag = this.eChgFlag;
    tmp.dNowPrice = this.dNowPrice;
    tmp.dPrevPrice = this.dPrevPrice;
    
    return tmp;
}
RadarData.RadarChg.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iStockID") || (this.iStockID = json.iStockID);
    !json.hasOwnProperty("iTime") || (this.iTime = json.iTime);
    !json.hasOwnProperty("eType") || (this.eType = json.eType);
    !json.hasOwnProperty("eStarsLevel") || (this.eStarsLevel = json.eStarsLevel);
    !json.hasOwnProperty("lStrengthBuy") || (this.lStrengthBuy = json.lStrengthBuy);
    !json.hasOwnProperty("lStrengthSell") || (this.lStrengthSell = json.lStrengthSell);
    !json.hasOwnProperty("eChgFlag") || (this.eChgFlag = json.eChgFlag);
    !json.hasOwnProperty("dNowPrice") || (this.dNowPrice = json.dNowPrice);
    !json.hasOwnProperty("dPrevPrice") || (this.dPrevPrice = json.dPrevPrice);
}
RadarData.RadarChg.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
RadarData.RadarChg.new = function () {
    return new RadarData.RadarChg();
}
RadarData.RadarChg.create = function (is) {
    return RadarData.RadarChg._readFrom(is);
}
RadarData.RadarQtList = function() {
    this.vRadarQt = new TafStream.List(RadarData.RadarQt);
    this._classname = "RadarData.RadarQtList";
};
RadarData.RadarQtList.prototype = new TafStream.JceStruct();
RadarData.RadarQtList._classname = "RadarData.RadarQtList";

RadarData.RadarQtList._write = function (os, tag, value) { os.writeStruct(tag, value); }
RadarData.RadarQtList._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
RadarData.RadarQtList._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new RadarData.RadarQtList();
    tmp.vRadarQt = is.readList(1, false, TafStream.List(RadarData.RadarQt));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
RadarData.RadarQtList.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeList(1, this.vRadarQt);
    os.resumePrecision && os.resumePrecision();
};
RadarData.RadarQtList.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
RadarData.RadarQtList.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
RadarData.RadarQtList.prototype.toObject = function() { 
    var tmp = {};

    tmp.vRadarQt = this.vRadarQt.toObject();
    
    return tmp;
}
RadarData.RadarQtList.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vRadarQt") || (this.vRadarQt.readFromObject(json.vRadarQt));
}
RadarData.RadarQtList.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
RadarData.RadarQtList.new = function () {
    return new RadarData.RadarQtList();
}
RadarData.RadarQtList.create = function (is) {
    return RadarData.RadarQtList._readFrom(is);
}
RadarData.RadarRtMin = function() {
    this.uiStockID = 0;
    this.iTime = 0;
    this.dblRtStrength = 0;
    this.lRtStrengthBuy = 0;
    this.lRtStrengthSell = 0;
    this._classname = "RadarData.RadarRtMin";
};
RadarData.RadarRtMin.prototype = new TafStream.JceStruct();
RadarData.RadarRtMin._classname = "RadarData.RadarRtMin";

RadarData.RadarRtMin._write = function (os, tag, value) { os.writeStruct(tag, value); }
RadarData.RadarRtMin._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
RadarData.RadarRtMin._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new RadarData.RadarRtMin();
    tmp.uiStockID = is.readUInt32(1, false, 0);
    tmp.iTime = is.readInt32(2, false, 0);
    tmp.dblRtStrength = is.readDouble(3, false, 0);
    tmp.lRtStrengthBuy = is.readInt64(4, false, 0);
    tmp.lRtStrengthSell = is.readInt64(5, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
RadarData.RadarRtMin.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeUInt32(1, this.uiStockID);
    os.writeInt32(2, this.iTime);
    os.writeDouble(3, this.dblRtStrength);
    os.writeInt64(4, this.lRtStrengthBuy);
    os.writeInt64(5, this.lRtStrengthSell);
    os.resumePrecision && os.resumePrecision();
};
RadarData.RadarRtMin.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
RadarData.RadarRtMin.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
RadarData.RadarRtMin.prototype.toObject = function() { 
    var tmp = {};

    tmp.uiStockID = this.uiStockID;
    tmp.iTime = this.iTime;
    tmp.dblRtStrength = this.dblRtStrength;
    tmp.lRtStrengthBuy = this.lRtStrengthBuy;
    tmp.lRtStrengthSell = this.lRtStrengthSell;
    
    return tmp;
}
RadarData.RadarRtMin.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("uiStockID") || (this.uiStockID = json.uiStockID);
    !json.hasOwnProperty("iTime") || (this.iTime = json.iTime);
    !json.hasOwnProperty("dblRtStrength") || (this.dblRtStrength = json.dblRtStrength);
    !json.hasOwnProperty("lRtStrengthBuy") || (this.lRtStrengthBuy = json.lRtStrengthBuy);
    !json.hasOwnProperty("lRtStrengthSell") || (this.lRtStrengthSell = json.lRtStrengthSell);
}
RadarData.RadarRtMin.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
RadarData.RadarRtMin.new = function () {
    return new RadarData.RadarRtMin();
}
RadarData.RadarRtMin.create = function (is) {
    return RadarData.RadarRtMin._readFrom(is);
}
RadarData.RadarRtMinList = function() {
    this.bClear = true;
    this.uiStockID = 0;
    this.vData = new TafStream.List(RadarData.RadarRtMin);
    this._classname = "RadarData.RadarRtMinList";
};
RadarData.RadarRtMinList.prototype = new TafStream.JceStruct();
RadarData.RadarRtMinList._classname = "RadarData.RadarRtMinList";

RadarData.RadarRtMinList._write = function (os, tag, value) { os.writeStruct(tag, value); }
RadarData.RadarRtMinList._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
RadarData.RadarRtMinList._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new RadarData.RadarRtMinList();
    tmp.bClear = is.readBoolean(1, false, true);
    tmp.uiStockID = is.readUInt32(2, false, 0);
    tmp.vData = is.readList(3, false, TafStream.List(RadarData.RadarRtMin));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
RadarData.RadarRtMinList.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeBoolean(1, this.bClear);
    os.writeUInt32(2, this.uiStockID);
    os.writeList(3, this.vData);
    os.resumePrecision && os.resumePrecision();
};
RadarData.RadarRtMinList.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
RadarData.RadarRtMinList.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
RadarData.RadarRtMinList.prototype.toObject = function() { 
    var tmp = {};

    tmp.bClear = this.bClear;
    tmp.uiStockID = this.uiStockID;
    tmp.vData = this.vData.toObject();
    
    return tmp;
}
RadarData.RadarRtMinList.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("bClear") || (this.bClear = json.bClear);
    !json.hasOwnProperty("uiStockID") || (this.uiStockID = json.uiStockID);
    !json.hasOwnProperty("vData") || (this.vData.readFromObject(json.vData));
}
RadarData.RadarRtMinList.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
RadarData.RadarRtMinList.new = function () {
    return new RadarData.RadarRtMinList();
}
RadarData.RadarRtMinList.create = function (is) {
    return RadarData.RadarRtMinList._readFrom(is);
}
RadarData.RadarRtMinBatchList = function() {
    this.vStock = new TafStream.List(RadarData.RadarRtMinList);
    this._classname = "RadarData.RadarRtMinBatchList";
};
RadarData.RadarRtMinBatchList.prototype = new TafStream.JceStruct();
RadarData.RadarRtMinBatchList._classname = "RadarData.RadarRtMinBatchList";

RadarData.RadarRtMinBatchList._write = function (os, tag, value) { os.writeStruct(tag, value); }
RadarData.RadarRtMinBatchList._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
RadarData.RadarRtMinBatchList._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new RadarData.RadarRtMinBatchList();
    tmp.vStock = is.readList(1, false, TafStream.List(RadarData.RadarRtMinList));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
RadarData.RadarRtMinBatchList.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeList(1, this.vStock);
    os.resumePrecision && os.resumePrecision();
};
RadarData.RadarRtMinBatchList.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
RadarData.RadarRtMinBatchList.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
RadarData.RadarRtMinBatchList.prototype.toObject = function() { 
    var tmp = {};

    tmp.vStock = this.vStock.toObject();
    
    return tmp;
}
RadarData.RadarRtMinBatchList.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vStock") || (this.vStock.readFromObject(json.vStock));
}
RadarData.RadarRtMinBatchList.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
RadarData.RadarRtMinBatchList.new = function () {
    return new RadarData.RadarRtMinBatchList();
}
RadarData.RadarRtMinBatchList.create = function (is) {
    return RadarData.RadarRtMinBatchList._readFrom(is);
}
RadarData.TempList = function() {
    this.iDate = 0;
    this.iFlag = 0;
    this.vtTemperature = new TafStream.List(RadarData.Temperature);
    this._classname = "RadarData.TempList";
};
RadarData.TempList.prototype = new TafStream.JceStruct();
RadarData.TempList._classname = "RadarData.TempList";

RadarData.TempList._write = function (os, tag, value) { os.writeStruct(tag, value); }
RadarData.TempList._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
RadarData.TempList._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new RadarData.TempList();
    tmp.iDate = is.readInt32(0, false, 0);
    tmp.iFlag = is.readInt32(1, false, 0);
    tmp.vtTemperature = is.readList(2, false, TafStream.List(RadarData.Temperature));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
RadarData.TempList.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.iDate);
    os.writeInt32(1, this.iFlag);
    os.writeList(2, this.vtTemperature);
    os.resumePrecision && os.resumePrecision();
};
RadarData.TempList.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
RadarData.TempList.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
RadarData.TempList.prototype.toObject = function() { 
    var tmp = {};

    tmp.iDate = this.iDate;
    tmp.iFlag = this.iFlag;
    tmp.vtTemperature = this.vtTemperature.toObject();
    
    return tmp;
}
RadarData.TempList.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iDate") || (this.iDate = json.iDate);
    !json.hasOwnProperty("iFlag") || (this.iFlag = json.iFlag);
    !json.hasOwnProperty("vtTemperature") || (this.vtTemperature.readFromObject(json.vtTemperature));
}
RadarData.TempList.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
RadarData.TempList.new = function () {
    return new RadarData.TempList();
}
RadarData.TempList.create = function (is) {
    return RadarData.TempList._readFrom(is);
}


